### DISCUSSION TITLE
Is there any way to block some clients?

### DISCUSSION THREAD

**Discussion by isac322** [0xERR0R/blocky#1002] [Q&A] [answered]
I made it as a public DNS, but some overseas IPs are continuously sending unnecessary requests. It would be nice to be able to deny DNS requests based on IP.

**Comment by kwitsch** [comment, marked as answer]
You could define a blacklist with a regex entry that matches every request and use it for the IP address. 🤔

Something like:

```YAML
blocking:
  blackLists:
    everything:
      - |
        /.*/
  clientGroupsBlock:
    123.123.123.123:
      - everything 
```
