### DISCUSSION TITLE
MikroTik Container port 53 bind permission denied

### DISCUSSION THREAD

**Discussion by xaizone** [0xERR0R/blocky#1069] [Q&A] [answered]
Hey,

trying to run Blocky under MikroTik Containers and I keep getting:

`ERROR server start failed: start tcp listener failed: listen tcp :53: bind: permission denied`.

Any idea how I could solve this? Maybe somebody has run into the same issue already and was able to solve it. Sorry if this is not the right place to ask.

MikroTik config:
```
/interface bridge add name=container
/interface veth add address=172.17.0.2/24 gateway=172.17.0.1 name=veth1
/ip address add address=172.17.0.1/24 interface=container network=172.17.0.0
/ip firewall nat add action=masquerade chain=srcnat src-address=172.17.0.0/24
/container config set registry-url=https://registry-1.docker.io tmpdir=docker/temp
```
_(I excluded unrelated stuff)_

/container/print output:
```
/container/print
 0 name="9dc99852-9ff8-4c6f-9402-aee4836dd86b" tag="spx01/blocky:latest" os="linux" 
   arch="arm64" interface=veth1 root-dir=docker/storage/blocky mounts="" dns="" 
   workdir="/app" logging=yes start-on-boot=yes status=stopped
```

Blocky config:
```yml
upstream:
  default:
    - 1.1.1.1
    - 1.0.0.1

blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  clientGroupsBlock:
    default:
      - ads

port: 53
```
