### DISCUSSION TITLE
PTR without conditional mapping

### DISCUSSION THREAD

**Discussion by dynek** [0xERR0R/blocky#1117] [General]
Hey,

Is it possible to resolve private in-addr.arpa. _addresses_ without specifying conditional mapping ?
e.g. my main dns (router) can resolve `34.0.1.10.in-addr.arpa.` to return its hostname, but when used as upstream through blocky, PTR is empty, except if I specifically add a conditional mapping for `0.1.10.in-addr.arpa.`.

Is this the normal behavior ?

config.yml:
```
log:
  level: info

queryLog:
  type: console

ports:
  dns: 5353
  http: 4000

prometheus:
  enable: true
  path: /metrics

upstream:
  default:
    - tcp+udp:172.19.0.1

upstreamTimeout: 5s

conditional:
  fallbackUpstream: false
  mapping:
    some-domain.com: 10.4.0.138
    0.10.10.in-addr.arpa: 10.4.0.138
    0.1.10.in-addr.arpa: 172.19.0.1
    0.2.10.in-addr.arpa: 172.19.0.1
    0.3.10.in-addr.arpa: 172.19.0.1
    0.4.10.in-addr.arpa: 172.19.0.1

blocking:
  processingConcurrency: 2
  startStrategy: fast
  refreshPeriod: 24h
  blockType: zeroIP
  blackLists:
    ads:
      - [..]
  clientGroupsBlock:
    default:
      - ads
  whiteLists:
    ads:
      - |
        [..]
```

Thank you
