### DISCUSSION TITLE
Blocky not responding to LAN requests?

### DISCUSSION THREAD

**Discussion by ghost** [0xERR0R/blocky#1257] [Q&A]
Hi, I'm new to setting up DNS servers and I seem to have run into a problem. I've followed the documentation to configure everything and it works well if I use ```dig``` on the machine that it's running on. But when I try to connect to it from another machine on the same network, nothing appears in the logs (even in debug logging) and the request times out. I'm thinking it's something about my network but I couldn't find anything that could help. Thank you for your help!

Here's the config.yaml that I'm using now:
```
upstreams:
  strategy: strict
  groups:
    default:
      - https://anycast.uncensoreddns.org/dns-query
      - https://cloudflare-dns.com/dns-query
      - https://dns.google/dns-query
blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Hosts-File.txt
      - https://v.firebog.net/hosts/AdguardDNS.txt
      - https://raw.githubusercontent.com/badmojr/1Hosts/master/Lite/domains.txt
      - https://big.oisd.nl/regex
    trackers:
      - https://raw.githubusercontent.com/mullvad/dns-blocklists/main/lists/doh/privacy/telemetry-apple
      - https://v.firebog.net/hosts/Easyprivacy.txt
  clientGroupsBlock:
    default:
      - ads
      - trackers
ports:
  dns: 127.0.0.1:53
```
