### DISCUSSION TITLE
Blocking TV outbound connections

### DISCUSSION THREAD

**Discussion by NeoPlayer13** [0xERR0R/blocky#1262] [Q&A] [answered]
Is there any way to block all outbound connections from a TV using Blocky and just allow it to resolve just a few apps or websites like netflix, youtube and google?

**Comment by kwitsch** [comment]
You could add a blocking group that blocks everything with a regex and whitelist all domains you want to pass. 🤔

**Reply by NeoPlayer13** [reply]
ok, I tried this:
```
blocking:
  blackLists:
    tv:
      - |
        /^[a-zA-Z0-9_.-]+(\.[a-zA-Z0-9_.-]+)*$"/

  whiteLists:
      tv:
        - |
          google.com
          youtube.com
          netflix.com

  clientGroupsBlock:
    TV:
      - tv

clientLookup:
  clients:
    TV:
      - 10.10.10.29
```

But it didn't work, don't know if the regex expresion is wrong or I misconfigured something.

**Reply by kwitsch** [reply, marked as answer]
I think it should look more like this:

```YaML
blocking:
  blackLists:
    tv:
      - |
        /.*/

  whiteLists:
      tv:
        - |
          google.com
          youtube.com
          netflix.com

  clientGroupsBlock:
    10.10.10.29:
       - tv

```

🤔
