### DISCUSSION TITLE
Can blocky resolve multiple subdomains?

### DISCUSSION THREAD

**Discussion by jameskr97** [0xERR0R/blocky#1285] [Q&A] [answered]
I read the followign line in the config:

> This configuration will also resolve any subdomain of the defined domain. For example a query "printer.lan" or " my.printer.lan" will return 192.168.178.3 as IP address.

Is there a way to configure this to work with multiple subdomains:
Such as with the above example, having `one.my.printer.lan` or `two.one.my.printer.lan` also forward to the `192.168.178.3` domain?

Thank you in advance.

**Comment by kwitsch** [comment, marked as answer]
Simply map both domains to the same IP like:

```YAML
customDNS:
  mapping:
    one.my.printer.lan: 192.168.178.3 
    two.my.printer.lan: 192.168.178.3 
```

**Reply by jameskr97** [reply]
I see! I suppose I was looking to only define the following, and have the remaining subdomains forward automatically.

```yaml
customDNS:
  mapping:
    printer.lan: 192.168.178.3
```

Though, I'll take it that this is not currently a feature.

Thank you.
