### DISCUSSION TITLE
DNS trys to resolve with search before not to

### DISCUSSION THREAD

**Discussion by Serverfrog** [0xERR0R/blocky#1351] [Q&A]
I have the following setup:

- two k3s nodes with MetalLB
  - every node has one instance of blocky running, reachable via the MetalLB defined IP Address
- an Public VPS which is reachable via the public domain and connected to the local network via Wireguard-> test.site
- the Local Domain a subdomain of one which is resolved by Cloudflare -> home.test.site
- an amount of local network Services -> service.cluster.home.test.site
- IPv4 traffic only (ISP has only IPv4)

The Problem:
if i put a 
```

    customDNS:
      rewrite:
        home.test.site: skip-custom

```

Every Local Name will be tried to be resolved via the upstream. But everything else works
If i don't put in in there, the search name will be appended for every request (eg. repo.jellyfin.org will be logged inside blocke as repo.jellyfin.org.home.test.site) which then is resolved to the IP of test.site.

How can i achieve that the Local Domains are reachable via the names, but the name resolution for other domains will not be tried to suffix the test.site?

Config (a part of it, due to the fact mine is quite long due to the amount of services)

```

upstreams:
      groups:
        default:
          - "1.1.1.1"
      strategy: strict
    connectIPVersion: v4
    filtering:
      queryTypes:
        - AAAA
    bootstrapDns:
      - upstream: tcp-tls:one.one.one.one
        ips:
        - 1.1.1.1
    customDNS:
      filterUnmappedTypes: false
      mapping:
        cluster.home.test.site: 192.168.178.100
        test.site: 123.123.123.123
        jellyfin.cluster.home.test.site: 192.168.178.100
    blocking:
      blackLists:
        ads:
        - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
        - http://sysctl.org/cameleon/hosts
      whiteLists:
        ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
          - |
            cdn.cookielaw.org
      clientGroupsBlock:
        default:
          - ads
    prometheus:
      enable: true
      path: /metrics
    ports:
      http: 4000
```
