### DISCUSSION TITLE
Runtime configuration / statistics - not working with USR1

### DISCUSSION THREAD

**Discussion by gspannu** [0xERR0R/blocky#1423] [Q&A] [answered]
I have 2 installations of Blocky on FreeBSD and Alpine.
Both blocky instances are running as services and everything (DNS, blocking, logging, etc...) all works as expected.

However, I am unable to retrieve any statistics using SIGUSR1 (as explained in the guide [here](https://0xerr0r.github.io/blocky/v0.23/additional_information/))

e.g.
```
# pgrep blocky
26670
# kill -s USR1 26670
# 
```

The command `kill -s USR1 <PID>` does not return anything. Just blank as illustrated above.

**What am I doing wrong?** 
_How do I get the Blocky runtime configuration / statistics?_

**Comment by 0xERR0R** [comment, marked as answer]
Please check the log output from blocky, statistics should be printed there. Kill command does not return anything, it just sends a signal to blocky

**Reply by gspannu** [reply]
Oh... and will the logging have to be set to `info` or will it work for other levels as well?

```
log:
  level: info #(debug, info, warn, error) #Use info while testing
  format: text
  timestamp: true
  privacy: false

```
