### DISCUSSION TITLE
Memory footprint of DNS cache & prefetch - How much RAM for e.g. 10,000 entries?

### DISCUSSION THREAD

**Discussion by gspannu** [0xERR0R/blocky#1425] [Q&A] [answered]
1) As a rough guide, what is the memory footprint of storing DNS records in cache?
2) Is the memory required for prefetch (`prefetchMaxItemsCount`) different to the main cache (`maxItemsCount`)?
Or is it shared or is double the memory required?

So, if my settings were like below (as a rough guide) - what would be my memory usage? **Approx**...

```
caching:
  maxItemsCount: 10000
  prefetching: true
  prefetchMaxItemsCount: 10000
```

```
caching:
  maxItemsCount: 1000
  prefetching: true
  prefetchMaxItemsCount: 1000
```

_Just looking to get some basic maths for estimating my deployment._
