### DISCUSSION TITLE
Help Needed: Basic guide to use Redis to synchronise 2 instances of Blocky

### DISCUSSION THREAD

**Discussion by gspannu** [0xERR0R/blocky#1457] [Q&A]
Tried searching on GitHub and elsewhere but could not find any guide for Redis and Blocky.

**I am looking for a basic guide (`what to write in the config.yml file`) to have 2 instances of blocky synchronised**

My Setup:

- Blocky Instance 1 running at Ip address: a.b.c.d
- Blocky Instance 2 running at IP address: w.x.y.z. 
- Redis Server running at IP address: k.l.m.n

Could someone please guide me as to what the **basic config.yml redis section needs to be** to ensure that caching between the 2 instances is synced?

```
redis:
  address: k.l.m.n
  password: <my_password>
  database: 0
  required: false
  connectionAttempts: 10
  connectionCooldown: 3s

```

Will the redis section in both blocky instances be 100% identical? Or does each confg.yml for the Blocky instance have to be somehow specific?

_Sorry... a newbie on the Redis stuff_
