### DISCUSSION TITLE
Reorganize client group config

### DISCUSSION THREAD

**Discussion by kwitsch** [0xERR0R/blocky#1504] [Ideas]
The issue #1462 and discussion #1466 made me think if we should reorganize the config to define only basic rules in the main section and bundle them under client groups.

I had something like this in my mind:
```
upstream:
  first:
    - ...
  second:
    - ...

blocking:
  ads:
    - ...

conditional:
  local:
    mapping:
      fritz.box: 192.168.178.1

client_groups:
  laptop:
    upstream:
      - second
    blocking:
      - ads
    conditional:
      - local
```
