### DISCUSSION TITLE
mysql fail, blocky fail

### DISCUSSION THREAD

**Discussion by ezekieldas** [0xERR0R/blocky#1534] [Ideas]
Bringing this up as a discussion topic before putting in as feature/bug...

I can do a specific reproducer of this if need be. 

On numerous occassions I've found when the service defined in mysql definition (queryLog) is unavailable, blocky will not fully start, thus failing as resolver service. 

Would it be possible to specify a timeout and allow it to continue without queryLog. I see `queryLog.creationAttempts` with default of 3, yet this doesn't seem to allow for the resolver to start if it fails. 

```
queryLog:
  type: mysql
  target: blocky:blocky@tcp(192.168.1.25:3306)/blocky?charset=utf8mb4&parseTime=True&loc=Local
  logRetentionDays: 7
```
