### DISCUSSION TITLE
Failing to setup split DNS

### DISCUSSION THREAD

**Discussion by YoMamasNerd** [0xERR0R/blocky#1544] [Q&A]
Hi guys,

I've setup blocky to block ads and that works fine.
I'm using blocky on a server in my home and besides blocky there are multiple other machines running on it. I want blocky to resolve a domain (`abc.xyz`) to a local IP and I can't figure out what I'm doing wrong.
My Routers IP is `192.168.178.1`
The IP of my Blocky Server is `192.168.178.100`
And the IP of my reverse proxy is `192.168.178.223`

```
customDNS:
  mapping:
    abc.xyz: 192.168.178.223

conditional:
  mapping:
    fritz.box: 192.168.178.1
    abc.xyz: 192.168.178.100
```

I've set the blocky instance as DNS in my router. Do you have any ideas or suggestions on how to resolve the domain locally?
