### DISCUSSION TITLE
Control YouTube content available to users

### DISCUSSION THREAD

**Discussion by rvrosm** [0xERR0R/blocky#1596] [Ideas]
I'm looking to configure CNAME records for YouTube domains to `restrict.youtube.com` specifically for devices used by kids. Is this something that can be accomplished with Blocky?

[Control YouTube content available to users](https://support.google.com/a/answer/6214622?hl=en#zippy=%2Coption-dns%2Coption-http-headers)

**Comment by ThinkChaos** [comment]
Hi,

I think the easiest will be to use the [customDNS](https://0xerr0r.github.io/blocky/latest/configuration/#custom-dns) mapping with the values recommended for `/etc/hosts` [here](https://cleanbrowsing.org/help/docs/enforce-youtube-child-restrict-mode/):
```yaml
customDNS:
  mapping:
    www.youtube.com: 216.239.38.119
    m.youtube.com: 216.239.38.119
    youtubei.googleapis.com: 216.239.38.119
    youtube.googleapis.com: 216.239.38.119
    www.youtube-nocookie.com: 216.239.38.119
```

This does the trick but I still had a pretty revealing ass pic on the YT homepage when I tried... it's probably better than nothing though.

For a CNAME specifically it's possible using the customDNS `zone` option.

**Comment by rvrosm** [comment]
Maybe it can be implemented by adding a new block type: CNAME ?

**Reply by ThinkChaos** [reply]
It's supported in the `zone` already.

But I don't see any point to using a CNAME here compared to the mapping as it's just more complexity. They key point is the upstream IPs are advertised as stable so hardcoding them is perfectly fine.

**Reply by rvrosm** [reply]
Yes, I think if `Custom DNS` can be applied to a specific client, then maybe we can put it in `rewrite` to make it work.

However, currently, `Custom DNS` and `Conditional DNS` affect all users and cannot be applied to specific clients or IPs.

Can this be implemented?

**Reply by ThinkChaos** [reply]
I see, I think the best option now is to run 2 instances, one with the `customDNS`, and then use [upstream groups](https://0xerr0r.github.io/blocky/latest/configuration/#upstream-groups) to point the devices to restrict to that 2nd instance.

Longer term it would be nice to make the configuration capable of assembling the different resolvers (here `customDNS` and the grouping) as you wish.  
So, for instance, you could define a `customDNS` under a group. That's a bunch of work though and nobody's taken it up for now even if we've discussed it in the past (#476).

**Reply by rvrosm** [reply]
this config is not working:

```
customDNS:
  rewrite:
    www.youtube.com: restrict.youtube.com
    m.youtube.com: restrict.youtube.com
    youtubei.googleapis.com: restrict.youtube.com
    youtube.googleapis.com: restrict.youtube.com
    www.youtube-nocookie.com: restrict.youtube.com
```

I tested it with `dig @127.0.0.1 www.youtube.com`.
