### DISCUSSION TITLE
A simple Blocky Dashboard with just Pandas

### DISCUSSION THREAD

**Discussion by ChitranshuV** [0xERR0R/blocky#1619] [Show and tell]
I've been running Blocky for the past two days and wanted to take a look at my query logs. After seeing the interactive dashboards shipped by Adguard Home and PiHole, I couldn't help but feel a bit envious. The documentation mentions an optional feature to connect Grafana and Prometheus for dashboarding, but I found it a bit daunting to set that up. So I ended up just creating a makeshift dashboard using Python and Pandas. I wanted to make lots of line and doughnut charts to get it working, but decided to make it as simple as possible with raw numbers being reported in tabular format. Right now, I'm running it on my local machine, so I'm the only one connecting to the DNS proxy. I haven't really used ClientID for analysis so far, and all the numbers are just the aggregate of all the clientIDs.

To get started, just add the following query logging configuration to the config.yml file.

```
queryLog:
  type: csv
  target: /home/chitranshu/Downloads/blocky_v0.24_Linux_x86_64/logs
  flushInterval: 30s
  fields:
  - clientIP
  - duration
  - responseReason
  - question

```

Grab the Python File from my public gist - [BlockyDashboard.py](https://gist.github.com/ChitranshuV/dcb062ebf8bf7dbedd9108930af9fd02)

I also set up an alias in my .bashrc so I can quickly run the script and launch the exported static HTML dashboard from the command line.

```
alias blocky_dashboard=[PYTHON_ENVIRONMENT_PATH] [PATH]/BlockyDashboard.py && chromium [EXPORTED_HTML_PATH]/Blocky_Dashboard.html
```
As they say, "it ain't much, but it's honest work."
