### DISCUSSION TITLE
Trouble with CNAME records in v0.24

### DISCUSSION THREAD

**Discussion by asianpianoman** [0xERR0R/blocky#1642] [Q&A] [answered]
I'm trying to utilize the new CNAME support introduced here: https://github.com/0xERR0R/blocky/pull/1352/files

Configuration:
```
customDNS:
    mapping:
      plex.asianpianoman.com: 10.69.169.169
      nginx-proxy01.asianpianoman.com: 10.69.169.35
      anubis-portainer.asianpianoman.com: CNAME(nginx-proxy01.asianpianoman.com)
```

I've verified with kubectl describe pod that I'm using v0.24 which should support this:
```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  63s                default-scheduler  Successfully assigned blocky/blocky-6585588f5c-hqtnm to k8s-worker03
  Normal   Pulling    63s                kubelet            Pulling image "ghcr.io/0xerr0r/blocky:v0.24"
  Normal   Pulled     62s                kubelet            Successfully pulled image "ghcr.io/0xerr0r/blocky:v0.24" in 1.489s (1.489s including waiting). Image size: 8403737 bytes.
  Normal   Created    9s (x4 over 62s)   kubelet            Created container blocky
  Normal   Started    9s (x4 over 62s)   kubelet            Started container blocky
  Normal   Pulled     9s (x3 over 61s)   kubelet            Container image "ghcr.io/0xerr0r/blocky:v0.24" already present on machine
  Warning  BackOff    4s (x11 over 60s)  kubelet            Back-off restarting failed container blocky in pod blocky-6585588f5c-hqtnm_blocky(b9411dc9-b64f-4eed-893e-15b3b960b167)
```

But I'm still getting the same error message I was when I was using v18:
```
kubectl logs -n blocky -f blocky-6585588f5c-hqtnm
[2024-11-12 12:41:05] FATAL unable to load configuration: wrong file structure: invalid IP address 'CNAME(nginx-proxy01.asianpianoman.com)'
```

Anyone see what I'm doing wrong?

Happy to convert to an issue if that's appropriate, figured I'd ask here first.
