### DISCUSSION TITLE
Allow one Client for allowlist

### DISCUSSION THREAD

**Discussion by huseyinkogo** [0xERR0R/blocky#1675] [Q&A]
How can i one client ( HK_PC ) to allow "urlscan.io" domain

Snippet of config.yml
```
blocking:
  denylists:
    general:
      - /opt/blocky/lists/pro.txt
      - /opt/blocky/lists/fake.txt
      - /opt/blocky/lists/popupads.txt
      - /opt/blocky/lists/tif.txt
      - /opt/blocky/lists/doh-vpn-proxy-bypass.txt
      - /opt/blocky/lists/hoster.txt
  allowlists:
    general:
      - /opt/blocky/lists/allowlist.txt
  clientGroupsBlock:
    default:
      - general
  blockType: zeroIp
  blockTTL: 2h
  loading:
    refreshPeriod: 11h
    downloads:
      timeout: 80s
      attempts: 5
      cooldown: 15s
    concurrency: 16
    maxErrorsPerSource: 5


clientLookup:
  upstream: 10.10.32.1
  singleNameOrder:
    - 1
  clients:
    HK_PC:
      - 10.10.32.5
```
