### DISCUSSION TITLE
Can Blocky handle SRV records via customdns?

### DISCUSSION THREAD

**Discussion by Harnish** [0xERR0R/blocky#1735] [Q&A]
I have a need for some SRV records locally and I have been playing around with getting them into Blocky but I am not having any luck.  Anybody have any thoughts?

ChatGPT gave me this to try but it blows up my config:
```
customDNS:
  customTTL: 1h  # (Optional) Set TTL for custom records
  mapping:
    "_submission._tcp.example.com":
      - type: "SRV"
        value: "10 5 587 mox.example.com"
    "_imap._tcp.example.com":
      - type: "SRV"
        value: "10 5 143 mox.example.com"
    "_imaps._tcp.example.com":
      - type: "SRV"
        value: "10 5 993 mox.example.com"
```
