### DISCUSSION TITLE
Setting up DoT

### DISCUSSION THREAD

**Discussion by DistractedCanuck** [0xERR0R/blocky#179] [Q&A] [answered]
So I'm trying to set up DoT to secure my DNS traffic.  I've tried adding `tcp-tls:protected.canadianshield.cira.ca:853` as my only upstream resolver.  But when I do that I no longer get any results.  
Looking at the similar config for unbound it looks like I need to call a cert library as well as have and Ip in addition to the tcp-tls domain.  

Currently my config file has the following: 
```
upstream:
  externalResolvers:
    - tcp-tls:protected.canadianshield.cira.ca:853
```
   
I am running blocky in a docker container based on repo with metric.  My setup works when I just add a normal IP in to the upstream resolver.   

The DNS I am trying to add is the following [CIRA Shield](https://www.cira.ca/cybersecurity-services/canadian-shield/configure) but it would also apply to Quad9 as the give their DoT in the same format.   

My docker container is currently only open to port 53 and 4000. 
Do I need to also forward port 853 to the container? 

Thanks for the help!

**Comment by 0xERR0R** [comment, marked as answer]
Hi, there a 2 different things: configuration of upstream DNS servers and configuration of blocky.

To use an external DNS resolver with TLS, just configure `tcp-tls:protected.canadianshield.cira.ca:853`, your example is correct. Blocky will contact this external DNS server with TLS.

Another thing is configuraiton of blocky: blocky can serve DNS over port 53 (DNS UDP and TCP) without encryption or DNS-over-HTTPS (aka DoH) with encryption. Blocky doesn't provide DoT as endpoint. If you want to use DoH, you can follow the guide (https://github.com/0xERR0R/blocky/wiki/Configuration-of-HTTPS-for-DoH-and-Rest-API) or simple put blocky behind a reverse proxy with encryption (e.g. traefik).

Please consider, if you use blocky only in your home network, without access from outside, I would recommend to use UDP via port 53, this is much faster and you don't need traffic encryption at home (use encrypted external DNS via DoT/DoH). If blocky is reachable from the internet, I would recommend to use DoH.

**Reply by DistractedCanuck** [reply]
Hi, Thanks again for the detailed response.  

So by setting it up as mentioned I should be getting encrypted DNS requests between Blocky and the external DNS Server? I'll try again. I wasn't getting any DNS results with the above line.   

As for the configuration of Blocky? are you just talking about the api for the metrics? If so I'm happy to just route those over HTTP since they will only be served locally.  

To use Blocky with only UDP would I just close the TCP port? As for outside access you mean to the config and api not that it doesn't have a external DNS server right?

**Reply by DistractedCanuck** [reply]
So I got the DoT working this time.  Yay to reloading! Also turns out that if you ping a site it doesn't get encrypted but if you request it in a browser it does.  Interesting.  

Speaking about reloading.  My blocky instance takes about 3 minutes to boot up and go to a running status rather than starting.  Is that normal?

**Reply by 0xERR0R** [reply]
Blocky provides REST API and Prometheus metrics, if you activate the HTTP listener (default port 4000).

To use blocky via port 53, you should forward TCP and UDP port 53 to your docker container. TCP is used as fallback for UDP if a DNS query is too big (due to size limitation of UDP packets).

Loading time of 3 minutes is not normal. Blocky loads blacklist in the memory cache, maybe some list download is too slow. Can you provide the log file? I run blocky in a docker container on a raspberry pi 3 and it takes 3 sec to restart the docker container (I have > 400K blacklist entries)

**Reply by DistractedCanuck** [reply]
Ok perfect that's the way I've got it set up.  

It would see that you are correct.  It had something to do with loading the blacklist.  I cleaned up all the lists and only added ones from [anudeepND/blacklist](https://github.com/anudeepND/blacklist) & [blocklistproject/Lists](https://github.com/blocklistproject/Lists)

boots up right away now!

**Reply by DistractedCanuck** [reply]
So one problem fixed another one starts.  Now the DoT isnt working any more.  I'm not sure why.  I thought maybe it was just the one server that was done but I can't get any of them to work.  

**Error Log** 
[2021-04-15 08:26:13] ERROR server: error on processing request: resolution was not successful, errors: [dial tcp: i/o timeout dial tcp: i/o timeout]
[2021-04-15 08:26:15] ERROR server: error on processing request: resolution was not successful, errors: [dial tcp: lookup private.canadianshield.cira.ca on 127.0.0.11:53: read udp 127.0.0.1:39493->127.0.0.11:53: i/o timeout dial tcp: lookup protected.canadianshield.cira.ca on 127.0.0.11:53: read udp 127.0.0.1:47006->127.0.0.11:53: i/o timeout]
[2021-04-15 08:26:15] ERROR server: error on processing request: resolution was not successful, errors: [dial tcp: lookup private.canadianshield.cira.ca on 127.0.0.11:53: read udp 127.0.0.1:39493->127.0.0.11:53: i/o timeout dial tcp: lookup dns.adguard.com on 127.0.0.11:53: read udp 127.0.0.1:55757->127.0.0.11:53: i/o timeout]
[2021-04-15 08:26:15] ERROR server: error on processing request: resolution was not successful, errors: [dial tcp: lookup private.canadianshield.cira.ca on 127.0.0.11:53: read udp 127.0.0.1:39493->127.0.0.11:53: i/o timeout dial tcp: lookup dns.quad9.net on 127.0.0.11:53: read udp 127.0.0.1:51840->127.0.0.11:53: i/o timeout]
[2021-04-15 08:26:15] ERROR server: error on processing request: resolution was not successful, errors: [dial tcp: lookup private.canadianshield.cira.ca on 127.0.0.11:53: read udp 127.0.0.1:39493->127.0.0.11:53: i/o timeout dial tcp: lookup dns.adguard.com on 127.0.0.11:53: read udp 127.0.0.1:55757->127.0.0.11:53: i/o timeout]
[2021-04-15 08:26:15] ERROR server: error on processing request: resolution was not successful, errors: [dial tcp: lookup dns.adguard.com on 127.0.0.11:53: read udp 127.0.0.1:55757->127.0.0.11:53: i/o timeout dial tcp: lookup dns.quad9.net on 127.0.0.11:53: read udp 127.0.0.1:51840->127.0.0.11:53: i/o timeout]
[2021-04-15 08:26:15] ERROR server: error on processing request: resolution was not successful, errors: [dial tcp: lookup dns.quad9.net on 127.0.0.11:53: read udp 127.0.0.1:51840->127.0.0.11:53: i/o timeout dial tcp: lookup dns.adguard.com on 127.0.0.11:53: read udp 127.0.0.1:55757->127.0.0.11:53: i/o timeout]
[2021-04-15 08:26:16] ERROR server: error on processing request: resolution was not successful, errors: [dial tcp: lookup dns.quad9.net on 127.0.0.11:53: read udp 127.0.0.1:51840->127.0.0.11:53: i/o timeout dial tcp: i/o timeout]
[2021-04-15 08:26:16] ERROR server: error on processing request: resolution was not successful, errors: [dial tcp: lookup private.canadianshield.cira.ca on 127.0.0.11:53: read udp 127.0.0.1:39493->127.0.0.11:53: i/o timeout dial tcp: i/o timeout]
[2021-04-15 08:26:16] ERROR server: error on processing request: resolution was not successful, errors: [dial tcp: lookup dns.adguard.com on 127.0.0.11:53: read udp 127.0.0.1:55757->127.0.0.11:53: i/o timeout dial tcp: i/o timeout]
[2021-04-15 08:26:17] ERROR server: error on processing request: resolution was not successful, errors: [dial tcp: i/o timeout dial tcp: i/o timeout]
[2021-04-15 08:26:18] ERROR server: error on processing request: resolution was not successful, errors: [dial tcp: i/o timeout 

**DNS Config** 
```
upstream:
  externalResolvers:
    - tcp-tls:protected.canadianshield.cira.ca:853
    - tcp-tls:private.canadianshield.cira.ca:853
    - tcp-tls:dns.quad9.net:853
    - tcp-tls:dns.adguard.com:853
    - tcp-tls:cloudflare-dns.com:853
blocking:
  blackLists:
    ads:
      - https://hosts.anudeep.me/mirror/adservers.txt
      - https://hosts.anudeep.me/mirror/facebook.txt
      - https://hosts.anudeep.me/mirror/CoinMiner.txt
      - https://blocklistproject.github.io/Lists/abuse.txt
      - https://blocklistproject.github.io/Lists/ads.txt
      - https://blocklistproject.github.io/Lists/crypto.txt
      - https://blocklistproject.github.io/Lists/malware.txt
      - https://blocklistproject.github.io/Lists/phishing.txt
      - https://blocklistproject.github.io/Lists/ransomware.txt
      - https://blocklistproject.github.io/Lists/redirect.txt
      - https://blocklistproject.github.io/Lists/scam.txt
      - https://blocklistproject.github.io/Lists/tracking.txt
  whiteLists: 
    ads:
      - /whitelists/whitelist.txt
  clientGroupsBlock:
    default:
      - ads
  blockType: zeroIp
prometheus:
  enable: true
port: 53
httpPort: 4000
queryLog:
    dir: /logs
    perClient: true
    logRetentionDays: 7
```
It sounds like it might be a docker issue? port 53 tcp and udp are forwarded.  I looks like blocky is trying to look the sites up on itself? Do I need to add the IPs for each as well like with unbound?

**Reply by 0xERR0R** [reply]
Looks like DNS problem in Docker: docker tries to resolve the IP address of "private.canadianshield.cira.ca". Please try to add:

```
  dns:
   - 8.8.8.8
 ```

to your docker-compose.yml (or `docker run --dns 8.8.8.8 ...`) and recreate the container again. I assume, your DNS configuration on you host machine is not correct.

What is the output of `dig private.canadianshield.cira.ca`?

Alternatively, you can try to set the `bootstrapDns` parameter in config.yml (see https://0xerr0r.github.io/blocky/configuration/) and set it to "8.8.8.8" or something like this.

**Reply by DistractedCanuck** [reply]
Ok, So just adding the bootstrapDns did allow me to load the blacklists but it did not resolve the issue.  
Adding a DNS to the docker container does seem to work.  It no longer creates issues and does seem to be using the correct DNS resolvers when I use DNSLeak. However, now the DoT is no longer working.  

  
running `dig private.canadianshield.cira.ca` or `dig www.google.ca` provide the same error. 

;; reply from unexpected source: 127.0.0.1#53, expected 127.0.0.53#53

;; reply from unexpected source: 127.0.0.1#53, expected 127.0.0.53#53

;; reply from unexpected source: 127.0.0.1#53, expected 127.0.0.53#53

; <<>> DiG 9.16.1-Ubuntu <<>> private.canadianshield.cira.ca
;; global options: +cmd
;; connection timed out; no servers could be reached

I think you're right it must be an issue with the DNS on my host machine.  

To set up blocky I am changing the DNS resolver on my router to blocky.

**Reply by DistractedCanuck** [reply]
Sounds like its a systemresolve issue.  I've disabled it and will try to reload later.  (People are using the home internet now).  This seems to have fixed the issue for people over on the pi-hole forums.

**Reply by DistractedCanuck** [reply]
Alright so, after playing with this for a while I have it working...ish.  

I had to stop the systemresolve service. Than add my own nameserver into resolv.conf. Once that was done blocky was able to load and resolve queries.  

```
2021-04-17 14:48:07	192.168.0.1	dlinkrouter	188	RESOLVED (private.canadianshield.cira.ca:853)	A (api.github.com.)	A (140.82.112.6)	NOERROR
2021-04-17 14:48:07	192.168.0.1	dlinkrouter	197	RESOLVED (private.canadianshield.cira.ca:853)	A (api.github.com.)	A (140.82.113.6)	NOERROR
```

So that works! If I can also change that to Quad9 and it will work and call the correct dns so it doesn't seem to be leaking.  

That being said I can't seem to get the encryption to work.  I don't know if thats from a lack of understanding what it actually is or if its not working.  

When I use Wireshark to monitor my traffic I can still see all the requested IPs unencrypted and when I test it using the [Browser Privacy Test](https://tenta.com/test/?utm_source=blog) it tells me TLS is not enabled.  

My conf file looks like this: 

```
upstream:
  externalResolvers:
   - tcp-tls:protected.canadianshield.cira.ca:853
   - tcp-tls:private.canadianshield.cira.ca:853
  #  - tcp-tls:dns.quad9.net:853
 #   - tcp-tls:dns.adguard.com:853
 #   - tcp-tls:cloudflare-dns.com:853

clientLookup:
    upstream: udp:192.168.0.1
    singleNameOrder:
      - 2
      - 1

blocking:
  blackLists:
    ads:
      - https://hosts.anudeep.me/mirror/adservers.txt
      - https://hosts.anudeep.me/mirror/facebook.txt
      - https://hosts.anudeep.me/mirror/CoinMiner.txt
      - https://blocklistproject.github.io/Lists/abuse.txt
      - https://blocklistproject.github.io/Lists/ads.txt
      - https://blocklistproject.github.io/Lists/crypto.txt
      - https://blocklistproject.github.io/Lists/malware.txt
      - https://blocklistproject.github.io/Lists/phishing.txt
      - https://blocklistproject.github.io/Lists/ransomware.txt
      - https://blocklistproject.github.io/Lists/redirect.txt
      - https://blocklistproject.github.io/Lists/scam.txt
      - https://blocklistproject.github.io/Lists/tracking.txt
  whiteLists: 
    ads:
      - /whitelists/whitelist.txt
  clientGroupsBlock:
    default:
      - ads
  blockType: zeroIp
prometheus:
  enable: true
port: 53
httpPort: 4000
bootstrapDns: 1.1.1.1
queryLog:
    dir: /logs
    perClient: true
    logRetentionDays: 7
```
and the docker compose like this: 

```
version: '3'

services:
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    networks:
       - blocky
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"
      - "853:853/udp"
      - "4000:4000"
    environment:
      - TZ=America/Halifax
    volumes:
      - ./blocky/config.yml:/app/config.yml
      - ./blocky/logs/:/logs/
      - ./whitelists/:/whitelists/
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks: 
      - blocky
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: unless-stopped

  grafana:
    image: grafana/grafana:6.7.1
    container_name: grafana
    networks: 
      - blocky
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    restart: unless-stopped    

volumes:
    prometheus_data: {}
    grafana_data: {}

    
networks:
  blocky:
    driver: bridge
    ipam:
      config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
         aux_addresses:
          blocky: 10.5.0.5
```
I tried opening port 853 to the container but that didn't seem to make a difference and closing port 53 broke it.   

using `dig private.canadianshield.cira.ca:853` now actually returns the expected response of: 

```
; <<>> DiG 9.16.1-Ubuntu <<>> private.canadianshield.cira.ca:853
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 37227
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;private.canadianshield.cira.ca:853. IN A

;; AUTHORITY SECTION:
.                       10800   IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2021041701 1800 900 604800 86400

;; Query time: 40 msec
;; SERVER: 149.112.121.20#53(149.112.121.20)
;; WHEN: Sat Apr 17 14:56:45 ADT 2021
;; MSG SIZE  rcvd: 138
```

Thank you for your help and hopefully I have annoyed you to much!
