### DISCUSSION TITLE
I wish I don't need these sidecars, because Blocky supports redundancy and hot reload 🛡️

### DISCUSSION THREAD

**Discussion by zdeneksvarc** [0xERR0R/blocky#1798] [Show and tell]
- blocky01 (primary)

```
# TZ=Europe/Prague
# INTERVAL=5

services:
  blocky:
    image: spx01/blocky:v0.26.2
    container_name: blocky
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/app/config.yml

  config-checker-local:
    image: docker:23.0.1-cli
    container_name: blocky-config-checker
    restart: always
    env_file:
      - .env
    volumes:
      - ./config.yml:/app/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >
      sh -c '
        echo "$(date): config-checker started, polling mounted config.yml every ${INTERVAL}s"
        apk add --no-cache diffutils >/dev/null
        cp /app/config.yml /tmp/config.prev.yml
        while true; do
          if ! cmp -s /tmp/config.prev.yml /app/config.yml; then
            echo "$(date): config.yml has changed — restarting blocky"
            cp /app/config.yml /tmp/config.prev.yml
            docker restart blocky
          fi
          sleep "${INTERVAL}"
        done
      '

  config-server:
    image: python:3-alpine
    container_name: blocky-config-server
    restart: always
    ports:
      - 48800:80
    working_dir: /srv
    volumes:
      - ./config.yml:/srv/config.yml:ro
    command: >
      sh -c "
        echo '[config-server] Serving /srv on port 80...' &&
        python3 -m http.server 80
      "
```

- blocky02 (secondary) or more

```
# TZ=Europe/Prague
# CONFIG_URL=http://primary.lan:48800/config.yml
# INTERVAL=5

services:
  blocky:
    image: spx01/blocky:v0.26.2
    container_name: blocky
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/app/config.yml

  config-checker-remote:
    image: docker:23.0.1-cli
    container_name: blocky-config-checker
    restart: always
    env_file:
      - .env
    volumes:
      - ./config.yml:/app/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >
      sh -c '
        # Announce startup
        echo "$(date): config-checker started, polling $CONFIG_URL every ${INTERVAL}s"
        # Install required tools
        apk add --no-cache curl diffutils >/dev/null &&
        # Start infinite loop
        while true; do
          # Download the latest config
          curl -sfL "$CONFIG_URL" -o /tmp/config.new.yml &&
          # Compare against the current config
          if ! cmp -s /tmp/config.new.yml /app/config.yml; then
            echo "$(date): config.yml has changed"
            # Overwrite content of the local file and restart Blocky
            cat /tmp/config.new.yml > /app/config.yml &&
            docker restart blocky
          fi
          # Sleep for INTERVAL seconds
          sleep "${INTERVAL}"
        done
      '
```
