### DISCUSSION TITLE
EDNS support help

### DISCUSSION THREAD

**Discussion by agneevX** [0xERR0R/blocky#269] [General]
I'm trying to use Google DNS remotely hosted in a VPS with EDNS as I've discovered it returns CDN IPs that my ISP publicly hosts, something Cloudflare or other public resolvers do not return.

I've set up blocky there with a basic config:

```yml
logLevel: warn
upstream:
  default:
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
caching:
  minTime: 5
  maxTime: 30
  prefetching: true
  prefetchExpires: 360
  prefetchThreshold: 2
```

<details><summary>compose.yml</summary>

```yml
version: '3.8'
services:
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    ports:
      - 2800:53/udp
      - 32070:53/tcp
    environment:
      - TZ=
    volumes:
      - type: bind
        source: /opt/appdata/blocky/blocky.yml
        target: /app/config.yml
```

</details>

It still seems to use the VPS' subnet:

```sh
❯ dig TXT o-o.myaddr.l.google.com +short @152.67.x.x -p 32070 +tcp +subnet="116.x.x.0/24"
"2404:6800:4000:1003::102"
"edns0-client-subnet 152.67.x.0/24"
# Should return my ISP's subnet
```
