### DISCUSSION TITLE
"Merging" Whitelists into default group

### DISCUSSION THREAD

**Discussion by Nold360** [0xERR0R/blocky#276] [Q&A] [answered]
Hi,

in my current configuration i have defaults "ads"-blacklist. Now i wanted to whitelist domains only for specific clients using a whitelist. 

Since the whitelist needs to have a different name then the blacklist, this doesn't seem to work like this:
``` yaml
 blackLists:
      ads:
         - my 
         - long 
         - list 
         - ....
 whiteLists:
       ads:
          - common-whitelist.txt
       ms:
          - special-whitelist.txt

 clientGroupsBlock:
      default:
        - ads
      LAPTOP-G35N0AS1.lan:
        - ads
        - ms
```
What's the best way to do this? I don't really want to figure out which blackList contains the domains I want to whitelist, then seperate them into another blackList-Group just so I can whiteList them later on. Cause that's the only thing I can currently think of...

Or I could duplicate the `ads`-List and name it `ms` but that's not really elegant either...

Full config [currently I added ms-whitelist to default group to make it work]: https://github.com/Nold360/heqet/blob/hive/values.d/blocky.yaml#L56

Thanks a lot for this great tool anyways!

**Comment by 0xERR0R** [comment, marked as answer]
Hi,

it should work. I tried with following config:

```yaml
# blocky.yml
httpPort: 4000
logLevel: trace

upstream:
  default:
    - 8.8.8.8
    - 1.1.1.1
blocking:
  whiteLists:
    ms:
      - |
        doubleclick.net
  blackLists:
    ads:
      - |
        doubleclick.net
        doubleclick.com
  clientGroupsBlock:
    default:
      - ads
    192.168.178.29:
      - ads
      - ms
port: 55555
```

192.168.178.29 is my IP address.

```bash
# doublecklick.com blocked
dig @192.168.178.29 -p 55555 +short  doubleclick.com                                                                                                                                                   
0.0.0.0
# doublecklick.net resolved, because whitelisted for 192.168.178.29
dig @192.168.178.29 -p 55555 +short  doubleclick.net                                                                                                                                                   
216.58.212.142
```

Log output: ` DEBUG blacklist_resolver: domain is whitelisted client_ip=192.168.178.29 client_names=192.168.178.29 domain=doubleclick.net group=ms question=A (doubleclick.net.)`

If I use `127.0.0.1` as resolver, my client will be mapped to 127.0.0.1

```bash
#  doubleclick.com  blocked
dig @127.0.0.1 -p 55555 +short  doubleclick.com                                                                                                                                                        
0.0.0.0

# doubleclick.net   blocked
dig @127.0.0.1 -p 55555 +short  doubleclick.net                                                                                                                                                        
0.0.0.0
```

Please set log level to `debug` maybe the resolution of client's name does not work or is not configured properly
