### DISCUSSION TITLE
Only DoH upstream question

### DISCUSSION THREAD

**Discussion by catleeball** [0xERR0R/blocky#331] [Q&A] [answered]
I was just getting started with blocky and had a quick question that I wasn't seeing in the docs:

If I only specify DoH upstream DNS clients in `config.yml`, will blocky be able to serve non-DoH requests it gets from its clients?

I hoped to send all DNS requests from my LAN to blocky with the idea that blocky will only use DoH regardless of what its clients support, effectively making all DNS queries from the LAN DoH.

e.g. say I'm running blocky with:

```yml
# === config.yml ===
upstream:
    default:
        - https://dns11.quad9.net/dns-query
        - https://dns.quad9.net/dns-query
        - https://dns.example.com/dns-query

# the rest of the config ...
```

will DNS requests from my network behave like this?

```
cat.lan >---[ udp to  blocky.lan:53 ]---> blocky.lan >---[ DoH to dns.example.com/dns-query ]---> example.com
```

so that if `cat.lan` doesn't know how to use DoH, it can send a DNS request of whatever type to `blocky.lan` who will resolve it via DoH.

Thanks!
