### DISCUSSION TITLE
Blocking error

### DISCUSSION THREAD

**Discussion by LexterS999** [0xERR0R/blocky#347] [Q&A] [answered]
I want to block whole domain .io and .cn with regex support on config, but it doesn't work for me. Seems like I did something wrong on config, but it was copied from example config. Can you please provide right config for the blocking section to make it work?

P.S adding .io and .cn into blacklist.txt doesn't help me at all. And I'm using v0.17

**Comment by 0xERR0R** [comment]
I can't test the config right now, but from the top of my head, it should look like this:

```yaml
upstream:
  externalResolvers:
    - 1.1.1.1
    - 9.9.9.9
blocking:
  blackLists:
    ads:
      - |
        /^.*\.io$/
        /^.*\.cn$/
  clientGroupsBlock:
    default:
      - ads
port: 53
httpPort: 4000
logLevel: info
```

The regex must be enclosed by `/`

Btw. You can test regex with this tool: https://regoio.herokuapp.com/

**Comment by LexterS999** [comment]
Is it ok to see that on log

INFO list_cache: file imported count=2 source=/^.*\.io$/
Nov 16 12:30:04  blocky[17497]: /^.*\.cn$/

**Comment by 0xERR0R** [comment]
Yes, it is ok. This output should be replaced with something useful in case of regex

**Comment by LexterS999** [comment]
Cool, thanks. So this regex will block anything with ads/banner, right?

  blackLists:
    ads:
    - /root/Blocky/blacklist.txt
    - https://raw.githubusercontent.com/eded333/TheFuckingList/main/pihole.txt
    - https://raw.githubusercontent.com/mtxadmin/ublock/master/hosts.txt
    - |
        /^.*\.io$/
        /^.*\.cn$/
        /^.*\ads$/
        /^.*\banner$/

**Comment by 0xERR0R** [comment]
if you want to block every domain name which contains ads, it should be `/.*ads.*/`

**Comment by LexterS999** [comment]
And what config must be if I want to add some domain within regex format into whitelist? Same question for the whole domain and subdomain to the blacklist.

**Comment by 0xERR0R** [comment]
This is the same format. Each regex must be enclosed with `/`. You can define regex either inline or in a separate text file

**Reply by LexterS999** [reply]
> This is the same format. Each regex must be enclosed with `/`. You can define regex either inline or in a separate text file

Any example please

**Comment by 0xERR0R** [comment, marked as answer]
```yaml
upstream:
  externalResolvers:
    - 1.1.1.1
    - 9.9.9.9
blocking:
  whiteLists:
    ads:
      - |
        # do not block domains with ".google.com"
        /^.*\.google.com$/
  blackLists:
    ads:
      - |
        /^.*\.io$/
        /^.*\.cn$/
  clientGroupsBlock:
    default:
      - ads
port: 53
httpPort: 4000
logLevel: info
```
