### DISCUSSION TITLE
blocky's clientLookup returning router's IP for all domains (in certain conditions)

### DISCUSSION THREAD

**Discussion by sn0opy** [0xERR0R/blocky#396] [Q&A] [answered]
Hey,

I'am experiencing a weird issue on my local blocky setup. My router (a FritzBox) us propagating my blocky server's IP address via DHCP to all clients and all clients seem to resolve all domains just fine. On a Windows PC I am experiencing something special with blocky being the main DNS. While using `nslookup domain.tld` it actually returns my router's IP and a (reverse?) domain name like "domain.tld.fritz.box". While using 1.1.1.1 or any other DNS, it works just fine.

I'm only experiencing this with Windows' `nslookup`. While using the WSL `nslookup` or `dig` the domain and its reverse dns name for the IP are returned just fine. The domain will also be properly resolved when adding a dot after the domain like `nslookup domain.tld.`. 

Why does it happen and is there a way to fix this "issue"? Is this caused by `clientLookup`? It looks like the problem does not occur when disabling it completely.

My config:

```yaml
upstream:
  default:
    - tcp-tls:1.1.1.1:853 # cloudflare
    - tcp-tls:1.0.0.1:853 # cloudflare
    - tcp-tls:1.1.1.2:853 # cloudflware anti-malware
    - tcp-tls:1.0.0.2:853 # cloudflware anti-malware
    - tcp-tls:8.8.8.8:853 # google
    - tcp-tls:8.8.4.4:853 # google
    - tcp-tls:9.9.9.9:853 # quad9
    - tcp-tls:149.112.112.112:853 # quad9
clientLookup:
  upstream: 192.168.0.1
  singleNameOrder:
    - 1
customDNS:
  mapping:
    locallyuseddomain.tld: 192.168.0.5 # this server also runs blocky, a reverse proxy for local services and other stuff
    fritz.box: 192.168.0.1
blocking:
  blockType: zeroIP
  refreshPeriod: 120m
  blackLists:
    ads:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://ewpratten.retrylife.ca/youtube_ad_blocklist/domains.txt
  clientGroupsBlock:
    default:
      - ads
```
