### DISCUSSION TITLE
HowTo for blocky with docker and IPv6 necessary

### DISCUSSION THREAD

**Discussion by ikarisan** [0xERR0R/blocky#452] [General]
Hi!

I am running docker as a docker container (via docker-compose) and it took me many days to figure out, how to enable IPv6 traffic to and from blocky. At first I didn't notice it, but after configuring IPv6 upstream servers I kept getting error messages that the IPv6 address could not be bound/used. Then I found out that IPv6 and docker are not really best friends. Below is how I got blocky, docker and IPv6 working for me.

1) Enable IPv6 for docker in daemon.json. Assuming that you are using docker 20.10.x, your daemon.json should look like this:

```
{
  "ipv6": true,
  "fixed-cidr-v6": "fdxx:xxx:xxx:xxx::/64",
  "experimental": true,
  "ip6tables": true
}
```
Please chose an indivdual fd::: address.

2) Create a new fd:::/64 network. You can use https://simpledns.plus/private-ipv6 for that. 

3) For blocky add a new network to docker. Let's name it "ipv6net_1".

`docker network create --driver bridge --ipv6 --subnet fd01:4c51:244f:5697::/64 --subnet 172.30.0.0/24 ipv6net_1 --attachable`

Please use your personal IPv6/IPv4 subnet!

4) Create a docker-compose file that consideres this network. The following is an example. Please modify the values for your needs!
```

version: '3.9'
services:
  blocky:
    image: 'spx01/blocky'    
    pull_policy: always
    container_name: blocky
    restart: unless-stopped
    networks:
      ipv6net_1:
        ipv6_address: fd01:4c51:244f:f697::42
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    dns:
      - 10.10.0.1
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - '53:53/tcp'
      - '4000:4000/tcp'
      - '53:53/udp'
    environment:
      - TZ=Europe/Berlin
    volumes: 
      - '/etc/docker_configs/blocky/config.yml:/app/config.yml'
      - 'blocky_logs:/logs'
    healthcheck:
      disable: true            
networks:
  ipv6net_1:
    external: true
    
volumes:
    blocky_logs:
      external: true

```

A "docker-compose up" should give you a blocky container with working outbound IPv6 traffic. :)
