### DISCUSSION TITLE
Regex as imported list

### DISCUSSION THREAD

**Discussion by m0zgen** [0xERR0R/blocky#491] [Q&A]
Hello, I'm using whitelisted regex as list, as example from `config.yml`:
```
...
    tracking:
      - https://raw.githubusercontent.com/m0zgen/dns-hole/master/whitelist.txt
      - |
        /^.*.site1.com/
        /^.*.site2.io/
        /^.*.siteN.etc/
...
```

If it possible - very convenient will be import "regex" domains from list:
```
cat wl-regext.txt
..
/^.*.site1.com/
/^.*.site2.io/
/^.*.siteN.etc/
...
```
And `config.yml`:
```
...
    tracking:
      - https://raw.githubusercontent.com/m0zgen/dns-hole/master/whitelist.txt
      - <link_or_path_to>/wl-regext.txt
...
```

**Comment by 0xERR0R** [comment]
Your example should work. I use regex list in my config with http url:

```yaml
  blackLists:
    ads:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - http://sysctl.org/cameleon/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/CoinMiner.txt
    regex:
      - https://raw.githubusercontent.com/mmotti/adguard-home-filters/master/regex.txt
```
