### DISCUSSION TITLE
Blocky won't restart because DNS lookup fails (catch 22)

### DISCUSSION THREAD

**Discussion by dbainbridge** [0xERR0R/blocky#550] [Q&A] [answered]
When I have to reboot my system it is trying to re-download the GitHub/s3 based IP block lists files I have set in my config but since blocky is my DNS proxy it can't resolve GitHub until blocky is actually running.  I'm having to work around this by temporarily changing my routers DNS setting to a public one and then switch it back to my Raspberry Pi running blocky after blocky fully starts up.  Here is my config:
```
upstream:
  default:
    - 1.1.1.3
    - 1.0.0.3
    - 9.9.9.9
blocking:
  blackLists:
    ads:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-porn/hosts
  clientGroupsBlock:
    default:
      - ads
port: 53
httpPort: 4000
```
