### DISCUSSION TITLE
Metrics with InfluxDB

### DISCUSSION THREAD

**Discussion by axelrindle** [0xERR0R/blocky#586] [Show and tell]
This is meant for everybody who's is using InfluxDB for their metrics.

### Requirements

- InfluxDB v2

### How-to

The `/metrics` endpoint can be scraped by an InfluxDB instance. Let's say this is your configuration:

```yml
httpPort: 5301

metrics:
  enable: true
  path: /metrics

// other settings ...
```

Then just login to the InfluxDB UI and create a new **Scraper**:

![image](https://user-images.githubusercontent.com/7105632/176778126-ff8008b6-8c28-47cb-a174-a85767688a16.png)

The metrics will appear in the selected bucket.

### Further Reading

- https://docs.influxdata.com/influxdb/v2.3/write-data/no-code/scrape-data/
