### DISCUSSION TITLE
Docker IP to container name for clientLookup

### DISCUSSION THREAD

**Discussion by sn0opy** [0xERR0R/blocky#673] [Ideas]
I am running several containers on the same host blocky is running on. DNS lookups for these containers are logged by blocky, but unfortunately they appear with their docker-internal ip.

There are projects like [dvddarias/docker-hoster](https://github.com/dvddarias/docker-hoster) which adds containers with specific parameters to a mounted hostfile. Since blocky already has a hostfile lookup, this would be a valid solution.

I was wondering if there's an oversight on my end to provide proper names in my logs/stats for containers, or if this is even a feature that could be added to blocky. This change would not introduce any new dependencies since blocky could read the information directly from the docker socket via standard libs.

**Comment by kwitsch** [comment]
You could use the internal Docker DNS server to resolve container names if you use docker networks.
Simply forward arpa requests of the internal subnets to 127.0.0.11 and define hostnames during container start or in your compose-file.

Or did I miss the point? 😅

**Reply by sn0opy** [reply]
It's totally what I want, yes. I was looking for a built-in way in Docker, but was probably looking for the wrong thing. Having a way to do this without defining a hostname would be perfect, but this should work as well.

I went ahead and tested it, but it doesn't seem to register the container's hostname properly or at least it keeps returning NXDOMAIN while requesting IP from within another container.  Is there something else that is required to make this work or is it simply not a reliable solution?

**Reply by sn0opy** [reply]
Guess I am able to answer my own question. Looks like you have to assign them to a custom bridge network as well. The default bridge does not seem to resolve names.

https://docs.docker.com/network/bridge/

> User-defined bridges provide automatic DNS resolution between containers.
> Containers on the default bridge network can only access each other by IP addresses, unless you use the [--link option](https://docs.docker.com/network/links/), which is considered legacy. On a user-defined bridge network, containers can resolve each other by name or alias.

**Reply by kwitsch** [reply]
Sorry my Docker knowledge outside of swarm-mode is somewhat limited.
Using overlay networks the name resolution works pretty well(most of my dns stack depends on it 😅)

blocky config snippet:
```YAML
# use recursive service as upstream
bootstrapDns: 127.0.0.11
upstream:
  default:
    - recursive

# use localdaomain service for MAC to hostname mapping
conditional:
  mapping:
    168.192.in-addr.arpa: localdomain
    ddv: localdomain
clientLookup:
  upstream: localdomain
```

compose file snippet:
```YAML
x-network-internal:
  &network-internal
  - int
x-network-both:
  &network-both
  - int
  - ext

services:
  # default dns resolution
  recursive:
    image: kwitsch/unbound:monthly
    networks: *network-both
  # Omada DNS server for local domain
  localdomain:
    image: ghcr.io/kwitsch/omadasitedns:0.5
    networks: *network-both
    secrets:
      - OSD_SITE_PASSWORD
    environment:
      - ... # needed env variables
  # blocky as main dns server
  blocky:
    image: ghcr.io/0xerr0r/blocky
    networks: *network-both # internal won't allow ports expose in host mode
    ports: # dns ports in host mode to get client ips
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
    configs:
      - source: blocky_config
        target: /app/config.yml

# seperate networks for stack and internet communication
networks:
  ext:
  int:
    internal: true
```
