### DISCUSSION TITLE
How does log.privacy: true work?

### DISCUSSION THREAD

**Discussion by rubiojr** [0xERR0R/blocky#981] [Q&A]
I was expecting name being queried not appearing in the logs (stdout) when `logPrivacy: true` but that doesn't seem to be the case, `question_name` in particular contains the name I'm trying to resolve, `foobar.com`:

```
blocky           | [2023-04-05 19:48:41]  INFO queryLog: query resolved answer=***** (****.**.****.****.***.***.***********.***.), ***** (*-****.**.****.****.***.***.***********.***.), ***** (*-****.****.****.****.***.***.***********.***.), ***** (*-****.****.****.****.****.***.***.***********.***.), ***** (**************.**********.***.), * (**.**.***.**), * (**.**.***.**), * (**.**.***.*), * (**.**.***.**) client_ip=MANUALLY_REDACTED client_names=MANUALLY_REDACTED duration_ms=5 hostname=something question_name=foobar.com question_type=A response_code=NOERROR response_reason=RESOLVED (https://1.1.1.1/dns-query) response_type=RESOLVED
```

This is the config I'm using:

```
upstream:
  default:
    - https://1.1.1.1/dns-query
blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - http://sysctl.org/cameleon/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
      - https://adaway.org/hosts.txt
      - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext
  clientGroupsBlock:
    default:
      - ads
port: 53
httpPort: 4000

log:
  privacy: true
```

**Comment by rubiojr** [comment]
May have solved my own question, I've resorted to add the `queryLog` section instead with:

```
queryLog:
  type: console
  fields:
    - clientIP
    - duration
```
