### ISSUE TITLE
DNS Leak

### ISSUE THREAD

**Issue by iofxl** [0xERR0R/blocky#1071]
I set up a blocky server and adjusted my DNS settings to use this server. 

I did a [DNS leak test](https://www.dnsleaktest.com/). 

The test results revealed a DNS leak, indicating that the servers identified were different IP addresses instead of my blocky server's IP.

I checked blocky server's log, found that it received requests for _randomstring_.test.dnsleaktest.com. Additionally, I used `tcpdump` and confirmed that packets were indeed sent to the upstream DNS server. 

But the results of the test indicate that there is still a DNS leak present.

My config.yml:

```yml
# optional: Mininal TLS version that the DoH and DoT server will use
minTlsServeVersion: 1.3
# if https port > 0: path to cert and key file for SSL encryption. if not set, self-signed certificate will be generated
certFile: /etc/lego/certificates/lego.crt
keyFile: /etc/lego/certificates/lego.key
#
upstream:
  default:
    - https://dns11.quad9.net/dns-query
upstreamTimeout: 5s

bootstrapDns:
  - upstream: https://dns11.quad9.net/dns-query
    ips:
    - 9.9.9.11

ports:
  dns: 53
  tls: 853
  https: 443
  http: 4000

blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  clientGroupsBlock:
    default:
      - ads

caching:
  minTime: 5m
  maxTime: 30m
  maxItemsCount: 0
  prefetching: false
  prefetchExpires: 2h
  prefetchThreshold: 5
  prefetchMaxItemsCount: 0
  cacheTimeNegative: 30m

log:
  level: info
  format: text
  timestamp: true
  privacy: false

queryLog:
  type: console
  target: /logs
  logRetentionDays: 7
  fields:
  - clientIP
  - question
  - duration

prometheus:
  enable: true
  path: /metrics

```
