### ISSUE TITLE
Docker image gone unhealthy

### ISSUE THREAD

**Issue by Section1977** [0xERR0R/blocky#1125]
Hi
what is the reason for blocky docker image go unhealthy if you change the following argument:
ports:
dns: 53

to 
ports:
dns: some_ip:53

What can be done to achieve "good" health status again ?

**Comment by kwitsch** [comment]
The container health check tries resolve a request to port 53. If it fails the container goes unhealthy.

The proper configuration would be to let blocky inside the container on port 53 and bind the port to a specific IP on docker level.

Another option would be to disable the health check. This could be necessary if you run the container in host mode. If the custom health check is disabled the docker default should kick in.

**Comment by 0xERR0R** [comment]
What is the reason to bind the DNS listener to a specific IP inside the docker image?

**Comment by Section1977** [comment]
HiI have an own non-public DNS Server with sd blocking features.I want dhcp and static IP within VMs automatic using my DNS serverVon meinem iPhone gesendetAm 12.09.2023 um 10:59 schrieb Dimitri Herzog ***@***.***>:﻿
What is the reason to bind the DNS listener to a specific IP inside the docker image?

**Comment by adjokic** [comment]
I am using [autoheal](https://github.com/willfarrell/docker-autoheal) alongside blocky.
relevant docker-compose.yml snippets:
```
  autoheal:
    image: willfarrell/autoheal
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
        - AUTOHEAL_CONTAINER_LABEL=autoheal
    restart: always
    container_name: autoheal
...
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    healthcheck:
      test: /app/blocky healthcheck
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 1m
    labels:
      autoheal: true
    # Optional the instance hostname for logging purpose
    hostname: blocky-hostname
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - 4000:4000
    environment:
      - TZ=YOUR_TIME_ZONE
    volumes:
      # Optional to synchronize the log timestamp with host
      - /etc/localtime:/etc/localtime:ro
      # config file
      - PATH_TO/blocky/config.yml:/app/config.yml
```
