### ISSUE TITLE
applying blacklist for a group not mapped

### ISSUE THREAD

**Issue by renanqts** [0xERR0R/blocky#1203]
Hello folks. Thanks for the amazing work.

I'm facing a problem very strange which I think is a bug, but I didn't debug in the code level yet.
Currently, I have the follow config:

```
    queryLog:
      type: none
    upstreams:
      groups:
        default:
          - 193.110.81.0
          - 185.253.5.0
          - 46.182.19.48
          - 80.241.218.68
          - tcp-tls:fdns1.dismail.de:853
          - https://dns.digitale-gesellschaft.ch/dns-query
    clientLookup:
      clients:
        not-blocked:
          - 192.168.188.10
    blocking:
      blackLists:
        ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
        do-not-block:
          - |
            # do not block
            foobar.com
      clientGroupsBlock:
        default:
          - ads
        not-blocked:
          - do-not-block
    ports:
      dns: 53
      http: 4000
    prometheus:
      enable: true
      path: /metrics
    redis:
      address: blocky-redis-master:6379
      password: something
      database: 2
      required: true
      connectionAttempts: 10
      connectionCooldown: 3s
```
As you can see, I have to groups: `default` and `not-blocked`.
For `not-blocked` clients, I don't want to have it using the blacklist `ads`, but currently it is being applied.
For example, if I query from the IP `192.168.188.10`, I can see it in the logs:

```
blocky-59f57778f7-657xc blocky [2023-10-15 10:53:26] DEBUG caching_resolver: domain is cached client_ip=192.168.188.10 client_names=not-blocked domain=www.googleadservices.com question=A (www.googleadservices.com.)
```

the result is:
```
; <<>> DiG 9.10.6 <<>> @192.168.188.203 www.googleadservices.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50407
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.googleadservices.com.	IN	A

;; ANSWER SECTION:
www.googleadservices.com. 21600	IN	A	0.0.0.0

;; Query time: 8 msec
;; SERVER: 192.168.188.203#53(192.168.188.203)
;; WHEN: Sun Oct 15 10:55:19 CEST 2023
;; MSG SIZE  rcvd: 58
```
Could some help to understand why I'm getting this result? There is no blacklist at all for this domain in the blacklist `do-not-block` which is mapped to the group `not-blocked`.

As fair as I understood from the docs, once the client has itself mapped inside a group, it will not be mapped mapped to the default, but seems like this is not true for the previous case.
