### ISSUE TITLE
There is a problem with configuring the regular dns upstream, and its ecs cannot be cached

### ISSUE THREAD

**Issue by liang-hiwin** [0xERR0R/blocky#1292]
```
upstreams:
  groups:
    # these external DNS resolvers will be used. Blocky picks 2 random resolvers from the list for each query
    # format for resolver: [net:]host:[port][/path]. net could be empty (default, shortcut for tcp+udp), tcp+udp, tcp, udp, tcp-tls or https (DoH). If port is empty, default port will be used (53 for udp and tcp, 853 for tcp-tls, 443 for https (Doh))
    # this configuration is mandatory, please define at least one external DNS resolver
    default:
      # example for tcp+udp IPv4 server (https://digitalcourage.de/)
      - udp:119.28.28.28

```
Configuration udp:119.28.28.28 prompts error
```
[2023-12-04 08:56:49] FATAL unable to load configuration: wrong file structure: can't convert upstream 'udp:119.28.28.28': can't convert port to number (1 - 65535) strconv.ParseUint: parsing "119.28.28.28": invalid syntax

ecs cannot be cached, and in severe cases, the parsing times out.

```
![image](https://github.com/0xERR0R/blocky/assets/17548936/2da72a27-490e-44d6-97e8-e82df00229fb)

![image](https://github.com/0xERR0R/blocky/assets/17548936/6eb9e277-234d-49f6-8d52-4a347f8df25d)
