### ISSUE TITLE
Whitelist-only group cannot be disabled through REST API

### ISSUE THREAD

**Issue by bpn19** [0xERR0R/blocky#1317]
Easiest to explain with a config excerpt:

```yaml
blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  whiteLists:
    alpha:
      - |
        www.wordreference.com
#    ...
  clientGroupsBlock:
    default:
      - alpha
#     ...
```

For my setup, I do not use *any* blacklists. The `ads` group is only there for the sake of this example. The goal is to disable the `alpha` group, i.e. un-whitelist its entries. However, this doesn't work:

```sh
$ blocky blocking disable --groups alpha
Error: response NOK, Status: 400 Bad Request
```

```
[2023-12-21 17:56:51] ERROR can't disable the blocking: group 'alpha' is unknown
```

But we can see that disabling `ads` works:

```sh
$ blocky blocking disable --groups ads
[2023-12-21 18:04:09]  INFO OK
```

I was thinking initially to just work around this by doing a dance with whitelist files, `sed -i`, and `blocky lists refresh`. But had a suspicion that this might be a bug/oversight, so I tried again. This time using an empty blacklist for `alpha`, a logical no-op, right?

```yaml
blocking:
  blackLists:
    alpha:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  whiteLists:
    alpha:
      - |
        www.wordreference.com
#    ...
  clientGroupsBlock:
    default:
      - alpha
#     ...
```

```sh
$ blocky blocking disable --groups alpha
[2023-12-21 18:06:36]  INFO OK
```

Everything works as expected: I can no longer resolve the domain(s) in `alpha`. Similarly, re-enabling it allows the domain to be resolved. I've read the documentation, and know that:

*If the same group has black and whitelists, whitelists will be used to disable particular blacklist entries. If a group has only whitelist entries -> this means only domains from this list are allowed, all other domains will be blocked.*

However, this still caught me by surprise. Can I ask, is this expected behaviour? As someone who does not use blacklists, being able to disable particular whitelist groups is definitely useful. Having to create a null entry in the blacklist section is not ideal IMO. Thank you for your work on this project.

**Comment by bpn19** [comment]
Just want to add, the null entry workaround does NOT work if you give *every* group its own entry. My original example taken literally wouldn't work as I explained. In that case, the behaviour is as explained in the documentation. So, you would need to at least add a `beta` entry that is whitelist-only to the `default` block, so that "all other domains will be blocked". Like so:

```yaml
blocking:
  blackLists:
    alpha:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  whiteLists:
    alpha:
      - |
        www.wordreference.com
    beta:
      - |
        github.com
#    ...
  clientGroupsBlock:
    default:
      - alpha
      - beta
#     ...
```

I still feel that the way that this works currently could be better as I said originally. For someone who does not use blacklists, `blocky blocking` becomes essentially useless.
