### ISSUE TITLE
Implement rate-limit for outgoing requests

### ISSUE THREAD

**Issue by adeelx** [0xERR0R/blocky#1382]
### Problem
I'm using `1.1.1.1` as my upstream as follows:
```
upstreams:
  strategy: parallel_best
  init:
    strategy: fast
  groups:
    default:
    - tcp-tls:1.1.1.1:853 # cloudflare
    - tcp-tls:1.0.0.1:853 # cloudflare
```
Whenever I restart the `blocky` container I run afoul of CloudFlare's 10QPS limit because all the devices on the network are simultaneously requesting IPs. To counter this, I have had to put `blocky` behind `dnsmasq` and on every restart I have to first switch `dnsmasq` to use Google DNS, then start `blocky` and finally once `blocky` shows that it can handle queries I switch `dnsmasq` to use blocky.

Do note that this happens _only_ when the `blocky` DNS server has been down for ~30mins or so and the network doesn't have any DNS resolvers which causes devices to retry queries and hence builds up the query volume.

### Relevant Links
- [Is there any rate-limiting for 1.1.1.1 DNS queries?](https://community.cloudflare.com/t/throttling-or-other-issue/122531)
- [The rate limit isn't static and 10qps is pretty rare.](https://news.ycombinator.com/item?id=36988883)
- [Throttling or other issue](https://community.cloudflare.com/t/throttling-or-other-issue/122531)

### The Ask
It will be helpful if `blocky` can be configured to not exceed a given QPS limit on a global level. Something along the lines of follows:
```
upstreams:
  qps_limit: 10 # or another sane default
  strategy: parallel_best
  init:
    strategy: fast
  groups:
    default:
    - tcp-tls:1.1.1.1:853 # cloudflare
    - tcp-tls:1.0.0.1:853 # cloudflare
```
This would make cold-starts of blocky much easier.
