### ISSUE TITLE
fails to resolve cloudflare dev domain until a restart of blocky

### ISSUE THREAD

**Issue by tcurdt** [0xERR0R/blocky#1383]
This is weird.

It seems like I have to restart blocky to pick up on new previously unseen domains from cloudflare pages. This fails first:

`nslookup site-nursingthetravelbug-com.pages.dev`

and works after a restart of blocky.

I am running `spx01/blocky:v0.23` with this config

```
port: 53
httpPort: 4000
logLevel: error
prometheus:
  enable: true
  path: /metrics

upstream:
  default:
    - 8.8.8.8
    - 8.8.4.4
    - 1.1.1.1

customDNS:
  customTTL: 1h
  filterUnmappedTypes: true
  mapping:
    # devices

blocking:
  refreshPeriod: 24h
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
```

Any idea what is causing this?
