### ISSUE TITLE
Query Logging: Ignore certain domains or regex entries

### ISSUE THREAD

**Issue by gspannu** [0xERR0R/blocky#1390]
I have an OPNsense router and Blocky running on a Debian machine separately.
I have a lot of Apple devices that seem to generate a lot (hundreds !) of queries like 
```
b._dns-sd._udp.0.1.168.192.in-addr.arpa
lb._dns-sd._udp.home
db._dns-sd._udp.home

```
It is basically _conditional forwarding that causes these excessive queries_, and is a _well known/ well documented issue appearing on both PiHole and AdGuard Home_. Many articles on the interment.

While I understand that the source of these queries is Apple devices, and Blocky cannot do much with these... **However, can these queries be omitted from the query log?**

Both Pi-Hole and AGH have _implemented a feature that certain domain names are not included in the query log or statistics_.

----
Could we have a **config section within queryLog** where certain domain names/ regex entries can be defined and **these will be ignored to be sent to the query log**.

Something like:
```
queryLog:
  type: postgresql
  target: postgres://user:password@<ipaddr>:5432/db_name
  logRetentionDays: 7
  ignoredomains:
    - |
    - *._dns-sd._udp.home
    - *.apple.com
    - /^.*p\.(([0-9]{1,3}\.){4})in-addr\.arpa$/
    - /^banners?[_.-]/
```

It is basically conditional/ lookup forwarding that causes these excessive queries. If I disable the below then these queries stop, but unfortunately so does client name lookup. I want the query log to report Client_name and it only works if lookup forwarding is enabled.

My config.yml
```
clientLookup:
  upstream: 192.168.1.1:53535  #Address of Router running dnsmasq

```
