### ISSUE TITLE
K8s: cannot run in Restricted PSS profile

### ISSUE THREAD

**Issue by zc-devs** [0xERR0R/blocky#1461]
I deploy Blocky in Kubernetes and always try to comply with Restricted profile of [Pod Security Standard](https://kubernetes.io/docs/concepts/security/pod-security-standards/). It requires to drop all capabilities, except NET_BIND_SERVICE.

I deploy Blocky on high port:
```yaml
    ports:
      dns: 1053
      http: 4000
```
with container settings below:
```yaml
      containers:
        - name: blocky
          image: ghcr.io/0xerr0r/blocky:v0.23
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - name: dns-tcp
              containerPort: 1053
            - name: dns-udp
              containerPort: 1053
              protocol: UDP
            - name: http
              containerPort: 4000
```

Currently, Blocky cannot run in Restricted profile. I get log line
```
exec /app/blocky: operation not permitted
```
and container gets restarted.

If I comment out `capabilities: drop: - ALL`, then container runs.

While working on #1460, I built custom image, commented out `BIN_AUTOCAB=1` and container was built without `setcap 'cap_net_bind_service=+ep'`. This image runs well in fully restricted PSS profile.

Besides, I want to mention #1353.

That being said, it would be great to have an image without capabilities. It could be separate version like `v0.23-unprivileged`.

**Comment by SISheogorath** [comment]
You can run blocky with PSS restrict. PSS restricted allows to add `NET_BIND_SERVICE`.

This is how I run blocky in a Namespace with PSS restricted version v1.26: https://git.shivering-isles.com/shivering-isles/infrastructure-gitops/-/blob/37b991bc0f7f4955773bce1df3ef5a0b6ce6cd0f/apps/k8s01/dns/dns.yaml

**Comment by zc-devs** [comment]
> It requires to drop all capabilities, except NET_BIND_SERVICE

I supposed, that config below should work
```yaml
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
```

However, the point is I do not need privileged ports and want to run without `NET_BIND_SERVICE` capability. But as this capability is set on executable, I have to add `NET_BIND_SERVICE` in K8s or rebuild image.
Propose is have an image without capabilities set on executable like `v0.23-unprivileged`.

Perhaps, I should have renamed the issue...

**Comment by zc-devs** [comment]
`ghcr.io/0xerr0r/blocky:v0.24`

While I confirm, that configuration below works in my cluster
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocky
spec:
...
      containers:
        - name: blocky
          image: ghcr.io/0xerr0r/blocky:v0.24
          ports:
            - name: dns-udp
              containerPort: 1053
              protocol: UDP
            - name: dns-tcp
              containerPort: 1053
              protocol: TCP
            - name: http
              containerPort: 4000
              protocol: TCP
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      securityContext:
        runAsUser: 100
        runAsGroup: 100
        runAsNonRoot: true
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
```
there might be clusters (old versions?) which do not set `ambient` capabilities and this configuration/workaround won't work.

[Linux Capabilities in OpenShift](https://www.redhat.com/en/blog/linux-capabilities-in-openshift)
[Running a container with runAsNonRoot and add capabilities](https://stackoverflow.com/questions/72872335/running-a-container-with-runasnonroot-and-add-capabilities)

That said, the dedicated unprivileged image is still preferable solution, I think.
