### ISSUE TITLE
individual lists saves memory? 

### ISSUE THREAD

**Issue by bcookatpcsd** [0xERR0R/blocky#1469]
I was trying to slim down and find lists that were 'worth it' and 'not'

setup at home for testing for work.. 

docker stats cpu isn't relevant fyi

```
CONTAINER ID   NAME         CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
b7db590b667c   blocky       0.02%     602MiB / 15.41GiB     3.81%     0B / 0B           0B / 389kB        10
```

and the config:

```
  denylists:
    ads:
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@main/wildcard/multi.txt
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/light.txt
    tif:
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/tif.txt
      - https://urlhaus.abuse.ch/downloads/hostfile/
        #- https://threatfox.abuse.ch/downloads/hostfile/
    tracking:
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/native.winoffice.txt
    bypass:
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/doh-vpn-proxy-bypass.txt
    nrds:
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/nrds.10.txt
        
        
  clientGroupsBlock:
    default:
      - ads
      - tif
      - tracking
      - bypass
      - nrds
```

```
CONTAINER ID   NAME         CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
b7db590b667c   blocky       0.96%     735.8MiB / 15.41GiB   4.66%     0B / 0B           0B / 0B           10
```

and the config file.. 

```
  denylists:
    ads:
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@main/wildcard/multi.txt
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/light.txt
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/tif.txt
      - https://urlhaus.abuse.ch/downloads/hostfile/
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/native.winoffice.txt
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/doh-vpn-proxy-bypass.txt
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/nrds.10.txt
    tif:
    tracking:
    bypass:
    nrds:
        #- https://threatfox.abuse.ch/downloads/hostfile/
        #      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@main/wildcard/tif.txt
  clientGroupsBlock:
    default:
      - ads
      - tif
      - tracking
      - bypass
      - nrds

```

splitting them up saves memory apparently.. 

```
docker exec -it blocky /app/blocky version
blocky
Version: v0.23-101-g4ebe1ef
Build time: 20240426-105018
Architecture: amd64
```
