### ISSUE TITLE
👍 An excellent project, it would be even better with the addition of multi-port services.

### ISSUE THREAD

**Issue by hululu1068** [0xERR0R/blocky#1483]
An excellent project, it would be even better with the addition of multi-port services.
For upstream DNS grouping, different ports utilize different groups:
```
upstreams:
  groups:
    default:
      - 5.9.164.112
      - tcp-tls:fdns1.dismail.de:853
      - https://dns.digitale-gesellschaft.ch/dns-query
    worker:
      - https://1.1.1.1/dns-query
      - 8.8.8.8

ports:
  dns: 53
    - groups: default
  dns2: 54
    - groups: worker
```

and,Hope to see support for OpenWRT.
