### ISSUE TITLE
List parsing change in v0.24, no longer allows spaces

### ISSUE THREAD

**Issue by disconn3ct** [0xERR0R/blocky#1492]
In 0.23, this works:
```yaml
customDNS:
  mapping:
    foopotato.here.com: 1.1.1.1, 2.2.2.2, 3.3.3.3
```
In 0.24, it exits with an error:
`blocky-86b45d55b-m8bz2 blocky [2024-05-26 09:26:49] FATAL unable to load configuration: wrong file structure: invalid IP address ' 2.2.2.2'`

Removing the space (`1.1.1.1,2.2.2.2,3.3.3.3`) solves the regression.
