### ISSUE TITLE
root nameserver for blocky config. Need a help

### ISSUE THREAD

**Issue by mmbdv** [0xERR0R/blocky#1503]
Hello
Is it possible to use root nameserver in upstreams? 
Cause when i added them in to my config, i keep getting next nameserver. Or there is any option to enable recursive resolve?

```
upstreams:
  strategy: strict
  groups:
    default:
      - 198.41.0.4
      - 199.9.14.201
      - 192.33.4.12
      - 199.7.91.13
      - 192.203.230.10
      - 192.5.5.241
      - 192.112.36.4
      - 198.97.190.53
      - 192.36.148.17
      - 192.58.128.30
      - 193.0.14.129
      - 199.7.83.42
      - 202.12.27.33
```

i'm a newbie 😵
