### ISSUE TITLE
conditional/split horizon only answers?

### ISSUE THREAD

**Issue by bcookatpcsd** [0xERR0R/blocky#1510]
This might be something like #1462 

Looking to provide an internal answer when asked from internal client, otherwise provide external answer. 

It seems that this does not yet exist.. right? 

https://0xerr0r.github.io/blocky/latest/configuration/#conditional-dns-resolution

Quote:

Usage: One usecase when having split DNS for internal and external (internet facing) users, but not all subdomains are listed in the internal domain

Looking for the ability to do something like this:

```
conditional:
   fallbackUpstream: true
 # next four lines
   groups:
     10.0.0.0/8:
       rewrite:
         dns.rewrite.entry: 1.2.3.4
   mapping:
```

https://0xerr0r.github.io/blocky/latest/configuration/#custom-dns

similar logic.. 

Thanks in advance.. 

Sorry if this does exist and I did not read/implement it properly..
