### ISSUE TITLE
blocky not writing to mariadb docker container

### ISSUE THREAD

**Issue by panks21** [0xERR0R/blocky#1547]
MariaDB 11.4.2-MariaDB-ubu2404
block - 0.24

docker-compose contents

```
version: "2.1"

services:
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5000:5000"
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./blocky-config/config.yml:/app/config.yml
##version: '3'
##volumes:
##  data:
##services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: blocky
      MYSQL_DATABASE: blocky
      MYSQL_USER: blocky
      MYSQL_PASSWORD: blocky
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
```

querylog config in config.yml

```
queryLog:
  type: mysql
  target: blocky:blocky@tcp(mariadb:3306)/blocky?charset=utf8mb4&parseTime=True&loc=Local
  logRetentionDays: 5
  creationAttempts: 20
  creationCooldown: 2s
  fields:
    - clientIP
    - duration
  flushInterval: 30s
```

post adding mysql as the source in the grafana.. the dashboard is empty. 
I am not a database expert. please pardon my mistake in config..
