### ISSUE TITLE
how to have a device with ip 192.168.1.10 being completly unfiltered, to be full allowlisted (whitelisted)

### ISSUE THREAD

**Issue by niouniou49** [0xERR0R/blocky#1559]
HI Here
it s  just a configuration question
how can i remove a specific device (192.168.1.10 from any blacklist (bloking lists), so this ip is not blocked by blocky at all?
thanks for your advice
pascal

**Comment by gspannu** [comment]
Just make your configuration file to reflect the same. Read the documentation.


As an example:
```
blocking:
  blackLists:
    adblock:
      - https://big.oisd.nl/domainswild            #OISD Big
    bypass:
      # No Adblocking group, bypass, everything allowed

  whiteLists:
    adblock:
      - |
        *.auth.split.io

  # definition: which groups should be applied for which client
  clientGroupsBlock:
    default:
      - adblock

    192.168.1.10/32:   #bypass, no adblocking
      - bypass

```
