### ISSUE TITLE
Can't gracefully shutdown unconnectable mysql instance

### ISSUE THREAD

**Issue by jvandenbroek** [0xERR0R/blocky#1585]
To make sure blocky always connects to a mariadb server on startup, I've set creationAttempts to -1. However it is impossible to interrupt the process when no connection is possible, only SIGKILL can be used to shoot it down. It would be nice to have some logic that allows graceful shutdown requests to be processed in this state. Thanks!

**Comment by ThinkChaos** [comment]
Seems like GORM, the DB library blocky uses, isn't the best at handling cancellation: https://github.com/go-gorm/gorm/issues/6791, https://github.com/go-gorm/gorm/issues/5599

The second issue recommends adding a `timeout` parameter to your DB target when using MySQL. See the [supported params](https://github.com/go-sql-driver/mysql?tab=readme-ov-file#dsn-data-source-name).  
Example:
```yaml
queryLog:
  type: mysql
  target: db_user:db_password@tcp(db_host_or_ip:3306)/db_user?charset=utf8mb4&parseTime=True&loc=Local&timeout=5s
```
