### ISSUE TITLE
Feature request - Config sync

### ISSUE THREAD

**Issue by imp1sh** [0xERR0R/blocky#1612]
I run blocky on different hosts as a container. If I'm not mistaken there is no way to sync the configuration.
So my feature request would be to make the configuration configureable via environment variable. The full config could be put into a dict var so that the content of the configuration file could just be put into the config var:

```yaml
env:
  config:
    ports:
      dns: 53
      http: 4000
    ...
```
