### ISSUE TITLE
Prefetch errors: Network is unreachable

### ISSUE THREAD

**Issue by ChitranshuV** [0xERR0R/blocky#1617]
I am seeing my console log filled with multiple messages like this

```
[2024-10-02 00:47:36] ERROR caching: can't prefetch 'www.youtube.com' resolution failed: resolver: "upstream 'https://dns.quad9.net/dns-query'" error: upstream 'https://dns.quad9.net/dns-query': can't resolve request via upstream server https://dns.quad9.net/dns-query (https://149.112.112.112:443/dns-query): can't perform https request: Post "https://149.112.112.112:443/dns-query": dial tcp 149.112.112.112:443: connect: network is unreachable
resolver: "upstream 'https://cloudflare-dns.com/dns-query'" error: upstream 'https://cloudflare-dns.com/dns-query': could not resolve IPs for upstream cloudflare-dns.com: 2 errors occurred:
	* resolution failed: resolver: "upstream 'tcp+udp:9.9.9.9'" error: upstream 'tcp+udp:9.9.9.9': can't resolve request via upstream server tcp+udp:9.9.9.9 (9.9.9.9:53): dial tcp 9.9.9.9:53: connect: networkis unreachable
resolver: "upstream 'tcp+udp:1.1.1.1'" error: upstream 'tcp+udp:1.1.1.1': can't resolve request via upstream server tcp+udp:1.1.1.1 (1.1.1.1:53): dial tcp 1.1.1.1:53: connect: network is unreachable
	* resolution failed: resolver: "upstream 'tcp+udp:9.9.9.9'" error: upstream 'tcp+udp:9.9.9.9': can't resolve request via upstream server tcp+udp:9.9.9.9 (9.9.9.9:53): dial tcp 9.9.9.9:53: connect: networkis unreachable
resolver: "upstream 'tcp+udp:1.1.1.1'" error: upstream 'tcp+udp:1.1.1.1': can't resolve request via upstream server tcp+udp:1.1.1.1 (1.1.1.1:53): dial tcp 1.1.1.1:53: connect: network is unreachable
```

This is my config.yml
```
upstreams:
  groups:
    default:
      - https://cloudflare-dns.com/dns-query
      - https://dns.quad9.net/dns-query
  init:
    strategy: failOnError

ports:
  dns: 53
  tls: 853
  https: 443
  http: 4000

bootstrapDns:
  - upstream: 1.1.1.1
  - upstream: 8.8.8.8
  - upstream: 9.9.9.9

log:
  level: info
  format: text
  timestamp: true
  privacy: false

blocking:
  denylists:
    ads:
      - https://big.oisd.nl/domainswild
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt
    custom:
      - https://gist.githubusercontent.com/ChitranshuV/ae5121ce4145dc0c98826d8caee14903/raw/b717fdfadc3614970327ada76f29670ce5761f3c/NewsWildcard.txt
      - https://gist.githubusercontent.com/ChitranshuV/5c06421113c1aa35b8f01397d2ad0777/raw/d7ff05c7a6b54f6a46917903388898d7b4d23530/SocialMediaWildcard.txt
    adult:
      - https://nsfw.oisd.nl/domainswild
  blockType: nxDomain
  clientGroupsBlock:
    default:
      - ads
      - custom
      - adult
  loading:
    refreshPeriod: 1h
    strategy: failOnError
    concurrency: 8
    downloads:
      timeout: 5m
      attempts: 10
      cooldown: 1s

caching:
  minTime: 5m
  maxTime: 30m
  maxItemsCount: 0
  prefetching: true
  prefetchExpires: 24h
  prefetchThreshold: 2
  prefetchMaxItemsCount: 0

prometheus:
  enable: true
  path: /home/chitranshu/Downloads/blocky_v0.24_Linux_x86_64/metrics

queryLog:
  type: csv
  target: /home/chitranshu/Downloads/blocky_v0.24_Linux_x86_64/logs
  logRetentionDays: 7
  flushInterval: 30s


```
