### ISSUE TITLE
Conditional forwarding exclusions (pinpoint DNS zones)

### ISSUE THREAD

**Issue by tehmacs** [0xERR0R/blocky#1631]
I have a split-horizon DNS use-case in which some internal records are not stored in the internal authoritative DNS server and they **must** be resolved externally because I am proxying them through CloudFlare.

The DNS zone is the same for internal and external records, so I'm looking to accomplish something like this without any rewrites of sort:

```
conditional:
  mapping:
    myhost.mydomain.com: 1.1.1.1
    mydomain.com: 10.0.0.1
```

This is basically an exclusion to a conditional forwarding rule, or a pinpoint DNS zone if you prefer.

I tried this configuration but ```myhost.mydomain.com``` returns NXDOMAIN, is there any way to achieve this?
