### ISSUE TITLE
When upstream is unavailable, blocky returns "Not Ready" responses for queries that do not rely on upstream

### ISSUE THREAD

**Issue by ideabucket** [0xERR0R/blocky#1639]
I have this Blocky setup:

```
upstreams:
  init:
    strategy: fast
  groups:
    default:
      - 10.64.0.1
  strategy: parallel_best

conditional:
  fallbackUpstream: false
  mapping:
    local.dev: 192.168.1.1
    168.192.in-addr.arpa: 192.168.1.1
```

`10.64.0.1` is a DNS server on the far side of a WireGuard tunnel from my router. If that tunnel is offline (and Blocky thus can't reach upstream), and I query a host in my internal domain `local.dev`, I get this response from Blocky:

```

**Comment by ideabucket** [comment]
Possibly relevant: `local.dev` is a placeholder. I actually use a real domain that has public authoritative nameservers for my internal network, so I can complete ACME DNS challenges. But the A records for my internal hosts aren't on the authoritative nameservers, only on 192.168.1.1.

**Comment by ideabucket** [comment]
Still very much an issue, unfortunately.

**Comment by ideabucket** [comment]
Keepalive. (Closing bug reports after 90 days is very annoying behaviour.)

**Comment by dpkg-i-foo-deb** [comment]
Can confirm this happens and it is annoying, all my homelab services go down when the upstream becomes unreachable even though I have my domains on local resolution

**Comment by brokoler** [comment]
I had an internet outage today and based on this issue my clients were not able to resolve local dns entries. All my local services stopped working for hours until the internet outage was fixed. Blocky only continued resolving customDNS entries when the public upstream DNS server was available.

@0xERR0R 
Sorry for pinging, not sure if you have seen the issue yet. In my point of view it's a critical issue, since from a client perspective Blocky  stops working without upstream access. Hope it can be fixed.

**Comment by 0xERR0R** [comment]
I tried to reproduce it with following config:

```yaml
upstreams:
  init:
    strategy: fast
  groups:
    default:
      - 200.200.200.200
  strategy: parallel_best

conditional:
  fallbackUpstream: false
  mapping:
    local.dev: 192.168.178.1
    168.192.in-addr.arpa: 192.168.178.1
```

upstream 200.200.200.200 is not reachable.

´dig @localhost gw.local.dev´ returns NXDOMAIN (as expected and sends query to 192.168.178.1).
´dig @localhost example.com ´ ends with timeout

Does this error still occur in the latest version of blocky?
