### ISSUE TITLE
customDNS to group different hosts

### ISSUE THREAD

**Issue by mhymny** [0xERR0R/blocky#1643]
Hello, I think I either found a bug or misunderstood the rewrite part for [customDNS](https://0xerr0r.github.io/blocky/latest/configuration/#custom-dns).

I have multiple hosts that host multiple services and I thought I could use `rewrite` to group multiple services like so:
```
customDNS:
  rewrite:
    testa.example.com: host1
    testb.example.com: host1
  mapping:
    host1: 1.1.1.1,2606:4700:4700::1111
```
However this approach doesn't give me a response when testa.example.com is queried. testb.example.com seems to work though...
