### ISSUE TITLE
Minimal configuration.

### ISSUE THREAD

**Issue by PauloFerreira25** [0xERR0R/blocky#1672]
Hi, could you create a config.yml in the docs that is a minimal configuration?

It would be great to have this for installation scripts.

**Comment by samyerkes** [comment]
Looks like this is already included in the docs. [https://0xerr0r.github.io/blocky/latest/installation/#prepare-your-configuration](https://0xerr0r.github.io/blocky/latest/installation/#prepare-your-configuration)

**Comment by PauloFerreira25** [comment]
Hello, thank you very much for your reply.

Yes, it is available in the documentation.

But to use it in the system installation script, it would be very useful to have an endpoint that can be used for curl.
By keeping it within the project's own repository, you would have control over how it should work.


Explaining why I got here.

I was testing the scripts from this project:
https://community-scripts.github.io/ProxmoxVE/scripts?id=blocky

Which installs blocky DNS proxy (which is very good, thanks for creating it).

Their script installs the latest version of blocky project. But with the configuration files from an old version, which makes blocky not work.

Since they are a project that tries to "facilitate" installations, it would be almost an endless battle, trying to manage all the projects, all the configurations when they are created.

When I did the installation using the script, because of this configuration incompatibility problem, I had the feeling that the blocky was not working. 

Due to "willpower" in wanting to make blocky work, I worked to identify that the problem was actually the incompatibility of the initial configuration, and that it was "hardcoded", where it could be a curl that does the initial download.

**Comment by polarathene** [comment]
> By keeping it within the project's own repository, you would have control over how it should work.

https://github.com/0xERR0R/blocky/blob/main/docs/config.yml

**Comment by PauloFerreira25** [comment]
Hello, thank you very much for your reply, however, this file is not a "minimal" configuration.

https://github.com/0xERR0R/blocky/blob/main/docs/config.yml
This file contains all possible configurations and examples of them.

My thinking is:

- In the case of a person who wants to start using blocky, is not a network expert, but wants to have their privacy, they need to start with something, and then evolve.

If they receive this file with everything already configured, many things will probably fail, will not work and will create frustration.

That's what happened to me when I used it for the first time, not because of a blocky error, but because of an error in the script that installed blocky. The script configured blocky with parameters that were no longer supported, and consequently, did not do the minimum to work.

I'm not trying to solve my problem, my blocky is already working, I've already been through the frustration. I want others to not go through this and have a more simplified blocky "installation", which works "out of the box" and evolves in configurations over time and on demand.

**Comment by 0xERR0R** [comment]
Hello @PauloFerreira25,

I see your point, the question is what is meant by "minimal" configuration for people who wants to have their privacy?

With or without blocklists and when with, which blocklists?

Which upstream servers should be used? If google/cloudfoundry etc. -> many people would say, google/cloudfoundry/xxx is evil, there is no privacy. If we use some freedom DNS servers -> some of them have bad performance or don't work after some time -> this should be maintained somehow.

Would you like to provide an example of a minimal configuration which can be used by a new user?

**Comment by PauloFerreira25** [comment]
Hi, please forgive me if any of the settings are wrong.

What I think would be something like this:
https://github.com/0xERR0R/blocky/blob/main/docs/config_minimal.yml

```yaml
upstreams:
  groups:
    default:
      - https://dns.digitale-gesellschaft.ch/dns-query
blocking:
  denylists:
    ads:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - http://sysctl.org/cameleon/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    special:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
  clientGroupsBlock:
    default:
      - ads
      - special
ports:
  dns: 53
  tls: 853
  https: 443
  http: 4000

log:
  level: info

```

I removed the comments, just to make the file more compact.

The idea is to just be the minimum so that blocky can call and respond to DNS queries.

I also don't have enough knowledge to indicate that these are the best values.
