### ISSUE TITLE
[Feature Request] DNS64 Support

### ISSUE THREAD

**Issue by TymanLS** [0xERR0R/blocky#1698]
I would love to see support for DNS64 added to blocky. This feature, described in [RFC 6147](https://www.rfc-editor.org/rfc/rfc6147), would have blocky synthesize AAAA records for hosts where only A records are found, and thus allow IPv6-only hosts to resolve addresses for IPv4-only hosts and send traffic to them through a separate NAT64 gateway. Currently I am solving this problem by using upstream DNS providers that support DNS64, such as [Cloudflare](https://developers.cloudflare.com/1.1.1.1/infrastructure/ipv6-networks/) and [Google](https://developers.google.com/speed/public-dns/docs/dns64) DNS64 servers, but I would like to have more flexibility in my selection of upstream DNS providers and which DNS64/NAT64 prefix I can use; currently Cloudflare and Google only support the well-known DNS64 prefix (64:ff9b::/96), but it would be nice to have the option to select a different prefix if desired. Thank you!

**Comment by benbender** [comment]
Would also love to see this implemented as it would be a foundational building block of getting rid of legacy ip on many home networks!

**Comment by Bartosz-lab** [comment]
DNS64 support would be awesome

**Comment by p3lim** [comment]
I would love to see support for this as well, but I'd like to add that this should be configurable with group mappings, just like blocking and upstreams, because depending on how you access blocky you might not have NAT64 to support it.

**Comment by TymanLS** [comment]
I am still interested in this feature! I don't have much experience with Go, but let me know if there's any other information I can provide to help with this effort.

**Comment by 0xERR0R** [comment]
@TymanLS This feature sounds interesting and can be implemented in blocky. I could start to implement it. Just for my understanding: DNS64 would be implemented in blocky, this is basically a translation layer which always returns AAAA record even if upstream DNS server returns only A. Where is the part with NAT64 gateway? Is it something you host in your local network or is it provided by your ISP?

My ISP (still) doesn't support ipv6, so I can't really test it

**Comment by TymanLS** [comment]
@0xERR0R Thank you for taking a look at this feature request!

Sorry about the confusion regarding the NAT64 gateway. The NAT64 gateway is a service hosted somewhere that translates between IPv6 and IPv4 addresses. DNS64 is not useful without a NAT64 gateway, but they are separate components; for blocky, we only need to worry about DNS64, not the NAT64 gateway.

For DNS64, I believe your understanding is correct. If a DNS query returns any AAAA records, then no action is required. However, if the DNS query only returns A records, then blocky will also return AAAA records that are calculated based on the DNS64 prefix and the A records.

For example, let's say we try to make a DNS request for an IPv4-only name like github.com. The reply contains no AAAA records:

```
$ nslookup github.com
Non-authoritative answer:
Name:   github.com
Address: 140.82.112.3
```

If we configure DNS64 using the well-known DNS64 prefix of 64:ff9b::/96, then the same DNS request will look like this:
```
$ nslookup github.com
Non-authoritative answer:
Name:   github.com
Address: 140.82.112.3
Name:   github.com
Address: 64:ff9b::8c52:7003
```

Let me know if there is any other information I can provide!

**Comment by 0xERR0R** [comment]
@TymanLS Ok, I would start with the implementation. Would you volunteer to test the implementation if I provide a Docker image?

**Comment by TymanLS** [comment]
Yes, I can certainly help test the implementation, just let me know where/how to get the docker image once it is ready. Thank you!

**Comment by 0xERR0R** [comment]
The image is tagged with "fb-dns64". I would greatly appreciate your feedback.

configuration:

```yaml
dns64:
  enable: true
  # optional: DNS64 prefixes for IPv4-to-IPv6 address synthesis
  # Multiple prefixes allow for load balancing or redundancy across multiple
  # NAT64 gateways. DNS64 will synthesize one AAAA record per prefix per A record.
  #
  # Format: IPv6 prefix in CIDR notation
  # Valid prefix lengths (per RFC 6052): /32, /40, /48, /56, /64, /96
  # - /96 is most common (well-known prefix 64:ff9b::/96)
  # - Shorter prefixes (/32, /40, etc.) allow more flexibility in address assignment
  #
  # default: [64:ff9b::/96] (RFC 6052 well-known prefix)
  #
  # IMPORTANT: Prefixes must not overlap. Overlapping prefixes will be rejected.
  prefixes:
    - 64:ff9b::/96
```
