### ISSUE TITLE
[Feature] Add option to disable caching for conditional dns resolver

### ISSUE THREAD

**Issue by eddster2309** [0xERR0R/blocky#1712]
Hi,
Would it be within the scope of the project for a flag to be added which would disable caching for conditional forwarders? For example, say I have a conditional forward setup to an IPA DNS server, I would like to always get the most up to date record from IPA, without editing the TTL of specific domains.

I have come up with three possible methods to implement this:

1. A global flag to disable caching for all conditionally forwarded domains, similar to how `fallbackUpstream` was implemented. This has the benefit of not significantly changing the config file layout, as only a single boolean would need to be added to the configuration file.
2. The better way in my opinion would be to to add a flag to each domain to disable caching for specific domains. The major issue with this approach is it would require a major change in the config file, as it would need to change the current key value pair to be nested map, like the following:
```
conditional:
  fallbackUpstream: false
  rewrite:
    example.com: fritz.box
    replace-me.com: with-this.com
  mapping:
    fritz.box:
      upstream: 192.168.1.1
      cache: false
```
3. Another option is to add another list of domains which are exempted from caching. This would also have the benefit of being able to disable caching on a domain that uses the default upstream servers. This would have the side effect of splitting config into two separate places.

I would be happy to submit PRs about this.

Thanks for your consideration

**Comment by adjokic** [comment]
+1 on this issue. I tried this configuration, but to no avail:
```
customDNS:
    zone: |
        $ORIGIN mydomain.local
        $TTL 0
```
not sure if I'm doing it right

**Comment by adjokic** [comment]
A new config option has been added to exclude certain paths from the cache:
```
caching:
  minTime: 5m
  cacheTimeNegative: 5m
  exclude:
    - /.*\.local$/
```

so now any lookup to a `*.local` service gives a 0 TTL:
```
❯ dig +ttlunits myservice.dc.local

...
;; ANSWER SECTION:
myservice.dc.local.              0s      IN      A       1.2.3.4
```

I believe this issue can be closed.
