### ISSUE TITLE
Default LOG settings are rediculous

### ISSUE THREAD

**Issue by zQueal** [0xERR0R/blocky#1719]
Woke up to a warning that my VPS storage was full. Upon inspection, the Blocky log file was over 200GB after being installed for less than 3 days.

Seems a bit dubious. Any guidance here? I can't really find any configuration options to limit logging.

**Comment by zQueal** [comment]
Best solution I've found to this was to use docker to limit the log size;

```yml
version: "2.1"
services:
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    # Optional the instance hostname for logging purpose
    hostname: blocky-hostname
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    environment:
      - TZ=Europe/Berlin # Optional to synchronize the log timestamp with host
    volumes:
      # Optional to synchronize the log timestamp with host
      - /etc/localtime:/etc/localtime:ro
      # config file
      - ./config.yml:/app/config.yml:ro
    logging:
      options:
        max-size: 100m # limits log to 100mb
```

IMO this is a pretty unexpected issue and sane defaults should be added to the website. Maybe a few GB?
