### ISSUE TITLE
[BUG] DNS over HTTPS ignores custom TTL values

### ISSUE THREAD

**Issue by brokoler** [0xERR0R/blocky#1731]
Blocky ignores custom TTL values when DNS over HTTPS is used.
Tested via Firefox about:networking#dns on my installations, would be great if someone else can confirm the issue.
Blocky v0.25 was used for testing.

Following parameters in config.yml are working fine with DNS port 53 but not with DNS over HTTPS:

```
customDNS:
  customTTL: 24h
blocking:
  blockTTL: 24h
caching:
  minTime: 24h
  maxTime: 24h
```

**DNS over HTTPS example (direct connection to Blocky without reverse proxy):**

![Image](https://github.com/user-attachments/assets/886f0b26-365d-45e7-b11e-2406e1335e02)

**Plain DNS example:**

![Image](https://github.com/user-attachments/assets/7b93f71e-3e84-4e13-b911-2b1cade4a185)

**Comment by 0xERR0R** [comment]
Tested the latest dev version with following config:

```yaml
upstreams:
  groups:
    default:
      - 1.1.1.1
      - 8.8.8.8
ports:
  dns: 53535
  http: 8080
  https: 8443
caching:
  minTime: 24h
  maxTime: 24h
```

Test with DoH

```bash
dnslookup google.de https://localhost:8443/dns-query 
dnslookup master
TLS verification has been disabled
Server: https://localhost:8443/dns-query

dnslookup result (elapsed 37.683591ms):
;; opcode: QUERY, status: NOERROR, id: 35452
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;google.de.     IN       A

;; ANSWER SECTION:
google.de.      86400   IN      A       142.250.203.99
```

test with plain
```bash
dig @localhost -p53535 google.de

; <<>> DiG 9.20.6 <<>> @localhost -p53535 google.de
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19886
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;google.de.                     IN      A

;; ANSWER SECTION:
google.de.              86226   IN      A       142.250.203.99

;; Query time: 0 msec
;; SERVER: ::1#53535(localhost) (UDP)
;; WHEN: Sat Mar 08 22:38:27 CET 2025
;; MSG SIZE  rcvd: 43
```

I would say, It looks good. Maybe firefox expects something special...
