### ISSUE TITLE
Memory usage keeps climbing on blacklist refresh

### ISSUE THREAD

**Issue by axyzs** [0xERR0R/blocky#1770]
Hi, I’m new to Blocky and really like this project. I'm using the latest version (v0.25) in Docker.

Everything works smoothly except for one issue: memory usage keeps increasing and never goes back down. I noticed that the memory keeps climbing steadily.  The memory increase only occurs during blacklist refreshes. I also tried the list/refresh API and confirmed that the issue is caused by blacklist refreshes.

I searched the issues and found this one: https://github.com/0xERR0R/blocky/issues/470. The diagram there shows that memory usage increases during list refreshes but then drops back down once the refresh job completes.

However, I tested on two different machines and encountered the same issue. 

I tested with refreshPeriod set to 1 hour and left Blocky running for 8 hours. Memory usage grew over time as follows:

Start: ~100 MB
After 1 hour: 170 MB
After 2 hours: 220 MB
After 3 hours: 270 MB
...and so on, reaching ~370 MB after 8 hours. then I stopped docker container. 

I only used two blocklists, they are big, but don't think that was the reason that memory keeps increasing. the CPU was fine, didn't consume anything. I tried to set `maxItemsCount` and `prefetchMaxItemsCount` smaller to 2000 or removed `caching` section, but didn't notice any difference. 

 I'm not sure whether this is due to my config or a potential issue with Blocky itself. Any insights or suggestions would be appreciated.

```
upstreams:
  init:
    strategy: fast
  groups:
    default:
      - https://cloudflare-dns.com/dns-query
      - https://dns.quad9.net/dns-query
  strategy: parallel_best
  timeout: 2s
...
blocking:
  denylists:
    ads:
      - https://big.oisd.nl/domainswild
    nsfw:
      - https://nsfw.oisd.nl/domainswild
  loading:
    refreshPeriod: 1h
    strategy: blocking
    downloads:
      attempts: 5
      timeout: 60s
      writeTimeout: 30s
    concurrency: 8

caching:
  minTime: 5m
  maxTime: 30m
  maxItemsCount: 5000
  prefetching: true
  prefetchExpires: 2h
  prefetchThreshold: 5
  prefetchMaxItemsCount: 5000
  cacheTimeNegative: 30m

log:
  level: info
  format: text
  timestamp: true
  privacy: false

prometheus:
  enable: true
  path: /metrics
```
