### ISSUE TITLE
If multiple whitelist-only groups are defined, blocking of not whitelisted domains does not work

### ISSUE THREAD

**Issue by 0xERR0R** [0xERR0R/blocky#202]
## Problem 
WhitelistOnly is only used, if no more than two whitelists are available or all clients include all whitelists. 

Look at the following config snippet. Two Groups are defined, each with their own set of "whitelist" entries. 
```yaml
blocking:
 whiteLists:
   net_one:
      - net_one_whitelist.txt
   net_two:
      - net_two_whitelist.txt
  clientGroupsBlock:
    one-client*:
       - net_one
    two-client*:
       - net_two

clientLookup:
 clients:
   one-client-1:  [127.0.0.1]
   two-client-2:  [127.0.0.2]
```

If multiple WhitelistOnly groups are defined, then every client, which do NOT include ALL whitelists, can resolve non-whitelist items. 
The `reflect.DeepEqual()` list now contains the check if `[net_one] ==  [net_one, net_two]`, which will always return false.  

**Expected Behavior**: Both clients are restricted to the defined whitelistOnly domains.

**Behavior**: None of them have whitelist enabled.

## Possible solution 
- if groupsToCheck contains ONE whitelistOnly group, then the client can only lookup whitelisted domains (this is implemented in the PR)
- if groupsToCheck groups are ALL whitelistOnly group, then the client can only lookup whitelisted domains

I changed the data type from slice to dict for performance reason. 

Best regards,
c-f
