### ISSUE TITLE
intermittent timeouts

### ISSUE THREAD

**Issue by vkuznet** [0xERR0R/blocky#213]
Hi,
I start testing blocky in my home environment and found that it is quite unstable. I set it up as service running on macOS node and configured my open WRT router to use it for DHCP server via [DHCP options](https://openwrt.org/docs/guide-user/base-system/dhcp_configuration#dhcp_options). I setup prometheus and grafana to monitor it. What I found that after couple of hours of normal usage I can see timeouts to upstream DNS servers (I tried both with Google and Cloudfare), e.g.
```
[2021-05-23 16:53:14] ERROR server: error on processing request: resolution was not successful, used resolvers: 'upstream 'tcp+udp:1.1.1.1:53'' and 'upstream 'tcp+udp:8.8.8.8:53'' errors: [read udp 192.168.1.134:54619->8.8.8.8:53: i/o timeout read udp 192.168.1.134:59101->1.1.1.1:53: i/o timeout]
```
 or lost of UDP packets to local host, e.g.
```
[2021-05-23 15:44:31] ERROR can't write message: write udp [::]:53->192.168.1.191:52027: sendmsg: host is down
```
The configuration I used is the following:
```
upstream:
  default:
    - 1.1.1.1
    - 9.9.9.9
    - 8.8.8.8
    - 8.8.4.4
    - tcp-tls:cloudflare-dns.com:853
    - tcp-tls:fdns1.dismail.de:853
    - https://dns.digitale-gesellschaft.ch/dns-query
blocking:
  blackLists:
    ads:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - http://sysctl.org/cameleon/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    special:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
  clientGroupsBlock:
    default:
      - ads
prometheus:
  enable: true
  path: /metrics

queryLog:
  dir: /tmp
  perClient: true
  logRetentionDays: 7
port: 53
httpPort: 4000
```

The problem is that after error occur my connection are stuck and I need to restart the blocky.

Any suggestions how to improve/debug the situation?
