### ISSUE TITLE
Core dump on armv7

### ISSUE THREAD

**Issue by seud0nym** [0xERR0R/blocky#237]
Hi.

I am trying to run blocky on an ISP provided Technicolor router (model DJA0230), which uses a vendor customised version of OpenWRT. The actual version of OpenWRT is unknown; however previous firmware releases have been based on 15.05.1.

I downloaded and extracted blocky_0.14_Linux_armv7.tar.gz.

As soon as I run blocky, it core-dumps and the router reboots.

I had exactly the same behavior testing the armv7 version of AdGuard Home, but they also have an armv5 version which _does_ work on this device without issues.

The config .yaml file I am testing with is just a copy from https://0xerr0r.github.io/blocky/installation/#prepare-your-configuration with the port number changed:
```
upstream:
  default:
    - 46.182.19.48
    - 80.241.218.68
    - tcp-tls:fdns1.dismail.de:853
    - https://dns.digitale-gesellschaft.ch/dns-query
blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  clientGroupsBlock:
    default:
      - ads
port: 53535
httpPort: 4000
```

Contents of /proc/cpuinfo:
```
processor       : 0
model name      : ARMv7 Processor rev 1 (v7l)
BogoMIPS        : 1990.65
Features        : half thumb fastmult edsp tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x4
CPU part        : 0xc09
CPU revision    : 1

processor       : 1
model name      : ARMv7 Processor rev 1 (v7l)
BogoMIPS        : 1990.65
Features        : half thumb fastmult edsp tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x4
CPU part        : 0xc09
CPU revision    : 1

Hardware        : BCM963138
Revision        : 0000
Serial          : 0000000000000000
```

uname -a:
```
Linux DJA0230-DCA589 4.1.52 #0 SMP PREEMPT Wed May 19 10:49:31 2021 armv7l GNU/Linux
```

/etc/openwrt_release:
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r15357-0940e7a405'
DISTRIB_TARGET='brcm6xxx-tch/VBNTJ_502L07p1'
DISTRIB_ARCH='arm_cortex-a9'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r15357-0940e7a405'
DISTRIB_TAINTS='no-all glibc busybox'
```
