### ISSUE TITLE
bootstrapDNS not used for upstream DNS resolution

### ISSUE THREAD

**Issue by ivoberger** [0xERR0R/blocky#242]
I've installed blocky using docker-compose with this compose config:
```yaml
services:
  blocky:
    image: spx01/blocky:latest
    container_name: blocky
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Berlin # Optional to synchronize the log timestamp with host
    volumes:
      # config file
      - ./blocky/config.yml:/app/config.yml
      - ./blocky/whitelists/:/app/whitelists/
      - ./blocky/blacklists/:/app/blacklists/
  ```
To isolate the issue I reduced my blocky config to this:
```yaml
httpPort: 4000
bootstrapDns: 45.90.28.71
upstream:
  default:
    - tcp-tls:one.one.one.one
    - tcp-tls:dns.google
 ```
Now I get a bunch of timeout errors like follows in the console
```
[2021-08-10 13:33:31] ERROR server: error on processing request: resolution was not successful, used resolvers: 'upstream 'tcp-tls:one.one.one.one:853'' and 'upstream 'tcp-tls:dns.google:853'' errors: [dial tcp: i/o timeout dial tcp: i/o timeout]
```
The `bootstrapDns` value is for [NextDNS ](nextdns.io), just because they have a nice request log, and it shows nothing, meaning it's not being used. Upon adding some blocklists I can see requests to resolve those domains (like `raw.githubusercontent.com`) but still no requests for `one.one.one.one` or `dns.google`. So it appears that blocky is using `bootstrapDns` for the blocklists but then tries to use itself to resolve the upstream DNS servers, which of course fails. It starts working once I add `1.1.1.1` to the upstream resolvers then I can see log entries of blocky resolving `one.one.one.one` using the `1.1.1.1` upstream.

Now this was working fine earlier, it broke after using and then removing a pihole instance as the upstream server (which was running on the same machine on a different port). So I probably also broke something on my end as well (even though I don't know what, pihole was running inside docker without host network access) but in my mind the local network config shouldn't really matter to blocky since it appears to be setting the `bootstrapDns` for itself here: https://github.com/0xERR0R/blocky/blob/461a903e079210c499d6ec935f7d31ed0d1de07a/cmd/serve.go#L65-L91.
And when I set `bootstrapDns` to something invalid it fails with that error message and I can see in the debug logs that it says it's using the set `bootstrapDns`, so it's being called just fine.
Once I add an entry for `1.1.1.1 one.one.one.one` to `/etc/hosts` on the host machine is also works, further confirming that it's using `localhost` instead of `bootstrapDNS`. Tried running `docker-compose down` and then up again as well as restarting the server, didn't do anything.

Again, it broke after I set pihole on the same machine in a different container as blockys upstream to test something else, so that must have screwed my setup somehow. I'm just wondering if you have any clue as to whats happening here since it makes absolutely no sense to me.

**Comment by ivoberger** [comment]
Tried moving blocky back into the docker bridge network to isolate it from the host:
```yaml
services:
  blocky:
    image: spx01/blocky:latest
    container_name: blocky
    restart: unless-stopped
    # network_mode: host
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    environment:
      - TZ=Europe/Berlin # Optional to synchronize the log timestamp with host
    volumes:
      # config file
      - ./blocky/config.yml:/app/config.yml
      - ./blocky/whitelists/:/app/whitelists/
      - ./blocky/blacklists/:/app/blacklists/
  ```
Same issue.. My current workaround is to resolve all requests it sends to itself using standard DNS
```yaml
upstream:
  default:
    - tcp-tls:one.one.one.one
    - tcp-tls:dns.google
    - tcp-tls:dns.quad9.net
    - tcp-tls:doh.mullvad.net
    - tcp-tls:dns3.digitalcourage.de
    - tcp-tls:dns.digitale-gesellschaft.ch:853
  rpi-1.fritz.box:
    - 1.1.1.1
    - 8.8.8.8
# client mapping of IPs to rpi-1.fritz.box is further down..
 ```
