### ISSUE TITLE
reverse dns explain

### ISSUE THREAD

**Issue by e1z0** [0xERR0R/blocky#250]
Hi,

I've trying to use blocky on one of my networks, i really need reverse dns'es, it helps me identify the clients of the network and it's the nice feature of blocky. But can't understand why does it need clientLookup and why it creates bunch of errors in the log file if i've try to use upstream server of blocky itself on the clientLookup
```
clientLookup:
  upstream: udp:192.168.1.92 # blocky ip
  singleNameOrder:
      - 2
      - 1
```

So far i've got bunch of errors in the log file
```
[2021-08-23 08:10:03]  WARN query_logging_resolver: query log writer is too slow, write duration: 0 ms channel_len=501 client_ip=192.168.1.92 client_names=blocky.lan question=PTR (92.1.168.192.in-addr.arpa.)
```

My full config file is:
```
upstream:
  default:
    - udp:192.168.1.85:5053
customDNS:
  mapping:
    gw.lan: 192.168.1.1
    imac.lan: 192.168.1.2
    macbook-2015.lan: 192.168.1.4
    # ...
clientLookup:
  upstream: udp:192.168.1.92
  singleNameOrder:
      - 2
      - 1
blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - http://sysctl.org/cameleon/hosts
      - https://block.energized.pro/basic/formats/hosts
    phishing:
      - https://urlhaus.abuse.ch/downloads/hostfile/
    china_cameras:
      - blacklists/china_cameras_hosts
  clientGroupsBlock:
    default:
      - ads
      - phishing
      - china_cameras
  blockType: zeroIp
prometheus:
  enable: true
port: 53
httpPort: 4000
queryLog:
  dir: /logs
  perClient: false
  logRetentionDays: 7
```

- 192.168.1.1 - server, network gateway
- 192.168.1.85:5053 - cloudflared dns-proxy translates standard requests to https DOH
- 192.168.1.92 - blocky docker ip

It does actually work, resolves all the rdns and standard dns queries but that flood in log with:

```
[2021-08-23 08:10:03] ERROR query_logging_resolver: query log writer is too slow, log entry will be dropped client_ip=192.168.1.92 client_names=blocky.lan question=PTR (92.1.168.192.in-addr.arpa.)
[2021-08-23 08:10:03] ERROR query_logging_resolver: query log writer is too slow, log entry will be dropped client_ip=192.168.1.92 client_names=blocky.lan question=PTR (92.1.168.192.in-addr.arpa.)
[2021-08-23 08:10:03]  WARN query_logging_resolver: query log writer is too slow, write duration: 0 ms channel_len=1000 client_ip=192.168.1.92 client_names=blocky.lan question=PTR (92.1.168.192.in-addr.arpa.)
```

I've just curious what's wrong, and why it does need clientLookup when it can look and query itself for reverse and standard dns requests?

I've also tried dnsblast (burn test, dns query checker) even when it got bunch of requests at one time, it does not show any error in the log:
```
./dnsblast -s 192.168.1.92 -r 4000 -q 200 -l 60
```

Thanks in advance!

**Comment by 0xERR0R** [comment]
Hey,

clientLookup.upstream is used to determine the client name based on IP address. Typical use case: your client receives the IP address via DHCP from your router. You can use router's internal DNS server as client lookup: blocky will perform a rDNS query and router will answer with the client's hostname. In your case you use blocky itself as client lookup DNS server -> this leads in infinite look (blocky receives DNS request, tries to retrieve the client name, performs rDNS request on itself -> recieves request, tries to retrieve the client name ...).

If you don't use DHCP, you can just remove the clientLookup.upstream configuration and use static ip -> client name mapping (see https://0xerr0r.github.io/blocky/configuration/#custom-client-name-mapping)

**Comment by e1z0** [comment]
But it means i need to declare static names second time, first time

```
customDNS:
  mapping:
    gw.lan: 192.168.1.1
    imac.lan: 192.168.1.2
    macbook-2015.lan: 192.168.1.4
    # ...
```
and second time
```
clientLookup:
  singleNameOrder:
      - 2
      - 1
  clients:
      gw.lan:
         - 192.168.1.1
      imac.lan:
         - 192.168.1.2
      macbook-2015.lan:
         - 192.168.1.4
```
because reverse dns works ok in lan with customDNS entries, but in the blocky log file i see only ip addresses, when i declare second time via clientLookup > clients, it shows hostnames.
