### ISSUE TITLE
Specify upstream lookup timeout

### ISSUE THREAD

**Issue by agneevX** [0xERR0R/blocky#256]
During periods of internet connectivity loss or packet drops, avg. response times shoot up very high while webpages are stuck resolving domains.

Would be helpful if a lookup timeout could be set that times out after x seconds.

`[2021-08-30 16:44:19] ERROR server: error on processing request: resolution was not successful, used resolvers: 'upstream 'https:https://9.9.9.11:443/dns-query'' and 'upstream 'https:https://1.1.1.1:443/dns-query'' errors: [can't perform https request: Post "https://9.9.9.11:443/dns-query": context deadline exceeded (Client.Timeout exceeded while awaiting headers) can't perform https request: Post "https://1.1.1.1:443/dns-query": context deadline exceeded (Client.Timeout exceeded while awaiting headers)]`

![image](https://user-images.githubusercontent.com/19761269/131332437-3b9c39d9-5483-497e-a7e3-378a9e3e24d9.png)

```yml
# blocky.yml
httpPort: 4000
logLevel: warn

upstream:
  default:
    - https://1.1.1.1/dns-query
    - https://9.9.9.11/dns-query

caching:
  minTime: 5
  maxTime: 30
  prefetching: true
  prefetchExpires: 360
  prefetchThreshold: 2

prometheus:
  enable: true
  path: /metrics
```
