### ISSUE TITLE
udp+tcp/tcp+udp syntax doesn't seem to work in the conditional mappings section

### ISSUE THREAD

**Issue by jonchun** [0xERR0R/blocky#305]
I converted most of my config to use tcp+udp as I noticed deprecation warnings in the logs. However, I also ran into an issue trying to use that syntax under the conditional mapping section. Not sure if it's intentional or not because after reverting to the old syntax, I see the following printed in the logs
```
[2021-10-01 14:29:39]  INFO server: -> resolver: 'ConditionalUpstreamResolver'
[2021-10-01 14:29:39]  INFO server:      jchun.lan = "parallel upstreams 'default (upstream 'tcp+udp:127.0.0.1:53')'"
```

Works:
```
conditional:
  mapping:
    jchun.lan: udp:127.0.0.1
```

Doesn't Work:
```
conditional:
  mapping:
    jchun.lan: udp:127.0.0.1
```

Error:
```
[2021-10-01 14:27:56] FATAL wrong file structure: can't convert port to number (1 - 65535) strconv.ParseUint: parsing "127.0.0.1": invalid syntax
[2021-10-01 14:27:59] FATAL wrong file structure: can't convert port to number (1 - 65535) strconv.ParseUint: parsing "127.0.0.1": invalid syntax
[2021-10-01 14:28:01] FATAL wrong file structure: can't convert port to number (1 - 65535) strconv.ParseUint: parsing "127.0.0.1": invalid syntax
[2021-10-01 14:28:04] FATAL wrong file structure: can't convert port to number (1 - 65535) strconv.ParseUint: parsing "127.0.0.1": invalid syntax
[2021-10-01 14:28:07] FATAL wrong file structure: can't convert port to number (1 - 65535) strconv.ParseUint: parsing "127.0.0.1": invalid syntax
[2021-10-01 14:28:10] FATAL wrong file structure: can't convert port to number (1 - 65535) strconv.ParseUint: parsing "127.0.0.1": invalid syntax
[2021-10-01 14:28:15] FATAL wrong file structure: can't convert port to number (1 - 65535) strconv.ParseUint: parsing "127.0.0.1": invalid syntax
[2021-10-01 14:28:23] FATAL wrong file structure: can't convert port to number (1 - 65535) strconv.ParseUint: parsing "127.0.0.1": invalid syntax
[2021-10-01 14:28:38] FATAL wrong file structure: can't convert port to number (1 - 65535) strconv.ParseUint: parsing "127.0.0.1": invalid syntax
[2021-10-01 14:29:06] FATAL wrong file structure: can't convert port to number (1 - 65535) strconv.ParseUint: parsing "127.0.0.1": invalid syntax```

---

Running in docker via docker-compose
```
            "Labels": {
                "com.docker.compose.config-hash": "ebe04193e76ed55fc7cad3f5d18efda292245876c780eb5d0c7e60e27d0a081b",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "blocky",
                "com.docker.compose.project.config_files": "docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/jchun/blocky",
                "com.docker.compose.service": "blocky",
                "com.docker.compose.version": "1.29.2",
                "org.opencontainers.image.created": "2021-09-20T20:08:58.506Z",
                "org.opencontainers.image.description": "Fast and lightweight DNS proxy as ad-blocker for local network with many features",
                "org.opencontainers.image.licenses": "Apache-2.0",
                "org.opencontainers.image.revision": "97a4a2eff34c5173410aada6c46c2cebff2616ad",
                "org.opencontainers.image.source": "https://github.com/0xERR0R/blocky",
                "org.opencontainers.image.title": "blocky",
                "org.opencontainers.image.url": "https://github.com/0xERR0R/blocky",
                "org.opencontainers.image.version": "v0.16"
            }
```

**Comment by jonchun** [comment]
also... perhaps unrelated bug/feature request? setting this value to localhost basically crashes blocky because it causes a recursive loop as far as I can tell. What I WANTED to do is say "don't bother forwarding `jchun.lan` to upstream resolvers because they won't exist". (i have them setup as part of my CustomDNSResolver block). For now, I just disabled the conditional mapping and am attempting to resolve unknown `jchun.lan` queries to my upstreams. (this seems to happen with certain services that will attempt to auto-resolve random subdomains as part of a discovery protocol or something)

**Comment by 0xERR0R** [comment]
Conditional mapping configures a custom dns resolver for a domain with subdomain. I think you need a custom mapping instead

**Comment by jonchun** [comment]
> 
> 
> Conditional mapping configures a custom dns resolver for a domain with subdomain. I think you need a custom mapping instead

I do have custom mappings set up, but that's not why I attempted to do this. (and perhaps it should move into a separate issue/feature request since I only opened this issue for the fact that the udp+tcp syntax was broken for me.

For example, lets say I set up `server1.jchun.lan`, `server2.jchun.lan`, `service1.jchun.lan`. All of those resolve perfectly fine with my custom mappings. However, service1 has some sort of discovery protocol that automatically looks for `discoveryservice1.jchun.lan` even though I haven't set up custom mappings for it. In that case, I want it to just fail out rather than attempt to use my upstream resolvers because it is guaranteed to NXDOMAIN upstream.

Because my domain is `jchun.lan`,

**Comment by 0xERR0R** [comment]
Custom mapping covers also all subdomains. If you define "jchun.lan" it will automatically apply this to "xyz.jchun.lan". If there is a need to configure only one domain without subdomains, we can make a new flag in the configuration.

Conditional mapping must cover all subdomains, the use case here is to resolve some host names with a different DNS resolver (not upstreams which are used to resolve all external queries)

**Comment by 0xERR0R** [comment]
Regarding the error "wrong file structure: can't convert port to number (1 - 65535)": can you provide your config as raw json please? I can't reproduce this behaviour.

**Comment by jonchun** [comment]
I'm not using JSON and am using YML. Perhaps that is why?
```
upstream:
  # these external DNS resolvers will be used. Blocky picks 2 random resolvers from the list for each query
  # format for resolver: [net:]host:[port][/path]. net could be empty (default, shortcut for tcp+udp), tcp+udp, tcp, udp, tcp-tls or https (DoH). If port is empty, default port will be used (53 for udp and tcp, 853 for tcp-tls, 443 for https (Doh))
  # this configuration is mandatory, please define at least one external DNS resolver
  default:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  # optional: use client name (with wildcard support: * - sequence of any characters, [0-9] - range)
  # or single ip address / client subnet as CIDR notation

# optional: timeout to query the upstream resolver. Default: 2s
upstreamTimeout: 2s

# optional: custom IP address(es) for domain name (with all sub-domains). Multiple addresses must be separated by a comma
# example: query "printer.lan" or "my.printer.lan" will return 192.168.178.3
customDNS:
  mapping:
     eebox.jchun.lan: 192.168.89.2
     blocky.jchun.lan: 192.168.89.3
     mango.jchun.lan: 192.168.89.4
#    printer.lan: 192.168.178.3,2001:0db8:85a3:08d3:1319:8a2e:0370:7344

# optional: definition, which DNS resolver(s) should be used for queries to the domain (with all sub-domains). Multiple resolvers must be separated by a comma
# Example: Query client.fritz.box will ask DNS server 192.168.178.1. This is necessary for local network, to resolve clients by host name
conditional:
#  # optional: replace domain in the query with other domain before resolver lookup in the mapping
#  rewrite:
#    example.com: fritz.box
  mapping:
     test.lan: udp+tcp:127.0.0.1
#    lan.net: udp:192.168.178.1,udp:192.168.178.2

# optional: use black and white lists to block queries (for example ads, trackers, adult pages etc.)
blocking:
  # definition of blacklist groups. Can be external link (http/https) or local file
  blackLists:
    ads:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - http://sysctl.org/cameleon/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    special:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
      - /app/blacklists/blacklist.txt
  # definition of whitelist groups. Attention: if the same group has black and whitelists, whitelists will be used to disable particular blacklist entries. If a group has only whitelist entries -> this means only domains from this list are allowed, all other domains will be blocked
  whiteLists:
    special:
      - /app/whitelists/whitelist.txt
  # definition: which groups should be applied for which client
  clientGroupsBlock:
    # default will be used, if no special definition for a client name exists
    default:
      - ads
      - special
    # use client name (with wildcard support: * - sequence of any characters, [0-9] - range)
    # or single ip address / client subnet as CIDR notation
  # which response will be sent, if query is blocked:
  # zeroIp: 0.0.0.0 will be returned (default)
  # nxDomain: return NXDOMAIN as return code
  # comma separated list of destination IP addresses (for example: 192.100.100.15, 2001:0db8:85a3:08d3:1319:8a2e:0370:7344). Should contain ipv4 and ipv6 to cover all query types. Useful with running web server on this address to display the "blocked" page.
  blockType: zeroIp
  # optional: TTL for answers to blocked domains
  # default: 6h
  blockTTL: 1m
  # optional: automatically list refresh period (in duration format). Default: 4h.
  # Negative value -> deactivate automatically refresh.
  # 0 value -> use default
  refreshPeriod: 4h
  # optional: timeout for list download (each url). Default: 60s. Use large values for big lists or slow internet connections
  downloadTimeout: 4m

# optional: configuration for caching of DNS responses
caching:
  # duration how long a response must be cached (min value).
  # If <=0, use response's TTL, if >0 use this value, if TTL is smaller
  # Default: 0
  minTime: 5m
  # duration how long a response must be cached (max value).
  # If <0, do not cache responses
  # If 0, use TTL
  # If > 0, use this value, if TTL is greater
  # Default: 0
  maxTime: -1
  # Max number of cache entries (responses) to be kept in cache (soft limit). Useful on systems with limited amount of RAM.
  # Default (0): unlimited
  maxItemsCount: 0
  # if true, will preload DNS results for often used queries (default: names queried more than 5 times in a 2-hour time window)
  # this improves the response time for often used queries, but significantly increases external traffic
  # default: false
  prefetching: true
  # prefetch track time window (in duration format)
  # default: 120
  prefetchExpires: 2h
  # name queries threshold for prefetch
  # default: 5
  prefetchThreshold: 5
  # Max number of domains to be kept in cache for prefetching (soft limit). Useful on systems with limited amount of RAM.
  # Default (0): unlimited
  prefetchMaxItemsCount: 0

# optional: configuration for prometheus metrics endpoint
prometheus:
  # enabled if true
  enable: true
  # url path, optional (default '/metrics')
  path: /metrics

# optional: write query information (question, answer, client, duration etc.) to daily csv file
queryLog:
  # optional one of: mysql, csv, csv-client. If empty, log to console
  type: csv
  # directory (should be mounted as volume in docker) for csv, db connection string for mysql
  target: /app/logs
  #target: db_user:db_password@tcp(db_host_or_ip:3306)/db_user?charset=utf8mb4&parseTime=True&loc=Local
  # if > 0, deletes log files which are older than ... days
  logRetentionDays: 7

# optional: DNS listener port and bind ip address, default 53 (UDP and TCP). Example: 53, :53, 127.0.0.1:53
port: 53
# optional: HTTPS listener port and bind ip address, default empty = no http listener. If > 0, will be used for prometheus metrics, pprof, REST API, DoH... Example: 443, :443, 127.0.0.1:443
httpPort: 4000
#httpsPort: 443
# mandatory, if https port > 0: path to cert and key file for SSL encryption
#httpsCertFile: server.crt
#httpsKeyFile: server.key
# optional: use this DNS server to resolve blacklist urls and upstream DNS servers. Useful if no DNS resolver is configured and blocky needs to resolve a host name. Format net:IP:port, net must be udp or tcp
bootstrapDns: tcp+udp:1.1.1.1
# optional: Drop all AAAA query if set to true. Default: false
disableIPv6: false
# optional: Log level (one from debug, info, warn, error). Default: info
logLevel: info
# optional: Log format (text or json). Default: text
logFormat: text
# optional: log timestamps. Default: true
logTimestamp: true
# optional: obfuscate log output (replace all alphanumeric characters with *) for user sensitive data like request domains or responses to increase privacy. Default: false
logPrivacy: false
```
