### ISSUE TITLE
Conditional DNS resolution for nested subdomains

### ISSUE THREAD

**Issue by BeeHiveJava** [0xERR0R/blocky#328]
Is there any way to use conditional dns resolution for nested subdomains? For example, in this scenario:
```yaml
conditional:
  mapping:
    test.example: tcp+udp:10.10.10.10
```

I would not only like to be able to resolve `*.test.example`, but also `*.*.test.example`. After doing some tests with `dig`, this does not seem to be the case currently. Is there any way to enable this kind of behaviour?

My use case is having blocky forward requests to CoreDNS running inside a kubernetes cluster. By default services in CoreDNS will resolve using `<service-name>.<service-namespace>.svc.cluster.local`. Defining a configuration like this in Blocky would be spectacular:
```yaml
conditional:
  rewrite:
    svc1.test.example: test-svc1.test-ns1.svc.cluster.local
    svc2.test.example: test-svc2.test-ns2.svc.cluster.local
  mapping:
    svc.cluster.local: tcp+udp:10.10.10.10 # IP of CoreDNS
```

**Comment by 0xERR0R** [comment]
Hey,

The key of rewrite will match only subdomains, so this should work:

```yaml
conditional:
  rewrite:
    test.example: test-ns1.svc.cluster.local
  mapping:
    svc.cluster.local: tcp+udp:10.10.10.10
```

this will translate "svc1.test.example" to "svc1.test-ns1.svc.cluster.local" and perform a DNS request against 10.10.10.10.
