### ISSUE TITLE
Blocky returning response for domain in blacklisted group

### ISSUE THREAD

**Issue by Matthew-Beckett** [0xERR0R/blocky#335]
I've imported a DNS name list into Blockly but when using nslookup to attempt to resolve I get a response when I expect NXDOMAIN.

## Domain List Import Log
<html>
<body>

2021-11-10 14:34:46 | {"level":"info","link":"https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/v4_validation_domains.txt","msg":"starting download","prefix":"list_cache","time":"2021-11-10T14:34:46Z"}
-- | --
2021-11-10 14:34:46 | {"level":"info","link":"https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/v3_domains.txt","msg":"starting download","prefix":"list_cache","time":"2021-11-10T14:34:46Z"}
2021-11-10 14:34:46 | {"level":"info","link":"https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/v2_domains.txt","msg":"starting download","prefix":"list_cache","time":"2021-11-10T14:34:46Z"}
2021-11-10 14:34:46 | {"level":"info","link":"https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/v4_domains.txt","msg":"starting download","prefix":"list_cache","time":"2021-11-10T14:34:46Z"}
2021-11-10 14:34:46 | {"count":26,"level":"info","msg":"file imported","prefix":"list_cache","source":"https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/v4_validation_domains.txt","time":"2021-11-10T14:34:46Z"}
2021-11-10 14:34:46 | {"count":610,"level":"info","msg":"file imported","prefix":"list_cache","source":"https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/v3_domains.txt","time":"2021-11-10T14:34:46Z"}
2021-11-10 14:34:46 | {"count":96,"level":"info","msg":"file imported","prefix":"list_cache","source":"https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/v2_domains.txt","time":"2021-11-10T14:34:46Z"}
2021-11-10 14:34:47 | {"count":688,"level":"info","msg":"file imported","prefix":"list_cache","source":"https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/v4_domains.txt","time":"2021-11-10T14:34:47Z"}
2021-11-10 14:34:47 | {"group":"pegasus","level":"info","msg":"group import finished","prefix":"list_cache","time":"2021-11-10T14:34:47Z","total_count":1407}

</body>
</html>

## Configuration

```
blocking:
  # definition of blacklist groups. Can be external link (http/https) or local file
  blackLists:
    ads:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://mirror1.malwaredomains.com/files/justdomains
      - http://sysctl.org/cameleon/hosts
      - https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
    pegasus:
      - https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/v4_domains.txt
      - https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/v3_domains.txt
      - https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/v2_domains.txt
      - https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/v4_validation_domains.txt
    tracking:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    special:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts

```
## NSLOOKUP Output
```
> accountcanceled.com
Server:  UnKnown
Address:  ***.***.***.***

Non-authoritative answer:
Name:    accountcanceled.com
Address:  75.2.37.224
```
