### ISSUE TITLE
Blocking error

### ISSUE THREAD

**Issue by asterriya** [0xERR0R/blocky#345]
I want to block whole domain .io and .cn with regex support on config, but it doesn't work for me. Seems like I did something wrong on config, but it was copied from example config. Can you please provide right config for the blocking section to make it work?

P.S adding .io and .cn into blacklist.txt doesn't help me at all. And I'm using v0.17

**Comment by 0xERR0R** [comment]
I can't test the config right now, but from the top of my head, it should look like this:

```yaml
upstream:
  externalResolvers:
    - 1.1.1.1
    - 9.9.9.9
blocking:
  blackLists:
    ads:
      - |
        /^.*\.io$/
        /^.*\.cn$/
  clientGroupsBlock:
    default:
      - ads
port: 53
httpPort: 4000
logLevel: info
```

The regex must be enclosed by `/`

Btw. You can test regex with this tool: https://regoio.herokuapp.com/
