### ISSUE TITLE
config issue

### ISSUE THREAD

**Issue by jr0dd** [0xERR0R/blocky#352]
I am having issues with the v0.17 image.  I get `FATAL wrong file structure: wrong host name ''`. Changing the loglevel provides no additional output. When I roll back to v0.16 everything works fine. I've been digging through the source to see if something has changed, but nothing is sticking out. Below is my full config.

```
upstream:
  default:
    - tcp-tls://1.1.1.1
    - tcp-tls://1.0.0.1
conditional:
  mapping:
    domain.tld: tcp+udp:10.10.2.2
clientLookup:
  upstream: tcp+udp:10.10.0.1
blocking:
  blackLists:
    ads:
      - https://dbl.oisd.nl
    fakenews:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
  whiteLists:
    ads:
      - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
  clientGroupsBlock:
    default:
      - ads
      - fakenews
prometheus:
  enable: true
  path: /metrics
httpPort: 4000
logLevel: info
```
