### ISSUE TITLE
Upstream resolver with a particular network interface

### ISSUE THREAD

**Issue by compliment** [0xERR0R/blocky#357]
Something like 1.1.1.1@eth0 and 1.1.1.1@eth1

**Comment by agneevX** [comment]
Sounds like you want to bind blocky to a specific network interface? Are you running it in a container? 

If so, it should be fairly easy to do that. Here's a docker-compose example:

```yml
services:
  blocky:
    image: spx01/blocky
    ports:
      - 10.0.0.2:53:53/udp # eth0
      - 192.168.1.2:53:53/udp # eth1
```
