### ISSUE TITLE
Print / export blackList(s)

### ISSUE THREAD

**Issue by rain0r** [0xERR0R/blocky#358]
It would be great if blocky could display (or export) all currently loaded domains that are blacklisted.

**Comment by 0xERR0R** [comment]
It would be technically possible, but it could be very huge amount of entries in the cache (for example I have 325K). That means, if we provide a REST API, there must be some paging.

What is your use case for display/export?

**Comment by kwitsch** [comment]
I started developing a [container](https://github.com/kwitsch/docker-adblocklists) a while ago(isn't officially released jet) which might be useful for your purpose.
It aggregates block and allow lists and serves them as http endpoints.
The endpoints deliver text feedback and can be called with a browser or curl. 
(As already mentioned calling the endpoint takes some time.)

example docker-compose:

```
version: "3.8"

services:
  adblocklists:
    image: kwitsch/adblocklists:dev
    environment:
      - ABL_REFRESH=90m
      - ABL_RESOLVER_STARTUP=1m
      - ABL_BLOCK_LISTS_0=https://block-list1.com/example.txt
      - ABL_BLOCK_LISTS_1=https://block-list2.com/example.txt
      - ABL_ALLOW_LISTS_0=https://allow-list1.com/example.txt
      - ABL_ALLOW_ENTRIES_0=custom.entry.com
  blocky:
    image: spx01/blocky
    ports:
      - "53:5333/tcp"
      - "53:5333/udp"
    volumes:
      - ./config.yml:/app/config.yml:ro
```

blocky config snippet:

```
blocking:
  clientGroupsBlock:
    default:
      - ads
  blackLists:
    ads:
      - http://adblocklists/blocklist
  whiteLists:
    ads:
      - http://adblocklists/allowlist
```
