### ISSUE TITLE
Support Docker label based configuration

### ISSUE THREAD

**Issue by agneevX** [0xERR0R/blocky#375]
Traefik supports specifying configuration within the docker-compose file.

```yml
pilot:
  token: test

# compose.yml
traefik:
  image: traefik
  labels:
    traefik.pilot.token: test
```

This would be great for blocky and would eliminate the need for maintaining a separate config file.

**Comment by 0xERR0R** [comment]
AFAIK it works only if traefik has access to docker daemon (and this is always a security risk). If not, there is no possibility to read labels inside the container. We can introduce environment variables for configuration, but it looks ugly for lists (e.g. for blocking list urls or custom blocking lists)

**Comment by kwitsch** [comment]
Agreed that the label based solution might be overkill for blocky.

But I would love an environment based configuration.
The blocky config is currently the only config file in my DNS stack. Everything else is configured though environment.

For other projects I use koanf to achieve this. There is an option to define conversion functions. With that it might be possible to convert map[int]string to []string. This would enable environment variables like BLOCKY_BLACKLISTS_ADS_1 for example.

**Comment by 0xERR0R** [comment]
koanf looks nice, I'll take a look on it. We need something, which can read yaml and env (env should has precedence over yaml) with custom parsing functionality. Really cool would be a lib which can also set default values with tags and generate documentation.

**Comment by kwitsch** [comment]
Koanf can read yaml & env(and some more).
I personally often use a combination of defaults & koanf.[helper lib](https://github.com/kwitsch/go-dockerutils/blob/d06b384a739f9eb5bf825f5a923882c05dc84a10/config/config.go)
Haven't seen something for documentation jet.

**Comment by agneevX** [comment]
> AFAIK it works only if traefik has access to docker daemon

Sorry, I had absolutely no idea.

> This would enable environment variables like BLOCKY_BLACKLISTS_ADS_1 for example.

This is a good alternative.

**Comment by kwitsch** [comment]
Slices in the same variable in a CSV notation should work out of the box.
Further are maps supported.
I try to prevent using variables with multiple values(slices) by using maps and convert them later. There is probably a better option, didn't investigate much as my focus was on other things.
Example usage with maps: [TinyMacDns config](https://github.com/kwitsch/TinyMacDns/blob/main/src/config/config.go)

**Comment by kwitsch** [comment]
Using a map[int]string the env config would look like:
- BLOCKY_UPSTREAM_DEFAULT_0=5.9.164.112
- BLOCKY_UPSTREAM_DEFAULT_1=1.1.1.1

**Comment by agneevX** [comment]
What if this was specified in `command`?

```yml
logLevel: error

upstream:
  default:
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
```

```yml
services:
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    command:
      - --log.level=error
      - --upstream.default=https://8.8.8.8/dns-query
      - --upstream.default=https://8.8.4.4/dns-query
```

**Comment by kwitsch** [comment]
Wouldn't really make a difference and env variables are more common.  
The effort to rebuild the config stays more or less the same.  
I started converting it to koanf(which supports both env & parameter) a while ago but ran out of free time.

**Comment by 0xERR0R** [comment]
I tried to implement env based config with koanf and there were some "challenges":
* currently, we use yaml package to conver yaml to structs. There is a lot of conversion logic (for example to create upstreams with validation), this must be rewritten for koanf.
* we have some logic to handle config changes. For example, we changed a single string property to an array of strings and implemented a conversion function which allows to use the old and a new variant.
* we have "complicated" configuration with nested maps of maps and yaml literal block scalars / special characters, for example:

```yaml
blocking:
  blackLists:
    ads:
      - |
        # inline definition with YAML literal block scalar style
        # hosts format
        someadsdomain.com
  clientGroupsBlock:
    default:
      - ads
    # use client name (with wildcard support: * - sequence of any characters, [0-9] - range)
    # or single ip address / client subnet as CIDR notation
    laptop*:
      - ads
```
koanf has no support for nested maps -> this must be (somehow) implemented. Also we need a "special" logic to handle inline list definitions...

**Comment by agneevX** [comment]
> Wouldn't really make a difference and env variables are more common.

I feel that this is not a correct way of providing configuration at runtime and is a potential misuse of environment variables.

**Comment by kwitsch** [comment]
> I feel that this is not a correct way of providing configuration at runtime and is a potential misuse of environment variables.

As far as i know it's the most common way to store configurations inside containers.
Config files have to be stored in volumes or distrubted through "docker config".
Volumes are locally stored which is quite troublesome in swarm environments and docker configs are read only thus every change has to be a seperate file.

Environment variables(and command arguments) can be updated through the swarm manager and are therefore a lot easier to maintain/update.

**Comment by kwitsch** [comment]
> koanf has no support for nested maps -> this must be (somehow) implemented. Also we need a "special" logic to handle inline list definitions...

Nested maps aren't really a problem but slices are. 😕
My last attempt include a separate koanf config struct(with maps instead of slices) that would have been converted to the old config struct afterwards.
This would produce a little overhead but ensure full backward compatibility.

Currently this feature has a low priority for me as there are some other tasks I like to solve first. 😅

**Comment by 0xERR0R** [comment]
> 
> As far as i know it's the most common way to store configurations inside containers. 

I agree with @kwitsch: env variables are the "recommended" way for containerized applications (see for example [12 factor app](https://12factor.net/config)

In k8s it is already possible to provide the yaml configuration as a config map -> in this case it is possible to put all descriptors and configurations in one file.

Only with docker-compose there is a need to maintain 2 files. Maybe we can allow to define the whole config as one variable, something like this (didn't try it, but it is a valid docker compose file, I think it will work):

```yaml
version: "2.1"
services:
  ubuntu:
    image: spx01/blocky
    environment:
      BLOCKY_CONFIG: |-
        upstream:
          default:
            - 5.9.164.112
```

Alternatively, it also possible to use something like this project: https://github.com/arribada/EnvToFile
