### ISSUE TITLE
CNAME Support?

### ISSUE THREAD

**Issue by SlothCroissant** [0xERR0R/blocky#411]
Hey there, loving Blocky so far! I've got a quick question that I'm hoping is just due to me missing something simple: Does blocky support manual CNAMEs to internal hosts?

Use case: I host a webserver on `webserver.lan`. This web server hosts several sites externally to the public internet - let's say `app1.web.url`, `app2.web.url`, `app3.web.url`. With my current PiHole setup, I use the underlying `dnsmasq` config options for CNAME mapping:

```
--cname=<cname>,[<cname>,]<target>[,<TTL>]
Return a CNAME record which indicates that <cname> is really <target>. There is a significant limitation on the target; it must be a DNS record which is known to dnsmasq and NOT a DNS record which comes from an upstream server. The cname must be unique, but it is permissible to have more than one cname pointing to the same target. Indeed it's possible to declare multiple cnames to a target in a single line, like so: --cname=cname1,cname2,target
If the time-to-live is given, it overrides the default, which is zero or the value of --local-ttl. The value is a positive integer and gives the time-to-live in seconds.
```

### Ask 
Does blocky support manual CNAMEs to internal hosts?

## What I've tried
First off, I tried just using the `customDNS.mapping` [YAML configuration (doc ref)](https://0xerr0r.github.io/blocky/configuration/#custom-dns) to try to add `webserver.lan` as the target for my FQDNS as so:

``` yaml
customDNS:
  mapping:
    webserver.lan: 10.1.0.10
    app1.url.com: webserver.lan
    app2.url.com: webserver.lan
    app3.url.com: webserver.lan
```

This config throws an error on startup which makes sense: `FATAL wrong file structure: invalid IP address 'webserver.lan'`

---
Next, I tried `conditional.rewrite` [YAML configuration (doc ref)](https://0xerr0r.github.io/blocky/configuration/#conditional-dns-resolution) to remap my app*.url.com URLs to `webserver.lan` as so:

``` yaml
customDNS:
  mapping:
    webserver.lan: 10.1.0.10
conditional:
  rewrite:
    app1.url.com: webserver.lan
    app2.url.com: webserver.lan
    app3.url.com: webserver.lan
```

This config loads, but when I query `app1.url.com`, it tosses it upstream and fails (as I assume it rewrites it to webserver.lan and fails Cloudflare's resolver):

```
INFO queryLog: query resolved answer= client_ip=10.1.10.100 client_names=10.1.10.100 duration_ms=99 question=A (app1.url.com.) response_code=NXDOMAIN response_reason=RESOLVED (https://1.0.0.1:443/dns-query)
```

Any guidance you could provide? Or is this not currently possible at this point? Thanks!

**Comment by kwitsch** [comment]
Had a similar problem a while back and figured that a conditional block without a mapping (rewrite only) is ignored somehow.
Try adding a mapping "lan: 127.0.0.1" to your conditional block.
This way blocky queries itself for all hosts in the lan domain and your custom mapping should work correctly.

**Comment by 0xERR0R** [comment]
CustomDNS creates only A and AAAA entries -> you can only map a custom url (with all subdomains) to the particular IP address.

Conditional mapping redirects some queries to the defined DNS resolver.

I think in your use case you can try to define customDNS mapping either for each app url like:

```yaml
customDNS:
  mapping:
    app1.url.com: 10.1.0.10
    app2.url.com: 10.1.0.10
    app3.url.com: 10.1.0.10
```

or for the whole domain (in this case for all subdomains: *.url.com):

```yaml
customDNS:
  mapping:
    url.com: 10.1.0.10
```
