### ISSUE TITLE
Whitelist problems?

### ISSUE THREAD

**Issue by parasit** [0xERR0R/blocky#426]
Hi,
I have installed blocky (blocky_0.17_Linux_armv7) in local network on my Raspberry PI (192.168.1.38). 
Blocking works very well, only sometimes even too well ...
I tried add some entries to whiteList, but looks like they are ignored. 
The question is, is this a configuration problem or something else?

Eg. for almost all reddit links from email, browser returns error `DNS_PROBE_FINISHED_NXDOMAIN`
Same result fom nslookup:
```
> nslookup click.redditmail.com
Server:  UnKnown
Address:  192.168.1.38

Non-authoritative answer:
Name:    click.redditmail.com
Address:  0.0.0.0

> nslookup click.redditmail.com 8.8.8.8
Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
Name:    thirdparty.bnc.lt
Addresses:  54.215.151.87
          13.57.159.75
Aliases:  click.redditmail.com
```

Below my blocky config
```
❯ cat config.yml
upstream:
  default:
    - 46.182.19.48
    - 80.241.218.68
    - tcp-tls:fdns1.dismail.de:853
    - https://dns.digitale-gesellschaft.ch/dns-query
blocking:
  whiteLists:
    ads:
      - |
        /reddit/
        /orbitfiles/
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://abp.oisd.nl/
      - https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
  clientGroupsBlock:
    default:
      - ads
port: 53
httpPort: 4000
prometheus:
  enable: true
```

P.S. I try also with whitelist from file, but with same result.
