### ISSUE TITLE
BlockingResolver deactivated

### ISSUE THREAD

**Issue by dbainbridge** [0xERR0R/blocky#433]
Why would the BlockingResolver be getting deactivated on startup?

My config looks like:

```
upstream:
  default:
    - 1.1.1.1
    - 1.0.0.1
blocking:
  blackLists:
    ads:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    special:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts

```

Using latest code in master.
