### ISSUE TITLE
Installed, but isn't blocking ads

### ISSUE THREAD

**Issue by sgebr01** [0xERR0R/blocky#434]
I've installed it as a standalone binary, but I'm still getting ads. I'm guessing I haven't installed it correctly. All I did was copy and paste the simple configuration file from the Installation page in the documentation(found here - https://0xerr0r.github.io/blocky/installation/) into a config.yaml file and then I ran the code in cmd prompt after changing the directory to where the blocky.exe file was. I know that I did the cmd prompt correctly since I saw some settings for Blocky, but I'm guessing that my config file was incorrect. I tried it on YouTube and Forbes, both still showed ads.

**Comment by 0xERR0R** [comment]
Hi, can you share you config please? How did you try it? Did you changed the DNS server on your machine?

btw. you can't block youtube ads with blocky/pi-hole/adguard home. But it will work for other ads (banner)

**Comment by sgebr01** [comment]
The config I used was this one, found in the installation page -
```
 upstream:
  default:
    - 46.182.19.48
    - 80.241.218.68
    - tcp-tls:fdns1.dismail.de:853
    - https://dns.digitale-gesellschaft.ch/dns-query
blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  clientGroupsBlock:
    default:
      - ads
port: 53
httpPort: 4000
```
I'm not sure if this is correct or not? Is there something I should customize about it, since I just got it from the website and changed no part of it.
