### ISSUE TITLE
Error, downloading a block list.

### ISSUE THREAD

**Issue by erenard** [0xERR0R/blocky#435]
Hello, It's been a week I'm using blocky and I'm very happy so far.
I'm encountering the following issue:
When adding a blocking blacklist like this:
```yml
blocking:
  downloadTimeout: 4m
  downloadAttempts: 5
  downloadCooldown: 10s
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    nvidia:
      - |
        androidtvwatsonfe-pa.googleapis.com
```
I get the following errors at startup :
```
blocky    | [2022-02-20 14:56:37]  INFO list_cache: starting download link=https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
blocky    | [2022-02-20 14:56:42]  WARN list_cache: Temporary network err / Timeout occurred, retrying... Get "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts": dial tcp: i/o timeout attempt=1 link=https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

-- ATTEMPT 2 to 5 removed for brevity --

blocky    | [2022-02-20 14:57:52]  WARN list_cache: err during file processing: Get "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts": dial tcp: i/o timeout
blocky    | [2022-02-20 14:57:52]  WARN list_cache: Populating group cache failed for group ads
blocky    | [2022-02-20 14:57:52]  INFO list_cache: file imported count=1 source=androidtvwatsonfe-pa.googleapis.com
blocky    | 
blocky    | [2022-02-20 14:57:52]  INFO list_cache: group import finished group=nvidia total_count=1
```
As you can see, `blocky` seems unable to make a download, that's why I tried the following command:
`docker exec blocky wget https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts`
returns:
```
Connecting to raw.githubusercontent.com (185.199.110.133:443)
saving to 'hosts'
hosts                100% |********************************| 3072k  0:00:00 ETA
'hosts' saved
```
So it seems `wget` can do it in the `blocky`'s container.
I might add that I run the container on a Synology NAS, not sure if relevant here.

**Comment by erenard** [comment]
Another error that might be relevant:
`docker exec blocky ./blocky blocking status` returns:
```
[2022-02-20 15:20:57] FATAL can't executeGet "http://localhost:4000/api/blocking/status": dial tcp 127.0.0.1:4000: connect: connection refused
```

**Comment by 0xERR0R** [comment]
Can you provide your configuration file please? Did you set bootstrapdns parameter?

**Comment by quantic-cloud** [comment]
It's my first time running this container. I also got the same error when loading the lists.

`blocky    | [2022-02-21 06:40:49]  WARN list_cache: Temporary network err / Timeout occurred, retrying`

Commenting the line `bootstrapDns: tcp:1.1.1.1` in the config file fixed the error. Thanks for pointing in that direction. I'll keep experimenting.

**Comment by erenard** [comment]
Hello, here the full `config.yml` file:
```
upstream:
  default:
    # opendns
    - 208.67.222.222
    - 208.67.220.220
    # adguard unfiltered
    - 94.140.14.140
    - 94.140.14.141
upstreamTimeout: 5s
customDNS:
  mapping:
    my_home_nas.synology.me: 192.168.1.2
blocking:
  downloadTimeout: 4m
  downloadAttempts: 5
  downloadCooldown: 10s
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    nvidia:
      - |
        androidtvwatsonfe-pa.googleapis.com
```
The `Temporary network err / Timeout occurred` occur almost immediately, it doesn't take `4m` at all.
