### ISSUE TITLE
Let's make Blocky more flexible

### ISSUE THREAD

**Issue by ThinkChaos** [0xERR0R/blocky#476]
While working on #449 and #475, I touched the resolver chaining and adding resolver nesting. This has got me thinking it would be nice to be able to configure arbitrary resolver chains, or rather trees, in the config.
This means making `createQueryResolver` in server.go configuration driven.

I haven't done any code work on this, but have been thinking about it for a while and think I have a decent vision for an implementation.

Here's an example of what I mean by configuration driven,
Please don't pay too much attention to the syntax and names, it's nothing concrete, just a draft to explain what I'm thinking.
```yaml
resolvers:
- log:
- metrics:
- rewrite:
    rules: [...]
    resolvers:
    - hostsFile:
    - cache:
    - customDNS:
      mapping: [...]
    - conditional:
        home: <router ip>
    - parallel:
      upstreams: [...]
```

This would make blocky much more flexible, and, I think, easy to understand without looking at `createQueryResolver`.
My main confusion source while using blocky has been the order in which resolvers run. Having the user decide would help alleviate that IMO.

What do you think of this idea?

P.S. please do not take this as me not liking blocky. On the contrary, I really enjoy using it, and want to help build it into something even greater!

EDIT: sorry accidentally pressed Ctrl-Enter. Filled out the rest!
