### ISSUE TITLE
MySQL Dashboard not working

### ISSUE THREAD

**Issue by devius** [0xERR0R/blocky#493]
This is what I get when running dashboard on Grafana

1055: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'blocky-resolv-1.t.request_ts' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"

**Comment by 0xERR0R** [comment]
It looks like "ONLY_FULL_GROUP_BY" is set by default in MySQL but not in MariaDB

**Comment by panks21** [comment]
I am facing the same issue... I have limited knowledge with databases

following is my config

```
queryLog:
  # optional one of: mysql, postgresql, csv, csv-client. If empty, log to console
  type: mysql
  target: blocky:blocky@tcp(192.168.155.245:33306)/blocky?charset=utf8mb4&parseTime=True&loc=Local
  # if > 0, deletes log files which are older than ... days
  logRetentionDays: 7
  creationAttempts: 3
  creationCooldown: 5s
```


docker-compose for mysql is as below. 

```
version: '2'
services:
  blocky_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: unless-stopped
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: blocky
      MYSQL_DATABASE: blocky
      MYSQL_USER: blocky
      MYSQL_PASSWORD: blocky
```
