### ISSUE TITLE
example doc min/max time

### ISSUE THREAD

**Issue by 24fpsDaVinci** [0xERR0R/blocky#527]
https://github.com/0xERR0R/blocky/blob/development/docs/config.yml#L115
```
# optional: configuration for caching of DNS responses
caching:
  # duration how long a response must be cached (min value).
  # If <=0, use response's TTL, if >0 use this value, if TTL is smaller
  # Default: 0
  minTime: 5m
  # duration how long a response must be cached (max value).
  # If <0, do not cache responses
  # If 0, use TTL
  # If > 0, use this value, if TTL is greater
  # Default: 0
  maxTime: -1

```
in the example config the minTime is 5m, the maxTime is -1
why is maxTime -1, as in do not cache responses?
