### ISSUE TITLE
Running on windows docker?

### ISSUE THREAD

**Issue by swiftaes** [0xERR0R/blocky#53]
I'm trying to run this on windows docker but when I inser the path to the config file i get loads of errors any help or does this not work on windows?

**Comment by 0xERR0R** [comment]
This should run on windows. You can use either docker-compose or plain docker:
```
docker run  --name blocky -p "53:53/udp" -v c:\temp\config.yml:/app/config.yml spx01/blocky
```
Put following config.yml to c:\temp\config.yml

```yaml
upstream:
    externalResolvers:
      - udp:46.182.19.48
      - udp:80.241.218.68
blocking:
    blackLists:
      ads:
        - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
        - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
        - https://mirror1.malwaredomains.com/files/justdomains
        - http://sysctl.org/cameleon/hosts
    clientGroupsBlock:
      default:
        - ads
```

and run in cmd.exe `nslookup -q=a google.com 127.0.0.1`, this will run a DNS query agains local running blocky (in docker)
