### ISSUE TITLE
feature: passing client name to upstream server

### ISSUE THREAD

**Issue by sweepyoface** [0xERR0R/blocky#538]
I'm using Blocky as a proxy to [NextDNS](https://nextdns.io/) for its web UI management and analytics visualization. I have configured clients to connect directly over DoH where possible, but for other devices I'd like to have Blocky forward the resolved client name (via rDNS) to the upstream. 

For example, NextDNS expects it in the format of
`https://dns.nextdns.io/<config_id>/<client_name>` for DoH
`<client_name>-<config_id>.dns.nextdns.io` for DoT

I imagine the most reasonable way of doing this for wide compatibility would be a special placeholder in the upstream URL, like so:
```yaml
upstream:
  default:
    - https://dns.nextdns.io/foo/${client_name}
    - ${client_name}-foo.dns.nextdns.io
```
