### ISSUE TITLE
Error server i/o timeout

### ISSUE THREAD

**Issue by travisboss** [0xERR0R/blocky#552]
`ERROR server: error on processing request: read udp 172.18.0.2:45185->10.0.2.253:53: i/o timeout`

Get a host of errors like this, only happens when I redirect my DNS to blocky which is hosted in a docker container on a rpi 3b+.

Here is my compose file:

```
version: "2.1"
services:
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000"
    environment:
      - TZ=America/Chicago
    volumes:
      - ./config.yml:/app/config.yml
``` 

Here is my config:

```
upstream:
  default:
    - 10.0.2.253
blocking:
  blackLists:
    ads:
      - https://dbl.oisd.nl/
    iot:
      - https://dbl.oisd.nl/extra/
    nsfw:
      - https://dbl.oisd.nl/nsfw/
    doh:
      - https://raw.githubusercontent.com/oneoffdallas/dohservers/master/list.txt
      - https://raw.githubusercontent.com/oneoffdallas/dohservers/master/listv6.txt
  clientGroupsBlock:
    default:
      - ads
      - doh
    secret/23:
      - ads
      - iot
      - nsfw
      - doh
    secret/23:
      - ads
      - iot
      - nsfw
      - doh
  refreshPeriod: 24h

caching:
  minTime: -1
  cacheTimeNegative: -1

port: 53
```

My reasonf or negative cache is I am just having unbound do all the caching on my pfsense instance and handling all the prefetch.
