### ISSUE TITLE
Filter loopback addresses from hosts file

### ISSUE THREAD

**Issue by ioqy** [0xERR0R/blocky#633]
I have the hostname of my server with the loopback address `127.0.1.1` in my hosts file (which was added by Docker I think) and `127.0.1.1` is one of the addresses returned by blocky when resolving the name of the server.

Blocky does also return the other address of the server and the connection to the server somehow works, but it might be a problem for some devices/applications and the loopback addresses should probably be filtered by blocky when reading the hosts file.

Content of /etc/hosts:
```
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       example.com

192.168.178.2             example.com
fe80::c44a:3704:3be3:3320 example.com
```
The first 4 lines probably come from the OS, the 5th line is probably from Docker and the last 2 where added by me.

Output of `nslookup example.com`:
```
Server:  fritz.box
Address:  :::::fafb

Non-authoritative answer:
Name:    example.com
Addresses:  fe80::c44a:3704:3be3:3320
          127.0.1.1
          192.168.178.2
```

**Comment by kwitsch** [comment]
I tried to replicate the behavior with my docker environment but don't get the `127.0.1.1       example.com` entry. 

Could you share an example compose file where it occures?

**Comment by ioqy** [comment]
```YAML
version: "2.1"
services:
  blocky:
    image: spx01/blocky
    container_name: blocky
    user: 1000:1000
    environment:
      - TZ=Europe/Amsterdam # Optional to synchronize the log timestamp with host
    volumes:
      - /etc/docker-services/blocky/blocky-config.yml:/app/config.yml
      - /var/local/docker-services/blocky/log:/log
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    network_mode: "host"
    healthcheck:
      disable: true
    restart: unless-stopped

```
