### ISSUE TITLE
development version start is very slow 

### ISSUE THREAD

**Issue by bboysoulcn** [0xERR0R/blocky#664]

**Comment by kwitsch** [comment]
Could you provide additional information like cpu architecture, do you run it in dock/kubernetes and if possible an example configuration file?

**Comment by bboysoulcn** [comment]
docker 
amd64

```yaml
upstream:
  default:
    - 223.5.5.5
    - 114.114.114.114
bootstrapDns: 223.5.5.5
upstreamTimeout: 2s
customDNS:
  mapping:
    redis.aaa.cn: 10.10.100.1
conditional:
  mapping:
    feedly.com: https://dns.xxx.cn/dns-query


port: 53
httpPort: 4000
logLevel: info
logFormat: json
logTimestamp: true
caching:
  minTime: 6h
  maxTime: 12h
  prefetching: true
  maxItemsCount: 0
redis:
  address: 10.10.100.20:6379
  password: zzzpasss
  database: 2
  required: true
  connectionAttempts: 10
  connectionCooldown: 3s
prometheus:
  enable: true
  path: /metrics
filtering:
  queryTypes:
    - AAAA
queryLog:
  type: csv
  target: /app/logs
  logRetentionDays: 7
```



just like this

**Comment by bboysoulcn** [comment]
may be the problem here

```yaml
conditional:
  mapping:
    feedly.com: https://dns.xxxx.cn/dns-query
    feedly.com: https://dns.xxxx.cn/dns-query
    feedly.com: https://dns.xxxx.cn/dns-query
    feedly.com: https://dns.xxxx.cn/dns-query
```
