### ISSUE TITLE
Docker container won't start since version v0.19

### ISSUE THREAD

**Issue by robinvalk** [0xERR0R/blocky#678]
I have a problem upgrading to version v0.19. It fails with the following error:
```
blocky    | Error: can't start server: 1 error occurred:
blocky    | 	* parallel resolver:  lookup anycast.uncensoreddns.org: i/o timeout
```

With v0.18 I initially get timeouts as well, but after 20 seconds they disappear and the queries are being resolved successfully:
```
blocky    | [2022-10-13 12:48:15]  INFO server: TCP server is up and running on address :53
blocky    | [2022-10-13 12:48:25] ERROR server: error on processing request: can't perform https request: Post "https://anycast.uncensoreddns.org:443/dns-query": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
blocky    | [2022-10-13 12:48:25] ERROR server: error on processing request: can't perform https request: Post "https://anycast.uncensoreddns.org:443/dns-query": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
blocky    | [2022-10-13 12:48:25] ERROR server: error on processing request: can't perform https request: Post "https://anycast.uncensoreddns.org:443/dns-query": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
blocky    | [2022-10-13 12:48:29] ERROR server: error on processing request: can't perform https request: Post "https://anycast.uncensoreddns.org:443/dns-query": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
blocky    | [2022-10-13 12:48:29] ERROR server: error on processing request: can't perform https request: Post "https://anycast.uncensoreddns.org:443/dns-query": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
blocky    | [2022-10-13 12:48:34] ERROR server: error on processing request: can't perform https request: Post "https://anycast.uncensoreddns.org:443/dns-query": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
blocky    | [2022-10-13 12:48:34] ERROR server: error on processing request: can't perform https request: Post "https://anycast.uncensoreddns.org:443/dns-query": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
blocky    | [2022-10-13 12:48:38] ERROR server: error on processing request: can't perform https request: Post "https://anycast.uncensoreddns.org:443/dns-query": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
blocky    | [2022-10-13 12:48:38] ERROR server: error on processing request: can't perform https request: Post "https://anycast.uncensoreddns.org:443/dns-query": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
blocky    | [2022-10-13 12:48:42] ERROR server: error on processing request: can't perform https request: Post "https://anycast.uncensoreddns.org:443/dns-query": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
blocky    | [2022-10-13 12:48:42] ERROR server: error on processing request: can't perform https request: Post "https://anycast.uncensoreddns.org:443/dns-query": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
blocky    | [2022-10-13 12:48:44]  INFO queryLog: query resolved answer=A .... response_code=NOERROR response_reason=RESOLVED (https://anycast.uncensoreddns.org:443/dns-query)
blocky    | [2022-10-13 12:48:44]  INFO queryLog: query resolved answer=A .... response_code=NOERROR response_reason=RESOLVED (https://anycast.uncensoreddns.org:443/dns-query)
blocky    | [2022-10-13 12:48:44]  INFO queryLog: query resolved answer= .... response_code=NOERROR response_reason=RESOLVED (https://anycast.uncensoreddns.org:443/dns-query)
.....
```

I'm running a really basic setup on a Raspberry Pi 3b:

config.yaml
```
upstream:
  default:
#    - https://dns.adguard-dns.com/dns-query # AdGuard: https://adguard-dns.io/nl/public-dns.html
#    - https://cloudflare-dns.com/dns-query # Cloudflare: https://1.1.1.1/
    - https://anycast.uncensoreddns.org/dns-query # UncensoredDNS: https://blog.uncensoreddns.org/dns-servers/
blocking:
  refreshPeriod: 24h
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-social/hosts
  clientGroupsBlock:
    default:
      - ads
port: 53
httpPort: 4000
```

docker-compose.yaml
```
version: "2.1"
services:
  blocky:
    image: spx01/blocky:v0.18 or v0.19
    container_name: blocky
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    environment:
      - TZ=Europe/Amsterdam # Optional to synchronize the log timestamp with host
    volumes:
      - ./config.yml:/app/config.yml
```

Any idea why it initially times out in the container or how I can extend/bypass the checks in the new version? I've also tried the development tag of the container but that didn't fix the issue.

**Comment by kwitsch** [comment]
You should at least define one IP based DNS server to resolv the other URLs.
This could be done with a [bootstrap dns configuration](https://0xerr0r.github.io/blocky/configuration/#bootstrap-dns-configuration).

If I remember correctly previous versions used the host system DNS config to resolve these(?).
This caused problems if the docker host had blocky as DNS server configured.

**Comment by robinvalk** [comment]
Thank you for your quick reply.

Although my docker host doesn't have setup blocky directly, it is configured via my router's settings to connect to it. But the router has a fallback to an ip anyways. So that doesn't really explain the problem.

I've tested two things that both resolve my issue though:

First I added the `upstreamTimeout` property to the configuration with something like 20 seconds as it's value. This resolved the issue. I think docker might just be slow with proxying the dns or something to the host? 

The second solution: I added the mentioned bootstrapDns configuration as follows:
```
bootstrapDns:
  upstream: https://cloudflare-dns.com/dns-query
  ips:
    - 1.1.1.1
```
This also works and is probably the preferred solution.

Once again, thank you very much!
