### ISSUE TITLE
CustomDNS does not apply to root entry, only subdomains

### ISSUE THREAD

**Issue by j0sh3rs** [0xERR0R/blocky#695]
I'm trying to configure Blocky to resolve my public domain (example.com) as an internal IP address when I'm on my home network. In my case, I serve an endpoint at the root domain (https://example.com) as well as subdomains (https://grafana.example.com). When I do lookups against blocky, the subdomains resolve correctly with the rewrite/mapping setup below, however the root domain continues to resolve to public IPs.

My configuration block for this looks like:
```yaml
      customDNS:
        rewrite:
          example.com: nginx-ingress
        mapping:
          nginx-ingress: 192.168.35.16
```

Outputs from lookups:
```shell
$ dig +short @192.168.35.11 example.com
104.26.12.122
104.26.13.122
172.67.72.62
```
```shell
$ dig +short @192.168.35.11 grafana.example.com
192.168.35.16
```

Expectation: Blocky treats root level domain A records the same as subdomains, honoring the mapping/rewrite block.

**Comment by bcookatpcsd** [comment]
```
customDNS:
  mapping:
    pool.ntp.org: 172.16.254.241
```

```
./q a blah.pool.ntp.org @10.20.0.6
blah.pool.ntp.org. 1m0s A 172.16.254.241

./q a who.pool.ntp.org @10.20.0.6
who.pool.ntp.org. 1m0s A 172.16.254.241

./q a pool.ntp.org @10.20.0.6
pool.ntp.org. 1m0s A 172.16.254.241
```

**Comment by kwitsch** [comment]
As @bcookatpcsd already mentioned in your case the rewrite config isn't necessary.

This should suffice your needs:
```YAML
      customDNS:
        mapping:
           example.com: 192.168.35.16
```
