### ISSUE TITLE
permissions issue with samba

### ISSUE THREAD

**Issue by SimonMcN** [0xERR0R/blocky#747]
Hi,
I was wondering if you could enhance the project to have the user/group id in the env variables ?

I have a permissions issue which I do not know how to diagnose but is almost identical to the attached issue.

I can map the drive and the blocky user can create folders & files in it.

I tried docker exec -it blocky /bin/sh to try and diagnose but it didn't work

OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown

```
version: "2.1"
services:
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    ports:
      - "192.168.100.160:53:53/tcp"
      - "192.168.100.160:53:53/udp"
      - "4000:4000/tcp"
    environment:
      - TZ=Europe/London # Optional to synchronize the log timestamp with host
    volumes:
      # config file
      - "./config.yml:/app/config.yml"
      - "queryLogs:/logs/"

volumes:
  queryLogs:
    driver_opts:
      type: cifs
      o: username=blocky,password=redacted,uid=100,gid=100,rw
      device: "//192.168.100.240/blocky"

networks:
  default:
    external:
      name: isolated
```

//192.168.100.240/blocky on /var/lib/docker/volumes/blocky_queryLogs/_data type cifs (rw,relatime,vers=3.1.1,cache=strict,username=blocky,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.100.240,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=4194304,wsize=4194304,bsize=1048576,echo_interval=60,actimeo=1)

**Comment by SimonMcN** [comment]
#444 
Apologies, this is the issue referenced above.

**Comment by SimonMcN** [comment]
error:
```
[2022-11-14 14:45:29] ERROR fileQueryLogWriter: can't create/open fileopen /logs/2022-11-14_192_168_100_191.log: permission denied file_name=/logs/2022-11-14_192_168_100_191.log
[2022-11-14 14:45:29] ERROR fileQueryLogWriter: can't create/open fileopen /logs/2022-11-14_192_168_100_191.log: permission denied file_name=/logs/2022-11-14_192_168_100_191.log

```

**Comment by SimonMcN** [comment]
```
root@:/var/lib/docker/volumes/blocky_queryLogs/_data# ls -laR
.:
total 4
drwxr-xr-x 2 root root    0 Nov 14 13:39 .
drwx-----x 3 root root 4096 Nov 14 13:18 ..
drwxr-xr-x 2 root root    0 Nov 14 13:40 logs

./logs:
total 4
drwxr-xr-x 2 root root 0 Nov 14 13:40 .
drwxr-xr-x 2 root root 0 Nov 14 13:39 ..
-rwxr-xr-x 1 root root 5 Nov 14 13:39 fsdf.txt
drwxr-xr-x 2 root root 0 Nov 14 13:40 logs

./logs/logs:
total 0
drwxr-xr-x 2 root root 0 Nov 14 13:40 .
drwxr-xr-x 2 root root 0 Nov 14 13:40 ..
root@:/var/lib/docker/volumes/blocky_queryLogs/_data# echo bob >test.txt
root@:/var/lib/docker/volumes/blocky_queryLogs/_data# ls
logs  test.txt
root@:/var/lib/docker/volumes/blocky_queryLogs/_data#
```

**Comment by kwitsch** [comment]
> I was wondering if you could enhance the project to have the user/group id in the env variables ?

Would be troublesome as the binary runs as the configured user and therefore needs execution permission for the binary.

> I tried docker exec -it blocky /bin/sh to try and diagnose but it didn't work

The only binary inside the container is ´/app/blocky´ therefore this won't work.

I have a few suggestions:
- ´chown -R 100:65533´ on //192.168.100.240/blocky
- changing gid to 65533 as its the default group id
- remove the slash on the volume mount
- add explicit write permissions to the volume mount

Example:
```YAML
version: "3.8"

services:
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    ports:
      - "192.168.100.160:53:53/tcp"
      - "192.168.100.160:53:53/udp"
      - "4000:4000/tcp"
    environment:
      - TZ=Europe/London
    volumes:
      - ./config.yml:/app/config.yml:ro
      - queryLogs:/logs:rw

volumes:
  queryLogs:
    driver_opts:
      type: cifs
      o: username=blocky,password=redacted,uid=100,gid=65533,rw
      device: "//192.168.100.240/blocky"

networks:
  default:
    external:
      name: isolated
```
