### ISSUE TITLE
Use multiple upstreams for bootstrapDns.

### ISSUE THREAD

**Issue by ftpd** [0xERR0R/blocky#760]
Correct me if I'm wrong, but it seems now I can define only one upstream for bootstrapDns. In worst case scenario when my upstream is down, blocky won't download filters when started.

Can we have bootstrapDns.upstream as a list, maybe?

**Comment by 0xERR0R** [comment]
Yes, you're right, you can define only one bootstrap DNS server.

It would make sense to allow multiple bootstrap DNS server. Since we allow also the definition of IP addresses (for DoH and DoT):

```yaml
bootstrapDns:
      upstream: tcp-tls:dns.example.com
      ips:
      - 123.123.123.123
```

we can't just change upstream to a list structure (or comma separated string). I think, we need more complex structure and we should also support current config (to avoid breaking changes).

**Comment by ThinkChaos** [comment]
Started looking into this.

For the config, we should be able to transparently support the old format with something like:

```yaml
bootstrapDns:
  - upstream: tcp-tls:dns1.example.com
    ips:
      - 123.123.123.123
  - upstream: tcp-tls:dns2.example.com
    ips:
      - 456.456.456.456
```

For the implementation, there's a little refactoring needed, but I don't foresee anything major. The awkward part is that with multiple bootstrap upstreams, we want to race them using `ParallelBestResolver`, but that resolver uses the `Bootstrap` to test the upstreams it uses. So it's a dependency loop.  
There's code to bypass those checks, only used by tests at the moment, so my plan is to also use that for construction as part of the `Bootstrap`.
Hopefully I'll make a PR soon!
