### ISSUE TITLE
How to configure a domain name to resolve with specified dns

### ISSUE THREAD

**Issue by liang-hiwin** [0xERR0R/blocky#764]
I want to specify all domain names of google to be resolved using 8.8.8.8. How do I write the configuration

The following configuration seems incorrect

```
conditional:
  fallbackUpstream: false
  #rewrite:
  #  example.com: google.com
  mapping:
    google.com: 8.8.8.8
```

**Comment by 0xERR0R** [comment]
This configuration should work:

```yaml
conditional:
  mapping:
    google.com: 8.8.8.8  
```

It will resolve google.com and all subdomains (like www.google.com) via 8.8.8.8

Does it work for you?

**Comment by liang-hiwin** [comment]
> This configuration should work:
> 
> ```yaml
> conditional:
>   mapping:
>     google.com: 8.8.8.8  
> ```
> 
> It will resolve google.com and all subdomains (like [www.google.com](http://www.google.com)) via 8.8.8.8
> 
> Does it work for you?

Through the log, found that does not work

**Comment by liang-hiwin** [comment]
> This configuration should work:
> 
> ```yaml
> conditional:
>   mapping:
>     google.com: 8.8.8.8  
> ```
> 
> It will resolve google.com and all subdomains (like [www.google.com](http://www.google.com)) via 8.8.8.8
> 
> Does it work for you?

Is this a device effect? Why is the log not marked to use 8.8.8.8

```
2022-11-25 13:53:29	127.0.0.1	127.0.0.1	7	CONDITIONAL	A (google.com.)	A (142.251.43.14)	NOERROR
2022-11-25 13:53:29	127.0.0.1	127.0.0.1	6	CONDITIONAL	A (google.com.)	A (142.251.43.14)	NOERROR
```

**Comment by liang-hiwin** [comment]
The above log shows 2 identical 127.0.0.1 and 6 and 7 behind, what do they mean? @0xERR0R

**Comment by 0xERR0R** [comment]
> > This configuration should work:
> > 
> > ```yaml
> > conditional:
> >   mapping:
> >     google.com: 8.8.8.8  
> > ```
> > 
> > It will resolve google.com and all subdomains (like [www.google.com](http://www.google.com)) via 8.8.8.8
> > 
> > Does it work for you?
> 
> Is this a device effect? Why is the log not marked to use 8.8.8.8
> 
> ```
> 2022-11-25 13:53:29	127.0.0.1	127.0.0.1	7	CONDITIONAL	A (google.com.)	A (142.251.43.14)	NOERROR
> 2022-11-25 13:53:29	127.0.0.1	127.0.0.1	6	CONDITIONAL	A (google.com.)	A (142.251.43.14)	NOERROR
> ```
> 
> 

It works. If conditional resolver is invoked, it prints CONDITIONAL

**Comment by liang-hiwin** [comment]
> > > This configuration should work:
> > > ```yaml
> > > conditional:
> > >   mapping:
> > >     google.com: 8.8.8.8  
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > It will resolve google.com and all subdomains (like [www.google.com](http://www.google.com)) via 8.8.8.8
> > > Does it work for you?
> > 
> > 
> > Is this a device effect? Why is the log not marked to use 8.8.8.8
> > ```
> > 2022-11-25 13:53:29	127.0.0.1	127.0.0.1	7	CONDITIONAL	A (google.com.)	A (142.251.43.14)	NOERROR
> > 2022-11-25 13:53:29	127.0.0.1	127.0.0.1	6	CONDITIONAL	A (google.com.)	A (142.251.43.14)	NOERROR
> > ```
> 
> It works. If conditional resolver is invoked, it prints CONDITIONAL

ok，The above log shows 2 identical 127.0.0.1 and 6 and 7 behind, what do they mean? @0xERR0R

It is query duration in milliseconds

**Comment by liang-hiwin** [comment]
> > > This configuration should work:
> > > ```yaml
> > > conditional:
> > >   mapping:
> > >     google.com: 8.8.8.8  
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > It will resolve google.com and all subdomains (like [www.google.com](http://www.google.com)) via 8.8.8.8
> > > Does it work for you?
> > 
> > 
> > Is this a device effect? Why is the log not marked to use 8.8.8.8
> > ```
> > 2022-11-25 13:53:29	127.0.0.1	127.0.0.1	7	CONDITIONAL	A (google.com.)	A (142.251.43.14)	NOERROR
> > 2022-11-25 13:53:29	127.0.0.1	127.0.0.1	6	CONDITIONAL	A (google.com.)	A (142.251.43.14)	NOERROR
> > ```
> 
> It works. If conditional resolver is invoked, it prints CONDITIONAL

What if I use a group to resolve google's domain name? How to write configuration?

**Comment by liang-hiwin** [comment]
Is it correct to write like this? 

```
upstream:
  default:
    - 5.9.164.112
    - 1.1.1.1
    - tcp-tls:fdns1.dismail.de:853
    - https://dns.digitale-gesellschaft.ch/dns-query
  google:
    - 8..8.8.8
    - 8.8.4.4
    - https://dns.google/dns-query
  youtube:
    - 1.1.1.1
    - 9.9.9.9
    - 
conditional:
  mapping:
    google: 8.8.8.8  

```
