### ISSUE TITLE
Conditional DNS resolution question

### ISSUE THREAD

**Issue by liang-hiwin** [0xERR0R/blocky#769]
The program can't start when there are thousands of domain name conditional forwarding

```
conditional:
  fallbackUpstream: false
  mapping:
    domian1.com: https://dns.google.com/dns-query
    domian2.com: https://dns.google.com/dns-query
    domian3.com: https://dns.google.com/dns-query
    .....
    domian5000.com: https://dns.google.com/dns-query
```

**Comment by kwitsch** [comment]
Tested it with >2k conditional mapping entries. 
During upstart blocky will loockup every conditional mapping so it may take a while. 
For ~2K entries it took my machine around 3 minutes but started correctly in the end. 
Depending on your machine it may even take longer. 

If you are using docker you should defenetly edit the HEALTHCHECK configuration by adjusting the `--start-period=` to a value that is greater than your upstart with all those lookups. 

What exactly is your use case to define 5K conditional mappings?

**Comment by liang-hiwin** [comment]
> Tested it with >2k conditional mapping entries. During upstart blocky will loockup every conditional mapping so it may take a while. For ~2K entries it took my machine around 3 minutes but started correctly in the end. Depending on your machine it may even take longer.
> 
> If you are using docker you should defenetly edit the HEALTHCHECK configuration by adjusting the `--start-period=` to a value that is greater than your upstart with all those lookups.
> 
> What exactly is your use case to define 5K conditional mappings?

Hello, because our national dns pollutes some domain names, so I can only configure it like this.

**Comment by kwitsch** [comment]
> Hello, because our country's dns pollutes some domain names, so I can only configure it like this. The number of these tainted domains is a bit high.

Is there a reason to use this server as default upstream?
Wouldn't it be way simpler using `https://dns.google.com/dns-query` as default upstream instead?
Or are there country specific domains not listed in the google resolver?

Unfortunattly I can't replicate the described behavior. Could you set the loglevel to debug and provide the logoutput until the crash?

**Comment by liang-hiwin** [comment]
I know from your reply above that the program is not crashing, it's just that the program will look for each conditional mapping, so it may take a while

**Comment by 0xERR0R** [comment]
> During upstart blocky will loockup every conditional mapping so it may take a while.

Is it related to https://github.com/0xERR0R/blocky/issues/749 ?

**Comment by kwitsch** [comment]
@0xERR0R maybe we should test conditional upstream resolvers only once if they are defined multiple times? 🤔

**Comment by kwitsch** [comment]
> > During upstart blocky will loockup every conditional mapping so it may take a while.
> 
> Is it related to https://github.com/0xERR0R/blocky/issues/749 ?

Yeah I also think so.

**Comment by ThinkChaos** [comment]
What about changing the configuration to have a single place where we define upstreams, and then can reference them in other parts? That way we push users towards not repeating servers in the different sections, and the code validates them a single time via the central definition.  
Something like:
```yaml
upstreams: # name is confusing, please just focus on the layout of the file
  srv1: tcp-tls:srv1.example.com
  srv2: https://srv2.example.com/dns-query

bootstrapDns:
  upstream: srv1
  ips:
    - 1.2.3.4

upstream:
  default:
    - srv1
    - srv2
```

This would also make the config much more self-documenting IMO, and keeping track of server variants (for example: srv1-no-ads, srv1-no-malware, etc.) really easy.  
In the code we'd also have a single place where upstreams are validated, and not have to worry about that in different places (parallel and upstream resolvers). It would add a possible error of undefined upstreams though, but that should be handled in `validateConfig`, keeping the resolvers simpler.
