### ISSUE TITLE
Support for multiple conditional forwarders per domain

### ISSUE THREAD

**Issue by davmin** [0xERR0R/blocky#79]
Attempting to add multiple resolvers for conditional forwards gives an error. It would be good if Blocky supported to the ability to query multiple forwarders.

`level=fatal msg="wrong file structure: yaml: unmarshal errors:\n  line 31: key \"ipa.example.com\" already set in map\n  line 33: key \"ad.example.com\" already set in map\n `

```
conditional:
    mapping:
      ipa.example.com: udp:10.0.0.11
      ipa.example.com: udp:10.0.0.12
      ad.example.com: udp:10.0.1.11
      ad.example.com: udp:10.0.1.12
```

**Comment by 0xERR0R** [comment]
Currently, only one resolver is supported for a domain (internal configuration as map). I see the point with multiple resolvers for a domain. What would be the expectation: should blocky use one random resolver to resolve the address? Or same logic as with external resolvers (pick 2 random, query both, use answer from fastest)?

**Comment by davmin** [comment]
Whichever solution is picked should facilitate high availability of the external resolvers. 

Either 
- your second option, send to two, use the fastest
- like resolv.conf, query the first, if no response query the second and on down the list.

The former has the advantage of quicker response in case of failure. The latter has the advantage of not making unnecessary requests. I would lean towards the latter as I would think the most common usage for conditional forwarders would be for querying internal dns servers for internal dns zones, so there is not as much benefit to random selection and performance is likely to be similar between resolvers.

**Comment by NoctivagusObitus** [comment]
Hi,
I like support the explanation @davmin gave for the option proposed secondly.

Furthermore i like to add my case where I have multiple internal custom DNS resolver which i greatly prefer but which could be down due to me playing around with them (Server reboot, VPN connections etc.) and therefore like to have an reliable alternative. I am aware of and willing to accept longer resolution times until i fixed the issue i myself have introduced. Therefore i have been happy with dnsmasq `strict-order`-style nameserver choosing (but greatly prefer blocky since it it much more on point with what i need).

**Comment by 0xERR0R** [comment]
OK, I understand the use case and this feature is indeed useful. The change to multiple resolvers will probably break the current configuration, this is only the doubt I have. I'll take a look, maybe I can find a better solution.

**Comment by NoctivagusObitus** [comment]
At this point I like to add that i would appreciate the same (optional?) behavior for the upstream configuration
```
upstream:
    resolutionStyle: strict-order # additional option for configuration?
    externalResolvers:
        - 1.1.1.1
        - 2.2.2.2
```
That might be an additional enhancement which is a low hanging fruit after implementing this for conditional forwarding?

**Comment by 0xERR0R** [comment]
Upstream resolver uses weighted random to peek 2 upstream resolvers from the pool. Resolvers, which bring too much errors, get penalty. And only the fastest answer will be used as result.
This method is robust and if one resolver is temporary not available, it would use the second one as fallback. I don't see the reason to introduce another strategy and make it more complex

**Comment by NoctivagusObitus** [comment]
Alright, I agree with your statement to keep complexity low !

Just to briefly explain my thought process:
i have a situation where i have a custom DNS server which knows multiple other custom domains as well as a public upstream one. So it keeps configuration effort low to just use this one. But yet again it could be down so i like to give blocky its own public upstream fallback.
What i would gain in this case is that i do no need to put five or so conditional forwarded domains all to the same same server. 
But since this is on option and probably also the intended way of doing things i stick with this.

**Comment by 0xERR0R** [comment]
Multiple resolvers can now be specified as comma separated string. Example:

```yaml
conditional:
  mapping:
    lan.net: udp:192.168.178.1,udp:192.168.178.2
```

On request, random 2 resolvers from the list will be asked, the fastest answer will be uses (same behaviour as upstream configuration)

**Comment by NoctivagusObitus** [comment]
your example looks like `lan.net` would be a single string and you would parse (split) it yourself?
```yaml
conditional:
  mapping:
    lan.net: "udp:192.168.178.1,udp:192.168.178.2"
```

if so have you done this because it being more convenient then using YAML specific arrays?
example:
```yaml
conditional:
  mapping:
    lan1.net: [udp:192.168.178.1, udp:192.168.178.2]
    lan2.net:
      - udp:192.168.178.1
      - udp:192.168.178.2
```

that would account for some things stupid people like me tend to do like putting whitesapces where they are not intended to be
