### ISSUE TITLE
Blocking ccTLDs with Blocky

### ISSUE THREAD

**Issue by 0xLem0nade** [0xERR0R/blocky#807]
I'd like to block all domains with a certain ccTLD (e.g: `.cn`), I have the following in my config.yml but it's not working!

```
blocking:
  blackLists:
    ads:
      - https://adaway.org/hosts.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    special:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
    regional:
      - |
        # inline definition with YAML literal block scalar style
        ||*.cn^
        /^(?:https?:\/\/)?(?:[^\.]+\.)?.*\.cn(\/.*)?$

  clientGroupsBlock:
    default:
      - ads
      - special
      - regional
```

Any ideas?
