### ISSUE TITLE
[Question] How to use IPv6 addresses as bind IPs?

### ISSUE THREAD

**Issue by alpominth** [0xERR0R/blocky#829]
When I try to use an IPv6 address as a bind IP I get an error:

```
./blocky -c ./conf 
[2023-01-15 07:44:52] FATAL unable to load configuration: wrong file structure: yaml: line 3: did not find expected node content
```

I tried **[::1]:53**, **::1:53**, **[::1:53]** and **[::1#53]**, nothing works.

The configuration I want to use:

```
    upstream:
      default:
        - tcp+udp:[::1]:10053
    port: [::1]:53
    caching:
      minTime: 720m
      maxTime: 1440m
      prefetching: true
      maxItemsCount: 100000000
      cacheTimeNegative: -1
    redis:
      address: 127.0.0.1:6379
      database: 2
      required: true
      connectionAttempts: 10
      connectionCooldown: 3s
```

How can I use an IPv6 address as a bind IP?
