### ISSUE TITLE
[Feature request] ability to listen on multiple addresses/ports

### ISSUE THREAD

**Issue by alpominth** [0xERR0R/blocky#836]
Here I use a network namespace sandbox in which a DNS port is forwarded to a subnet in this way:

```
iptables -t nat -A PREROUTING -i subnet -p udp -s 10.0.0.2 -d 10.0.0.1 --dport 53 -j DNAT --to-destination 10.0.0.1:1053
ip6tables -t nat -A PREROUTING -i subnet -p udp -s fd00::1 -d fd00::1 --dport 53 -j DNAT --to-destination [fd00::1]:1053
```

The peer will have a UDP port 53 available in the IPv4 and IPv6 address for DNS resolution.

I could just set the addresses of bind IP in Blocky to [::]:1053, but it would listen on all ports of my machine, such thing is a undesirable behavior.

An option in Blocky to listen on multiple addresses/ports would be nice in this scenario, it could be like this:

`port: "10.0.0.1:53, [fd00::1]:53"`

Or

```
port: "10.0.0.1:53"
port: "[fd00::1]:53"
```

**Comment by 0xERR0R** [comment]
You can use multiple ports/interfaces, see https://0xerr0r.github.io/blocky/configuration/#basic-configuration. Did you try to specify ip/port as comma separated string like `127.0.0.1:53,[::1]:53`?

**Comment by alpominth** [comment]
No, I tried:

port "10.0.0.1:1053, [fd00::1]:1053"

and:

port 10.0.0.1:1053
port "[fd00::1]:1053"

But I found what was wrong, I used "quotes", I removed and it worked.

Thanks.

**Comment by ThinkChaos** [comment]
Quotes shouldn't change anything in this case: the value is parsed as a string regardless.  
I think the issue was the space.

**Comment by alpominth** [comment]
My config (now working):

```
    logLevel: error
    upstream:
      default:
        - tcp+udp:[::1]:10053
    upstreamTimeout: 10s
    port: 127.0.0.1:53,[::1]:53
    caching:
      minTime: 86400m
      maxTime: 86400m
      prefetching: true
      maxItemsCount: 131072
      cacheTimeNegative: 10080m
    redis:
      address: 127.0.0.1:6379
      database: 2
      required: true
      connectionAttempts: 10
      connectionCooldown: 0s
```

[::1]:10053 is the port of DNSCrypt.
