### ISSUE TITLE
[Feature Request] Pre group refresh period

### ISSUE THREAD

**Issue by shizunge** [0xERR0R/blocky#844]
Today we have a gloabl setting for the block/white refresh period.
```
blocking:
  refreshPeriod: 60m
```

Could you enhance this to set refresh period for each group?
E.g.
```
blocking:
  # global setting.
  refreshPeriod: 60m
  # new pre group settings.
  refreshPeriodForGroups:
    ads: 60m
```

Use case:
I maintain explicitly block list and white list. When I add/remove items to the lists, I hope blocky could pick them up immediately.
