### ISSUE TITLE
[Feature Request] Option to get hosts file from http url

### ISSUE THREAD

**Issue by adb76** [0xERR0R/blocky#867]
Hello,

as far a I understood the configuration options correctly, currently it is only possible to get a hosts configuration from a file on the file system:

```
hostsFile:
  filePath: /etc/hosts
  hostsTTL: 24h
  refreshPeriod: 6h
```

It would be great to have an option to get it additionally or optionally also from an http url (analog to the ad blacklists), e.g.:

```
hostsFile:
  hosts:
    - /etc/hosts
    - https://some.url/hosts
  hostsTTL: 24h
  refreshPeriod: 6h
```

What is the idea behind it? Well, I am using an DNS service to avoid geoip blocking, which offers an URL to an up to date hosts list, which of course can change over time. So the idea is to avoid manual download of that list - or to avoid to forget it to do so ;-) 

Kind regards.
