### ISSUE TITLE
Issue running blocky on k3s using ConfigMap

### ISSUE THREAD

**Issue by tech1ndex** [0xERR0R/blocky#877]
### Issue:

- Trying to deploy Blocky using a ConfigMap to pass minimal config to blocky
- Mounting "config.yml" configMap at /app
- Issue appears to be with entryPoint of /app/blocky, error complains about location of blocky:
`Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/app/blocky": stat /app/blocky: no such file or directory: unknown`

#### Deployment Spec for Ref:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-cm
  namespace: blocky
data:
  config.yml: |
    upstream:
      default:
        - 1.1.1.1
        - 8.8.8.8
    blocking:
      blackLists:
        ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      clientGroupsBlock:
        default:
          - ads
    port: 53
    httpPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocky
  namespace: blocky
spec:
  selector:
    matchLabels:
      app: blocky
  replicas: 1
  template:
    metadata:
      labels:
        app: blocky
    spec:
      containers:
      - name: blocky
        image: spx01/blocky:v0.20
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: blocky-config
          mountPath: /app
      volumes:
      - name: blocky-config
        configMap:
          name: blocky-cm
          items:
          - key: config.yml
            path: config.yml
```
