### ISSUE TITLE
[Bug] Prometheus blocky_prefetch_domain_name_cache_count showing inconsistent values if bootstrap is enabled

### ISSUE THREAD

**Issue by adb76** [0xERR0R/blocky#891]
Hello,

I'm using blocky 0.20. After playing a little bit around with the prefetch configuration and looking on the prometheus stats I saw that the value _blocky_prefetch_domain_name_cache_count_ sometimes jumps down to the value "7" and than after a few seconds up again to the value before. You can see that here directly on the graph:

![grafik](https://user-images.githubusercontent.com/7468139/220264048-5051139d-5d6c-4dd9-bdf7-823b03f77a2d.png)

Since it doesn't seem for me that the prefetch cache is cleared, is it only a reporting error of the prometheus endpoint?

Here you can see my current config:

```
upstream:
  default:
    - https://dns.quad9.net/dns-query
    - https://1.1.1.1/dns-query
    - https://dns0.eu

connectIPVersion: v4

clientLookup:
  upstream: 192.168.2.1
  singleNameOrder:
    - 1

conditional:
  mapping:
    fritz.box: 192.168.2.1
    168.192.in-addr.arpa: 192.168.2.1

blocking:
  blackLists:
    ads:
      - /app/blacklist.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/pro.plus.txt
      - https://gitlab.com/hagezi/mirror/-/raw/main/dns-blocklists/hosts/pro.plus.txt
    clean:
      - https://nsfw.oisd.nl/domains
    regional:
      - |
        # inline definition with YAML literal block scalar style
        /\.cn$/
        /\.ru$/
    empty:
  whiteLists:
    ads:
      - /app/whitelist.txt

  clientGroupsBlock:
    default:
      - ads
      - clean
      - regional

caching:
  minTime: 24h
  prefetching: true
  prefetchExpires: 6h
  prefetchThreshold: 6
  cacheTimeNegative: 24h

redis:
  address: 192.168.2.30:6379
  database: 0
  required: true
  connectionAttempts: 10
  connectionCooldown: 3s

queryLog:
  type: mysql
  target: (removed)
  logRetentionDays: 7
  creationAttempts: 6
  creationCooldown: 10s

port: 53
httpPort: 4000
bootstrapDns: tcp+udp:9.9.9.9

prometheus:
  enable: true
```

Kind regards.
