### ISSUE TITLE
odd behavior with regex in whitelist 

### ISSUE THREAD

**Issue by adamsewell** [0xERR0R/blocky#893]
I have the following regex in a custom whitelist with blocky with the goal of allowing an entire domain of proton.me and all subdomains. I'll also be the first to attempt that my regex knowledge is subpar so maybe it has something to do with my regex but I would have considered different actions by blocky. According to regex101, my pattern should make at least the api.proton.me and I would assume blocky would allow it. 

blocky version is 0.20

The regex pattern:
```regex
/([a-z0-9]+[.])*proton.me/
```

When this pattern is present, this is the log for 'account-api.proton.me' 
```
RESOLVED (tcp+udp:10.5.1.1)	A (account-api.proton.me.)		NOERROR
```

With this pattern removed, this is the log. 
```
RESOLVED (tcp+udp:10.5.1.1)	A (account-api.proton.me.)	CNAME (mail-api.proton.me.), A (185.70.42.41)	NOERROR
```
10.5.1.1 is a dns resolver on my pfsense router which has 9.9.9.9 and 1.1.1.1 set for upstream. 

What am I missing here or is this a bug?

**Comment by 0xERR0R** [comment]
I tried (latest development version) with following config:

```yaml
upstream:
  default:
    - 8.8.8.8
port: 55555
blocking:
  whiteLists:
    ads:
      - |
        /([a-z0-9]+[.])*proton.me/

  blackLists:
    ads:
      - |
        /proton/
  clientGroupsBlock:
    default:
      - ads
```

```sh
dig @localhost -p55555 account-api.proton.me

; <<>> DiG 9.16.1-Ubuntu <<>> @localhost -p55555 account-api.proton.me
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43771
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;account-api.proton.me.         IN      A

;; ANSWER SECTION:
account-api.proton.me.  113     IN      CNAME   mail-api.proton.me.
mail-api.proton.me.     113     IN      A       185.70.42.41

;; Query time: 8 msec
;; SERVER: ::1#55555(::1)
;; WHEN: Wed Feb 22 08:29:36 UTC 2023
;; MSG SIZE  rcvd: 89
```

If I remove the whitelist entry, the domain will be blocked as expected:

```sh
dig @localhost -p55555 account-api.proton.me

; <<>> DiG 9.16.1-Ubuntu <<>> @localhost -p55555 account-api.proton.me
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60361
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;account-api.proton.me.         IN      A

;; ANSWER SECTION:
account-api.proton.me.  21600   IN      A       0.0.0.0

;; Query time: 0 msec
;; SERVER: ::1#55555(::1)
;; WHEN: Wed Feb 22 08:30:24 UTC 2023
;; MSG SIZE  rcvd: 55
```

**Comment by adamsewell** [comment]
Odd, would you try removing /proton/ from your blacklists? I think that might be the only difference in our tests.

**Comment by 0xERR0R** [comment]
Sure,

following config:
```yaml
upstream:
  default:
    - 8.8.8.8
port: 55555
blocking:
  whiteLists:
    ads:
      - |
        /([a-z0-9]+[.])*proton.me/
  clientGroupsBlock:
    default:
      - ads
```

```sh
dig @localhost -p55555 account-api.proton.me

; <<>> DiG 9.16.1-Ubuntu <<>> @localhost -p55555 account-api.proton.me
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54428
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;account-api.proton.me.         IN      A

;; ANSWER SECTION:
account-api.proton.me.  247     IN      CNAME   mail-api.proton.me.
mail-api.proton.me.     554     IN      A       185.70.42.41

;; Query time: 8 msec
;; SERVER: ::1#55555(::1)
;; WHEN: Wed Feb 22 13:17:01 UTC 2023
;; MSG SIZE  rcvd: 89
```

Removing whitelist:

```yaml
upstream:
  default:
    - 8.8.8.8
port: 55555
```

```sh
dig @localhost -p55555 account-api.proton.me

; <<>> DiG 9.16.1-Ubuntu <<>> @localhost -p55555 account-api.proton.me
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5755
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;account-api.proton.me.         IN      A

;; ANSWER SECTION:
account-api.proton.me.  552     IN      CNAME   mail-api.proton.me.
mail-api.proton.me.     552     IN      A       185.70.42.41

;; Query time: 8 msec
;; SERVER: ::1#55555(::1)
;; WHEN: Wed Feb 22 13:18:31 UTC 2023
;; MSG SIZE  rcvd: 89
```
