### ISSUE TITLE
Two Log Outputs

### ISSUE THREAD

**Issue by padey** [0xERR0R/blocky#906]
Hi all.

Is there a possibility that two log destinations can be selected?

I would like to write all queries to an internal Postgres DB and the console output via syslog to a SIEM system. If I disable both log outputs, Blocky does not start (Docker).

It would be great if I could enable multiple sources or just enable the console output additionally.

Best regards!

**Comment by kwitsch** [comment]
Query logging shouldn`t interfer with the regular log output.
Could you provide an example config to better understand your issue?

**Comment by padey** [comment]
My Blocky config.yml looks like this right now:

```
...
#queryLog:
#  type: console
#  target: /logs
#  logRetentionDays: 30

queryLog:
  type: postgresql
  target: postgres://blocky:PWD@IP:PORT/blocky

logRetentionDays: 7
....
```  

When I remove the #, the container wont start. For example.. when the postgres is not reachable, the console output is activated.

**Comment by 0xERR0R** [comment]
so you want to log your query data (request, response etc) to postgres **and** CSV file? This is currently not possible, you can specify only one destination.

**Comment by padey** [comment]
Sorry, ignore the "target" part - thats uncommented in my config.. when I activate the console output, and in a second queryLog the postgres. I get the following error:

[2023-02-28 16:50:28] FATAL unable to load configuration: wrong file structure: yaml: unmarshal errors:
  line 96: field queryLog already set in type config.Config

**Comment by padey** [comment]
So here is my full config. When two types of queryLog are enabled, I get the error message above. 

```
upstream:
  default:
    -         ****
    -         ****

clientLookup:
  upstream:         ****
  singleNameOrder:
    - 2
    - 1
    - 
customDNS:
  customTTL: 1h
  mapping:
   asdfasdf:         ****

conditional:
    mapping:
        ****
        ****
        ****
        
        

blocking:
  blackLists:
    phishing:
     - https://phishing.army/download/phishing_army_blocklist_extended.txt
    malware:
     - https://urlhaus.abuse.ch/downloads/hostfile/
  clientGroupsBlock:
    default:
      - malware
      - phishing  

prometheus:
  enable: true

caching:
  minTime: 5m
  maxTime: 30m
  maxItemsCount: 0
  prefetching: true
  prefetchExpires: 2h
  prefetchThreshold: 5
  prefetchMaxItemsCount: 0
  cacheTimeNegative: 30m  

redis:
  address:         ****:6379
  database: 0
  required: false
  connectionAttempts: 10
  connectionCooldown: 3s
  
#queryLog:
#  type: console
#  logRetentionDays: 30

queryLog:
  type: postgresql
  target: postgres://        ****:        ****@        ****/blocky
  logRetentionDays: 7
  
port: 53
httpPort: 4000
```
