### ISSUE TITLE
always get  "field ports not found in type config.Config" error when I add ports section in config.yml

### ISSUE THREAD

**Issue by changchichung** [0xERR0R/blocky#941]
part of my config.yml

```
# optional: DNS listener port(s) and bind ip address(es), default 53 (UDP and TCP). Example: 53, :53, "127.0.0.1:5353,[::1]:5353"
#port: 5356
#port: 53

ports:
  # optional: DNS listener port(s) and bind ip address(es), default 53 (UDP and TCP). Example: 53, :53, "127.0.0.1:5353,[::1]:5353"
  dns: 53
  # optional: Port(s) and bind ip address(es) for DoT (DNS-over-TLS) listener. Example: 853, 127.0.0.1:853
  tls: 853
  # optional: Port(s) and optional bind ip address(es) to serve HTTPS used for prometheus metrics, pprof, REST API, DoH... If you wish to specify a specific IP, you can do so such as 192.168.0.1:443. Example: 443, :443, 127.0.0.1:443,[::1]:443
  https: 443
  # optional: Port(s) and optional bind ip address(es) to serve HTTP used for prometheus metrics, pprof, REST API, DoH... If you wish to specify a specific IP, you can do so such as 192.168.0.1:4000. Example: 4000, :4000, 127.0.0.1:4000,[::1]:4000
  http: 4000

hostsFile:
  # optional: Path to hosts file (e.g. /etc/hosts on Linux)
  filePath: /etc/hosts
  # optional: TTL, default: 1h
  hostsTTL: 60m
  # optional: Time between hosts file refresh, default: 1h
  refreshPeriod: 30m
  # optional: Whether loopback hosts addresses (127.0.0.0/8 and ::1) should be filtered or not, default: false
  filterLoopback: true
```

I use supervisor to start blocky , and here is the supervisor log
```
[2023-03-20 16:02:45] FATAL unable to load configuration: wrong file structure: yaml: unmarshal errors:
  line 74: field ports not found in type config.Config
[2023-03-20 16:02:47] FATAL unable to load configuration: wrong file structure: yaml: unmarshal errors:
  line 74: field ports not found in type config.Config
```

but I can not find any error in my config , I just copy that ports section from 
https://github.com/0xERR0R/blocky/blob/main/docs/config.yml

any suggestions ??

**Comment by kwitsch** [comment]
It was restructured during development and isn't present in the last release.
You could eighter use the development build, wait for the next release or use the old config fields.

Old config fields:
```YAML
port: 53
httpPort: 4000
httpsPort: 443
tlsPort: 853
```
