### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by tcurdt** [0xERR0R/blocky#975]
This is a weird one. I suspect it's me not having blocky configured correctly

```
port: 53
httpPort: 4000
logLevel: error
prometheus:
  enable: true
  path: /metrics

upstream:
  default:
    # opendns
    - 208.67.222.123
    - 208.67.220.123
    # google
    - 8.8.8.8
    - 8.8.4.4
    # cloudflare
    - 1.1.1.1
    # quad9
    - 9.9.9.9
    - 149.112.112.112

customDNS:
  customTTL: 1h
  filterUnmappedTypes: true
  mapping:
    # devices

blocking:
  refreshPeriod: 24h
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
```

but I cannot fully make sense of this yet.

When using blocky (spx01/blocky:v0.21) as dns resolver making request to some domains (for example) 

   https://my.zerotier.com
 
 I end up with a NET::ERR_CERT_AUTHORITY_INVALID.
 
<img width="511" alt="Screenshot 2023-04-03 at 16 46 48" src="https://user-images.githubusercontent.com/13697/229545891-c405919a-9e4f-49f0-bf73-311be6bcdb0a.png">

When I switch my local dns settings from blocky to just `1.1.1.1` everything resolves just fine.

Importing the sub CA cannot really be the answer here.
What's going on?
